# GENERATED by tools/codegen — DO NOT EDIT
# Source: ordercloud-openapi-v3.json
"""OrderCloud Addresses API resource."""

from __future__ import annotations
from typing import Any, Optional, Union

from ..models.address import Address
from ..models.assignments import AddressAssignment
from ..models.misc import PartyType
from ..models.shared import ListPage
from .base import BaseResource

__all__ = ["AddressesResource"]


class AddressesResource(BaseResource):
    """Operations on OrderCloud Addresses."""

    async def list(
        self,
        buyer_id: str,
        *,
        search: Optional[str] = None,
        search_on: Optional[str] = None,
        sort_by: Optional[str] = None,
        page: Optional[int] = None,
        page_size: Optional[int] = None,
        filters: Optional[dict[str, Any]] = None,
    ) -> ListPage[Address]:
        """List addresses

        Args:
            buyer_id: ID of the buyer.
            search: Word or phrase to search for.
            search_on: Comma-delimited list of fields to search on.
            sort_by: Comma-delimited list of fields to sort by.
            page: Page of results to return. When paginating through many items (> page 30), we recommend the "Last ID" method, as outlined in the Advanced Querying documentation.
            page_size: Number of results to return per page.
            filters: An object or dictionary representing key/value pairs to apply as filters. Valid keys are top-level properties of the returned model or 'xp.???'

        Returns:
            A paginated list of Address objects.
        """
        params = self._build_list_params(
            search=search,
            search_on=search_on,
            sort_by=sort_by,
            page=page,
            page_size=page_size,
            filters=filters,
        )
        resp = await self._http.get(f"/buyers/{buyer_id}/addresses", **params)
        return self._parse_list(resp.json(), Address)

    async def create(
        self,
        buyer_id: str,
        address: Union[Address, dict[str, Any]],
    ) -> Address:
        """Create an address

        Args:
            buyer_id: ID of the buyer.
            address: A ``Address`` model or dict. Required fields: Street1, City, Country.

        Returns:
            The Address object.
        """
        resp = await self._http.post(f"/buyers/{buyer_id}/addresses", json=self._serialize(address))
        return Address(**resp.json())

    async def get(
        self,
        buyer_id: str,
        address_id: str,
    ) -> Address:
        """Retrieve an address

        Args:
            buyer_id: ID of the buyer.
            address_id: ID of the address.

        Returns:
            The Address object.
        """
        resp = await self._http.get(f"/buyers/{buyer_id}/addresses/{address_id}")
        return Address(**resp.json())

    async def save(
        self,
        buyer_id: str,
        address_id: str,
        address: Union[Address, dict[str, Any]],
    ) -> Address:
        """Create or update an address

        Args:
            buyer_id: ID of the buyer.
            address_id: ID of the address.
            address: A ``Address`` model or dict. Required fields: Street1, City, Country.

        Returns:
            The Address object.
        """
        resp = await self._http.put(
            f"/buyers/{buyer_id}/addresses/{address_id}",
            json=self._serialize(address),
        )
        return Address(**resp.json())

    async def delete(
        self,
        buyer_id: str,
        address_id: str,
    ) -> None:
        """Delete an address

        Args:
            buyer_id: ID of the buyer.
            address_id: ID of the address.
        """
        await self._http.delete(f"/buyers/{buyer_id}/addresses/{address_id}")

    async def patch(
        self,
        buyer_id: str,
        address_id: str,
        partial: dict[str, Any],
    ) -> Address:
        """Partially update an address

        Args:
            buyer_id: ID of the buyer.
            address_id: ID of the address.
            partial: A dict of fields to update.

        Returns:
            The Address object.
        """
        resp = await self._http.patch(f"/buyers/{buyer_id}/addresses/{address_id}", json=partial)
        return Address(**resp.json())

    async def delete_assignment(
        self,
        buyer_id: str,
        address_id: str,
        *,
        user_id: Optional[str] = None,
        user_group_id: Optional[str] = None,
    ) -> None:
        """Delete an address assignment

        Args:
            buyer_id: ID of the buyer.
            address_id: ID of the address.
            user_id: ID of the user.
            user_group_id: ID of the user group.
        """
        _params: dict[str, Any] = {}
        if user_id is not None:
            _params["userID"] = user_id
        if user_group_id is not None:
            _params["userGroupID"] = user_group_id
        await self._http.delete(f"/buyers/{buyer_id}/addresses/{address_id}/assignments", **_params)

    async def list_assignments(
        self,
        buyer_id: str,
        *,
        address_id: Optional[str] = None,
        user_id: Optional[str] = None,
        user_group_id: Optional[str] = None,
        level: Optional[PartyType] = None,
        is_shipping: Optional[bool] = None,
        is_billing: Optional[bool] = None,
        page: Optional[int] = None,
        page_size: Optional[int] = None,
    ) -> ListPage[AddressAssignment]:
        """List address assignments

        Args:
            buyer_id: ID of the buyer.
            address_id: ID of the address.
            user_id: ID of the user.
            user_group_id: ID of the user group.
            level: Level of the address assignment. Possible values: User, Group, Company, BuyerGroup.
            is_shipping: Is shipping of the address assignment.
            is_billing: Is billing of the address assignment.
            page: Page of results to return. When paginating through many items (> page 30), we recommend the "Last ID" method, as outlined in the Advanced Querying documentation.
            page_size: Number of results to return per page.

        Returns:
            A paginated list of AddressAssignment objects.
        """
        params = self._build_list_params(
            page=page,
            page_size=page_size,
        )
        if address_id is not None:
            params["addressID"] = address_id
        if user_id is not None:
            params["userID"] = user_id
        if user_group_id is not None:
            params["userGroupID"] = user_group_id
        if level is not None:
            params["level"] = level
        if is_shipping is not None:
            params["isShipping"] = is_shipping
        if is_billing is not None:
            params["isBilling"] = is_billing
        resp = await self._http.get(f"/buyers/{buyer_id}/addresses/assignments", **params)
        return self._parse_list(resp.json(), AddressAssignment)

    async def save_assignment(
        self,
        buyer_id: str,
        address_assignment: Union[AddressAssignment, dict[str, Any]],
    ) -> None:
        """Create or update an address assignment

        Args:
            buyer_id: ID of the buyer.
            address_assignment: A ``AddressAssignment`` model or dict. Required fields: AddressID.
        """
        await self._http.post(
            f"/buyers/{buyer_id}/addresses/assignments", json=self._serialize(address_assignment)
        )
