# GENERATED by tools/codegen — DO NOT EDIT
# Source: ordercloud-openapi-v3.json
"""OrderCloud AdminAddresses API resource."""

from __future__ import annotations
from typing import Any, Optional, Union

from ..models.address import Address
from ..models.shared import ListPage
from .base import BaseResource

__all__ = ["AdminAddressesResource"]


class AdminAddressesResource(BaseResource):
    """Operations on OrderCloud AdminAddresses."""

    async def list(
        self,
        *,
        search: Optional[str] = None,
        search_on: Optional[str] = None,
        sort_by: Optional[str] = None,
        page: Optional[int] = None,
        page_size: Optional[int] = None,
        filters: Optional[dict[str, Any]] = None,
    ) -> ListPage[Address]:
        """List admin addresses

        Args:
            search: Word or phrase to search for.
            search_on: Comma-delimited list of fields to search on.
            sort_by: Comma-delimited list of fields to sort by.
            page: Page of results to return. When paginating through many items (> page 30), we recommend the "Last ID" method, as outlined in the Advanced Querying documentation.
            page_size: Number of results to return per page.
            filters: An object or dictionary representing key/value pairs to apply as filters. Valid keys are top-level properties of the returned model or 'xp.???'

        Returns:
            A paginated list of Address objects.
        """
        params = self._build_list_params(
            search=search,
            search_on=search_on,
            sort_by=sort_by,
            page=page,
            page_size=page_size,
            filters=filters,
        )
        resp = await self._http.get("/addresses", **params)
        return self._parse_list(resp.json(), Address)

    async def create(
        self,
        address: Union[Address, dict[str, Any]],
    ) -> Address:
        """Create an admin address

        Args:
            address: A ``Address`` model or dict. Required fields: Street1, City, Country.

        Returns:
            The Address object.
        """
        resp = await self._http.post("/addresses", json=self._serialize(address))
        return Address(**resp.json())

    async def get(
        self,
        address_id: str,
    ) -> Address:
        """Retrieve an admin address

        Args:
            address_id: ID of the address.

        Returns:
            The Address object.
        """
        resp = await self._http.get(f"/addresses/{address_id}")
        return Address(**resp.json())

    async def save(
        self,
        address_id: str,
        address: Union[Address, dict[str, Any]],
    ) -> Address:
        """Create or update an admin address

        Args:
            address_id: ID of the address.
            address: A ``Address`` model or dict. Required fields: Street1, City, Country.

        Returns:
            The Address object.
        """
        resp = await self._http.put(
            f"/addresses/{address_id}",
            json=self._serialize(address),
        )
        return Address(**resp.json())

    async def delete(
        self,
        address_id: str,
    ) -> None:
        """Delete an admin address

        Args:
            address_id: ID of the address.
        """
        await self._http.delete(f"/addresses/{address_id}")

    async def patch(
        self,
        address_id: str,
        partial: dict[str, Any],
    ) -> Address:
        """Partially update an admin address

        Args:
            address_id: ID of the address.
            partial: A dict of fields to update.

        Returns:
            The Address object.
        """
        resp = await self._http.patch(f"/addresses/{address_id}", json=partial)
        return Address(**resp.json())
