# GENERATED by tools/codegen — DO NOT EDIT
# Source: ordercloud-openapi-v3.json
"""OrderCloud ApiClients API resource."""

from __future__ import annotations
from typing import Any, Optional, Union

from ..models.api_client import ApiClient, ApiClientSecret, ApiClientSecretCreateResponse
from ..models.assignments import ApiClientAssignment
from ..models.shared import ListPage
from .base import BaseResource

__all__ = ["ApiClientsResource"]


class ApiClientsResource(BaseResource):
    """Operations on OrderCloud ApiClients."""

    async def list(
        self,
        *,
        search: Optional[str] = None,
        search_on: Optional[str] = None,
        sort_by: Optional[str] = None,
        page: Optional[int] = None,
        page_size: Optional[int] = None,
        filters: Optional[dict[str, Any]] = None,
    ) -> ListPage[ApiClient]:
        """List API clients

        Args:
            search: Word or phrase to search for.
            search_on: Comma-delimited list of fields to search on.
            sort_by: Comma-delimited list of fields to sort by.
            page: Page of results to return. When paginating through many items (> page 30), we recommend the "Last ID" method, as outlined in the Advanced Querying documentation.
            page_size: Number of results to return per page.
            filters: An object or dictionary representing key/value pairs to apply as filters. Valid keys are top-level properties of the returned model or 'xp.???'

        Returns:
            A paginated list of ApiClient objects.
        """
        params = self._build_list_params(
            search=search,
            search_on=search_on,
            sort_by=sort_by,
            page=page,
            page_size=page_size,
            filters=filters,
        )
        resp = await self._http.get("/apiclients", **params)
        return self._parse_list(resp.json(), ApiClient)

    async def create(
        self,
        api_client: Union[ApiClient, dict[str, Any]],
    ) -> ApiClient:
        """Create an API client

        Args:
            api_client: A ``ApiClient`` model or dict. Required fields: AccessTokenDuration, AppName.

        Returns:
            The ApiClient object.
        """
        resp = await self._http.post("/apiclients", json=self._serialize(api_client))
        return ApiClient(**resp.json())

    async def get(
        self,
        api_client_id: str,
    ) -> ApiClient:
        """Retrieve an API client

        Args:
            api_client_id: ID of the api client.

        Returns:
            The ApiClient object.
        """
        resp = await self._http.get(f"/apiclients/{api_client_id}")
        return ApiClient(**resp.json())

    async def save(
        self,
        api_client_id: str,
        api_client: Union[ApiClient, dict[str, Any]],
    ) -> ApiClient:
        """Create or update an API client

        Args:
            api_client_id: ID of the api client.
            api_client: A ``ApiClient`` model or dict. Required fields: AccessTokenDuration, AppName.

        Returns:
            The ApiClient object.
        """
        resp = await self._http.put(
            f"/apiclients/{api_client_id}",
            json=self._serialize(api_client),
        )
        return ApiClient(**resp.json())

    async def delete(
        self,
        api_client_id: str,
    ) -> None:
        """Delete an API client

        Args:
            api_client_id: ID of the api client.
        """
        await self._http.delete(f"/apiclients/{api_client_id}")

    async def patch(
        self,
        api_client_id: str,
        partial: dict[str, Any],
    ) -> ApiClient:
        """Partially update an API client

        Args:
            api_client_id: ID of the api client.
            partial: A dict of fields to update.

        Returns:
            The ApiClient object.
        """
        resp = await self._http.patch(f"/apiclients/{api_client_id}", json=partial)
        return ApiClient(**resp.json())

    async def list_secrets(
        self,
        api_client_id: str,
        *,
        search: Optional[str] = None,
        search_on: Optional[str] = None,
        sort_by: Optional[str] = None,
        page: Optional[int] = None,
        page_size: Optional[int] = None,
        filters: Optional[dict[str, Any]] = None,
    ) -> ListPage[ApiClientSecret]:
        """List API client secrets

        Args:
            api_client_id: ID of the api client.
            search: Word or phrase to search for.
            search_on: Comma-delimited list of fields to search on.
            sort_by: Comma-delimited list of fields to sort by.
            page: Page of results to return. When paginating through many items (> page 30), we recommend the "Last ID" method, as outlined in the Advanced Querying documentation.
            page_size: Number of results to return per page.
            filters: An object or dictionary representing key/value pairs to apply as filters. Valid keys are top-level properties of the returned model or 'xp.???'

        Returns:
            A paginated list of ApiClientSecret objects.
        """
        params = self._build_list_params(
            search=search,
            search_on=search_on,
            sort_by=sort_by,
            page=page,
            page_size=page_size,
            filters=filters,
        )
        resp = await self._http.get(f"/apiclients/{api_client_id}/secrets", **params)
        return self._parse_list(resp.json(), ApiClientSecret)

    async def create_secret(
        self,
        api_client_id: str,
        api_client_secret: Union[ApiClientSecret, dict[str, Any]],
    ) -> ApiClientSecretCreateResponse:
        """Create an API client secret

        Args:
            api_client_id: ID of the api client.
            api_client_secret: A ``ApiClientSecret`` model or dict. Required fields: Name.

        Returns:
            The ApiClientSecretCreateResponse object.
        """
        resp = await self._http.post(
            f"/apiclients/{api_client_id}/secrets", json=self._serialize(api_client_secret)
        )
        return ApiClientSecretCreateResponse(**resp.json())

    async def get_secret(
        self,
        api_client_id: str,
        api_client_secret_id: str,
    ) -> ApiClientSecret:
        """Retrieve an API client secret

        Args:
            api_client_id: ID of the api client.
            api_client_secret_id: ID of the api client secret.

        Returns:
            The ApiClientSecret object.
        """
        resp = await self._http.get(f"/apiclients/{api_client_id}/secrets/{api_client_secret_id}")
        return ApiClientSecret(**resp.json())

    async def delete_secret(
        self,
        api_client_id: str,
        api_client_secret_id: str,
    ) -> None:
        """Delete an API client secret

        Args:
            api_client_id: ID of the api client.
            api_client_secret_id: ID of the api client secret.
        """
        await self._http.delete(f"/apiclients/{api_client_id}/secrets/{api_client_secret_id}")

    async def patch_secret(
        self,
        api_client_id: str,
        api_client_secret_id: str,
        partial: dict[str, Any],
    ) -> ApiClientSecret:
        """Partially update an API client secret

        Args:
            api_client_id: ID of the api client.
            api_client_secret_id: ID of the api client secret.
            partial: A dict of fields to update.

        Returns:
            The ApiClientSecret object.
        """
        resp = await self._http.patch(
            f"/apiclients/{api_client_id}/secrets/{api_client_secret_id}", json=partial
        )
        return ApiClientSecret(**resp.json())

    async def list_assignments(
        self,
        *,
        api_client_id: Optional[str] = None,
        buyer_id: Optional[str] = None,
        supplier_id: Optional[str] = None,
        page: Optional[int] = None,
        page_size: Optional[int] = None,
    ) -> ListPage[ApiClientAssignment]:
        """List API client assignments

        Args:
            api_client_id: ID of the api client.
            buyer_id: ID of the buyer.
            supplier_id: ID of the supplier.
            page: Page of results to return. When paginating through many items (> page 30), we recommend the "Last ID" method, as outlined in the Advanced Querying documentation.
            page_size: Number of results to return per page.

        Returns:
            A paginated list of ApiClientAssignment objects.
        """
        params = self._build_list_params(
            page=page,
            page_size=page_size,
        )
        if api_client_id is not None:
            params["apiClientID"] = api_client_id
        if buyer_id is not None:
            params["buyerID"] = buyer_id
        if supplier_id is not None:
            params["supplierID"] = supplier_id
        resp = await self._http.get("/apiclients/assignments", **params)
        return self._parse_list(resp.json(), ApiClientAssignment)

    async def save_assignment(
        self,
        api_client_assignment: Union[ApiClientAssignment, dict[str, Any]],
    ) -> None:
        """Create or update an API client assignment

        Args:
            api_client_assignment: A ``ApiClientAssignment`` model or dict. Required fields: ApiClientID.
        """
        await self._http.post(
            "/apiclients/assignments", json=self._serialize(api_client_assignment)
        )

    async def delete_buyer_assignment(
        self,
        api_client_id: str,
        buyer_id: str,
    ) -> None:
        """Delete an API client buyer assignment

        Args:
            api_client_id: ID of the api client.
            buyer_id: ID of the buyer.
        """
        await self._http.delete(f"/buyers/{buyer_id}/ApiClients/Assignments/{api_client_id}")

    async def delete_supplier_assignment(
        self,
        api_client_id: str,
        supplier_id: str,
    ) -> None:
        """Delete an API client supplier assignment

        Args:
            api_client_id: ID of the api client.
            supplier_id: ID of the supplier.
        """
        await self._http.delete(f"/suppliers/{supplier_id}/ApiClients/Assignments/{api_client_id}")
