# GENERATED by tools/codegen — DO NOT EDIT
# Source: ordercloud-openapi-v3.json
"""OrderCloud BundleSubscriptionItems API resource."""

from __future__ import annotations
from typing import Any, Union

from ..models.line_item import BundleItems, LineItem
from .base import BaseResource

__all__ = ["BundleSubscriptionItemsResource"]


class BundleSubscriptionItemsResource(BaseResource):
    """Operations on OrderCloud BundleSubscriptionItems."""

    async def create(
        self,
        subscription_id: str,
        bundle_id: str,
        bundle_items: Union[BundleItems, dict[str, Any]],
    ) -> LineItem:
        """Create a bundle subscription item

        Args:
            subscription_id: ID of the subscription.
            bundle_id: ID of the bundle.
            bundle_items: A ``BundleItems`` model or dict.

        Returns:
            The LineItem object.
        """
        resp = await self._http.post(
            f"/subscriptions/{subscription_id}/bundles/{bundle_id}",
            json=self._serialize(bundle_items),
        )
        return LineItem(**resp.json())

    async def delete(
        self,
        subscription_id: str,
        bundle_id: str,
        bundle_item_id: str,
    ) -> None:
        """Delete a bundle subscription item

        Args:
            subscription_id: ID of the subscription.
            bundle_id: ID of the bundle.
            bundle_item_id: ID of the bundle item.
        """
        await self._http.delete(
            f"/subscriptions/{subscription_id}/bundles/{bundle_id}/{bundle_item_id}"
        )
