# GENERATED by tools/codegen — DO NOT EDIT
# Source: ordercloud-openapi-v3.json
"""OrderCloud BundleLineItems API resource."""

from __future__ import annotations
from typing import Any, Union

from ..models.line_item import BundleItems, LineItem
from ..models.misc import OrderDirection
from .base import BaseResource

__all__ = ["BundleLineItemsResource"]


class BundleLineItemsResource(BaseResource):
    """Operations on OrderCloud BundleLineItems."""

    async def create(
        self,
        direction: OrderDirection,
        order_id: str,
        bundle_id: str,
        bundle_items: Union[BundleItems, dict[str, Any]],
    ) -> LineItem:
        """Create a bundle line item

        Args:
            direction: Direction of the order, from the current user's perspective.
            order_id: ID of the order.
            bundle_id: ID of the bundle.
            bundle_items: A ``BundleItems`` model or dict.

        Returns:
            The LineItem object.
        """
        resp = await self._http.post(
            f"/orders/{direction}/{order_id}/bundles/{bundle_id}",
            json=self._serialize(bundle_items),
        )
        return LineItem(**resp.json())

    async def delete(
        self,
        direction: OrderDirection,
        order_id: str,
        bundle_id: str,
        bundle_item_id: str,
    ) -> None:
        """Delete a bundle line item

        Args:
            direction: Direction of the order, from the current user's perspective.
            order_id: ID of the order.
            bundle_id: ID of the bundle.
            bundle_item_id: ID of the bundle item.
        """
        await self._http.delete(
            f"/orders/{direction}/{order_id}/bundles/{bundle_id}/{bundle_item_id}"
        )
