# GENERATED by tools/codegen — DO NOT EDIT
# Source: ordercloud-openapi-v3.json
"""OrderCloud Categories API resource."""

from __future__ import annotations
from typing import Any, Optional, Union

from ..models.assignments import (
    CategoryAssignment,
    CategoryBundleAssignment,
    CategoryProductAssignment,
)
from ..models.category import Category
from ..models.shared import ListPage
from .base import BaseResource

__all__ = ["CategoriesResource"]


class CategoriesResource(BaseResource):
    """Operations on OrderCloud Categories."""

    async def list(
        self,
        catalog_id: str,
        *,
        depth: Optional[str] = None,
        search: Optional[str] = None,
        search_on: Optional[str] = None,
        sort_by: Optional[str] = None,
        page: Optional[int] = None,
        page_size: Optional[int] = None,
        filters: Optional[dict[str, Any]] = None,
    ) -> ListPage[Category]:
        """List categories

        Args:
            catalog_id: ID of the catalog.
            depth: Depth of the category.
            search: Word or phrase to search for.
            search_on: Comma-delimited list of fields to search on.
            sort_by: Comma-delimited list of fields to sort by.
            page: Page of results to return. When paginating through many items (> page 30), we recommend the "Last ID" method, as outlined in the Advanced Querying documentation.
            page_size: Number of results to return per page.
            filters: An object or dictionary representing key/value pairs to apply as filters. Valid keys are top-level properties of the returned model or 'xp.???'

        Returns:
            A paginated list of Category objects.
        """
        params = self._build_list_params(
            depth=depth,
            search=search,
            search_on=search_on,
            sort_by=sort_by,
            page=page,
            page_size=page_size,
            filters=filters,
        )
        resp = await self._http.get(f"/catalogs/{catalog_id}/categories", **params)
        return self._parse_list(resp.json(), Category)

    async def create(
        self,
        catalog_id: str,
        category: Union[Category, dict[str, Any]],
        *,
        adjust_list_orders: Optional[bool] = None,
    ) -> Category:
        """Create a category

        Args:
            catalog_id: ID of the catalog.
            category: A ``Category`` model or dict. Required fields: Name.
            adjust_list_orders: Adjust list orders of the category.

        Returns:
            The Category object.
        """
        resp = await self._http.post(
            f"/catalogs/{catalog_id}/categories", json=self._serialize(category)
        )
        return Category(**resp.json())

    async def get(
        self,
        catalog_id: str,
        category_id: str,
    ) -> Category:
        """Retrieve a category

        Args:
            catalog_id: ID of the catalog.
            category_id: ID of the category.

        Returns:
            The Category object.
        """
        resp = await self._http.get(f"/catalogs/{catalog_id}/categories/{category_id}")
        return Category(**resp.json())

    async def save(
        self,
        catalog_id: str,
        category_id: str,
        category: Union[Category, dict[str, Any]],
        *,
        adjust_list_orders: Optional[bool] = None,
    ) -> Category:
        """Create or update a category

        Args:
            catalog_id: ID of the catalog.
            category_id: ID of the category.
            category: A ``Category`` model or dict. Required fields: Name.
            adjust_list_orders: Adjust list orders of the category.

        Returns:
            The Category object.
        """
        resp = await self._http.put(
            f"/catalogs/{catalog_id}/categories/{category_id}",
            json=self._serialize(category),
        )
        return Category(**resp.json())

    async def delete(
        self,
        catalog_id: str,
        category_id: str,
    ) -> None:
        """Delete a category

        Args:
            catalog_id: ID of the catalog.
            category_id: ID of the category.
        """
        await self._http.delete(f"/catalogs/{catalog_id}/categories/{category_id}")

    async def patch(
        self,
        catalog_id: str,
        category_id: str,
        partial: dict[str, Any],
        *,
        adjust_list_orders: Optional[bool] = None,
    ) -> Category:
        """Partially update a category

        Args:
            catalog_id: ID of the catalog.
            category_id: ID of the category.
            partial: A dict of fields to update.
            adjust_list_orders: Adjust list orders of the partial 1.

        Returns:
            The Category object.
        """
        resp = await self._http.patch(
            f"/catalogs/{catalog_id}/categories/{category_id}", json=partial
        )
        return Category(**resp.json())

    async def delete_assignment(
        self,
        catalog_id: str,
        category_id: str,
        *,
        buyer_id: Optional[str] = None,
        user_id: Optional[str] = None,
        user_group_id: Optional[str] = None,
    ) -> None:
        """Delete a category assignment

        Args:
            catalog_id: ID of the catalog.
            category_id: ID of the category.
            buyer_id: ID of the buyer.
            user_id: ID of the user.
            user_group_id: ID of the user group.
        """
        await self._http.delete(f"/catalogs/{catalog_id}/categories/{category_id}/assignments")

    async def delete_bundle_assignment(
        self,
        catalog_id: str,
        category_id: str,
        bundle_id: str,
    ) -> None:
        """Delete a category bundle assignment

        Args:
            catalog_id: ID of the catalog.
            category_id: ID of the category.
            bundle_id: ID of the bundle.
        """
        await self._http.delete(
            f"/catalogs/{catalog_id}/categories/{category_id}/bundleassignments/{bundle_id}"
        )

    async def delete_product_assignment(
        self,
        catalog_id: str,
        category_id: str,
        product_id: str,
    ) -> None:
        """Delete a category product assignment

        Args:
            catalog_id: ID of the catalog.
            category_id: ID of the category.
            product_id: ID of the product.
        """
        await self._http.delete(
            f"/catalogs/{catalog_id}/categories/{category_id}/productassignments/{product_id}"
        )

    async def list_assignments(
        self,
        catalog_id: str,
        *,
        category_id: Optional[str] = None,
        buyer_id: Optional[str] = None,
        user_group_id: Optional[str] = None,
        level: Optional[str] = None,
        page: Optional[int] = None,
        page_size: Optional[int] = None,
    ) -> ListPage[CategoryAssignment]:
        """List category assignments

        Args:
            catalog_id: ID of the catalog.
            category_id: ID of the category.
            buyer_id: ID of the buyer.
            user_group_id: ID of the user group.
            level: Level of the category assignment. Possible values: Group, Company, BuyerGroup.
            page: Page of results to return. When paginating through many items (> page 30), we recommend the "Last ID" method, as outlined in the Advanced Querying documentation.
            page_size: Number of results to return per page.

        Returns:
            A paginated list of CategoryAssignment objects.
        """
        params = self._build_list_params(
            page=page,
            page_size=page_size,
        )
        if category_id is not None:
            params["categoryID"] = category_id
        if buyer_id is not None:
            params["buyerID"] = buyer_id
        if user_group_id is not None:
            params["userGroupID"] = user_group_id
        if level is not None:
            params["level"] = level
        resp = await self._http.get(f"/catalogs/{catalog_id}/categories/assignments", **params)
        return self._parse_list(resp.json(), CategoryAssignment)

    async def save_assignment(
        self,
        catalog_id: str,
        category_assignment: Union[CategoryAssignment, dict[str, Any]],
    ) -> None:
        """Create or update a category assignment

        Args:
            catalog_id: ID of the catalog.
            category_assignment: A ``CategoryAssignment`` model or dict. Required fields: CategoryID, BuyerID.
        """
        await self._http.post(
            f"/catalogs/{catalog_id}/categories/assignments",
            json=self._serialize(category_assignment),
        )

    async def list_bundle_assignments(
        self,
        catalog_id: str,
        *,
        category_id: Optional[str] = None,
        bundle_id: Optional[str] = None,
        page: Optional[int] = None,
        page_size: Optional[int] = None,
    ) -> ListPage[CategoryBundleAssignment]:
        """List category bundle assignments

        Args:
            catalog_id: ID of the catalog.
            category_id: ID of the category.
            bundle_id: ID of the bundle.
            page: Page of results to return. When paginating through many items (> page 30), we recommend the "Last ID" method, as outlined in the Advanced Querying documentation.
            page_size: Number of results to return per page.

        Returns:
            A paginated list of CategoryBundleAssignment objects.
        """
        params = self._build_list_params(
            page=page,
            page_size=page_size,
        )
        if category_id is not None:
            params["categoryID"] = category_id
        if bundle_id is not None:
            params["bundleID"] = bundle_id
        resp = await self._http.get(
            f"/catalogs/{catalog_id}/categories/bundleassignments", **params
        )
        return self._parse_list(resp.json(), CategoryBundleAssignment)

    async def save_bundle_assignment(
        self,
        catalog_id: str,
        category_bundle_assignment: Union[CategoryBundleAssignment, dict[str, Any]],
    ) -> None:
        """Create or update a category bundle assignment

        Args:
            catalog_id: ID of the catalog.
            category_bundle_assignment: A ``CategoryBundleAssignment`` model or dict. Required fields: CategoryID, BundleID.
        """
        await self._http.post(
            f"/catalogs/{catalog_id}/categories/bundleassignments",
            json=self._serialize(category_bundle_assignment),
        )

    async def list_product_assignments(
        self,
        catalog_id: str,
        *,
        category_id: Optional[str] = None,
        product_id: Optional[str] = None,
        page: Optional[int] = None,
        page_size: Optional[int] = None,
    ) -> ListPage[CategoryProductAssignment]:
        """List category product assignments

        Args:
            catalog_id: ID of the catalog.
            category_id: ID of the category.
            product_id: ID of the product.
            page: Page of results to return. When paginating through many items (> page 30), we recommend the "Last ID" method, as outlined in the Advanced Querying documentation.
            page_size: Number of results to return per page.

        Returns:
            A paginated list of CategoryProductAssignment objects.
        """
        params = self._build_list_params(
            page=page,
            page_size=page_size,
        )
        if category_id is not None:
            params["categoryID"] = category_id
        if product_id is not None:
            params["productID"] = product_id
        resp = await self._http.get(
            f"/catalogs/{catalog_id}/categories/productassignments", **params
        )
        return self._parse_list(resp.json(), CategoryProductAssignment)

    async def save_product_assignment(
        self,
        catalog_id: str,
        category_product_assignment: Union[CategoryProductAssignment, dict[str, Any]],
    ) -> None:
        """Create or update a category product assignment

        Args:
            catalog_id: ID of the catalog.
            category_product_assignment: A ``CategoryProductAssignment`` model or dict. Required fields: CategoryID, ProductID.
        """
        await self._http.post(
            f"/catalogs/{catalog_id}/categories/productassignments",
            json=self._serialize(category_product_assignment),
        )
