# GENERATED by tools/codegen — DO NOT EDIT
# Source: ordercloud-openapi-v3.json
"""OrderCloud CostCenters API resource."""

from __future__ import annotations
from typing import Any, Optional, Union

from ..models.assignments import CostCenterAssignment
from ..models.cost_center import CostCenter
from ..models.shared import ListPage
from .base import BaseResource

__all__ = ["CostCentersResource"]


class CostCentersResource(BaseResource):
    """Operations on OrderCloud CostCenters."""

    async def list(
        self,
        buyer_id: str,
        *,
        search: Optional[str] = None,
        search_on: Optional[str] = None,
        sort_by: Optional[str] = None,
        page: Optional[int] = None,
        page_size: Optional[int] = None,
        filters: Optional[dict[str, Any]] = None,
    ) -> ListPage[CostCenter]:
        """List cost centers

        Args:
            buyer_id: ID of the buyer.
            search: Word or phrase to search for.
            search_on: Comma-delimited list of fields to search on.
            sort_by: Comma-delimited list of fields to sort by.
            page: Page of results to return. When paginating through many items (> page 30), we recommend the "Last ID" method, as outlined in the Advanced Querying documentation.
            page_size: Number of results to return per page.
            filters: An object or dictionary representing key/value pairs to apply as filters. Valid keys are top-level properties of the returned model or 'xp.???'

        Returns:
            A paginated list of CostCenter objects.
        """
        params = self._build_list_params(
            search=search,
            search_on=search_on,
            sort_by=sort_by,
            page=page,
            page_size=page_size,
            filters=filters,
        )
        resp = await self._http.get(f"/buyers/{buyer_id}/costcenters", **params)
        return self._parse_list(resp.json(), CostCenter)

    async def create(
        self,
        buyer_id: str,
        cost_center: Union[CostCenter, dict[str, Any]],
    ) -> CostCenter:
        """Create a cost center

        Args:
            buyer_id: ID of the buyer.
            cost_center: A ``CostCenter`` model or dict. Required fields: Name.

        Returns:
            The CostCenter object.
        """
        resp = await self._http.post(
            f"/buyers/{buyer_id}/costcenters", json=self._serialize(cost_center)
        )
        return CostCenter(**resp.json())

    async def get(
        self,
        buyer_id: str,
        cost_center_id: str,
    ) -> CostCenter:
        """Retrieve a cost center

        Args:
            buyer_id: ID of the buyer.
            cost_center_id: ID of the cost center.

        Returns:
            The CostCenter object.
        """
        resp = await self._http.get(f"/buyers/{buyer_id}/costcenters/{cost_center_id}")
        return CostCenter(**resp.json())

    async def save(
        self,
        buyer_id: str,
        cost_center_id: str,
        cost_center: Union[CostCenter, dict[str, Any]],
    ) -> CostCenter:
        """Create or update a cost center

        Args:
            buyer_id: ID of the buyer.
            cost_center_id: ID of the cost center.
            cost_center: A ``CostCenter`` model or dict. Required fields: Name.

        Returns:
            The CostCenter object.
        """
        resp = await self._http.put(
            f"/buyers/{buyer_id}/costcenters/{cost_center_id}",
            json=self._serialize(cost_center),
        )
        return CostCenter(**resp.json())

    async def delete(
        self,
        buyer_id: str,
        cost_center_id: str,
    ) -> None:
        """Delete a cost center

        Args:
            buyer_id: ID of the buyer.
            cost_center_id: ID of the cost center.
        """
        await self._http.delete(f"/buyers/{buyer_id}/costcenters/{cost_center_id}")

    async def patch(
        self,
        buyer_id: str,
        cost_center_id: str,
        partial: dict[str, Any],
    ) -> CostCenter:
        """Partially update a cost center

        Args:
            buyer_id: ID of the buyer.
            cost_center_id: ID of the cost center.
            partial: A dict of fields to update.

        Returns:
            The CostCenter object.
        """
        resp = await self._http.patch(
            f"/buyers/{buyer_id}/costcenters/{cost_center_id}", json=partial
        )
        return CostCenter(**resp.json())

    async def delete_assignment(
        self,
        buyer_id: str,
        cost_center_id: str,
        *,
        user_id: Optional[str] = None,
        user_group_id: Optional[str] = None,
    ) -> None:
        """Delete a cost center assignment

        Args:
            buyer_id: ID of the buyer.
            cost_center_id: ID of the cost center.
            user_id: ID of the user.
            user_group_id: ID of the user group.
        """
        _params: dict[str, Any] = {}
        if user_id is not None:
            _params["userID"] = user_id
        if user_group_id is not None:
            _params["userGroupID"] = user_group_id
        await self._http.delete(
            f"/buyers/{buyer_id}/costcenters/{cost_center_id}/assignments", **_params
        )

    async def list_assignments(
        self,
        buyer_id: str,
        *,
        cost_center_id: Optional[str] = None,
        user_group_id: Optional[str] = None,
        level: Optional[str] = None,
        page: Optional[int] = None,
        page_size: Optional[int] = None,
    ) -> ListPage[CostCenterAssignment]:
        """List cost center assignments

        Args:
            buyer_id: ID of the buyer.
            cost_center_id: ID of the cost center.
            user_group_id: ID of the user group.
            level: Level of the cost center assignment. Possible values: Group, Company, BuyerGroup.
            page: Page of results to return. When paginating through many items (> page 30), we recommend the "Last ID" method, as outlined in the Advanced Querying documentation.
            page_size: Number of results to return per page.

        Returns:
            A paginated list of CostCenterAssignment objects.
        """
        params = self._build_list_params(
            page=page,
            page_size=page_size,
        )
        if cost_center_id is not None:
            params["costCenterID"] = cost_center_id
        if user_group_id is not None:
            params["userGroupID"] = user_group_id
        if level is not None:
            params["level"] = level
        resp = await self._http.get(f"/buyers/{buyer_id}/costcenters/assignments", **params)
        return self._parse_list(resp.json(), CostCenterAssignment)

    async def save_assignment(
        self,
        buyer_id: str,
        cost_center_assignment: Union[CostCenterAssignment, dict[str, Any]],
    ) -> None:
        """Create or update a cost center assignment

        Args:
            buyer_id: ID of the buyer.
            cost_center_assignment: A ``CostCenterAssignment`` model or dict. Required fields: CostCenterID.
        """
        await self._http.post(
            f"/buyers/{buyer_id}/costcenters/assignments",
            json=self._serialize(cost_center_assignment),
        )
