# GENERATED by tools/codegen — DO NOT EDIT
# Source: ordercloud-openapi-v3.json
"""OrderCloud CreditCards API resource."""

from __future__ import annotations
from typing import Any, Optional, Union

from ..models.assignments import CreditCardAssignment
from ..models.credit_card import CreditCard
from ..models.misc import PartyType
from ..models.shared import ListPage
from .base import BaseResource

__all__ = ["CreditCardsResource"]


class CreditCardsResource(BaseResource):
    """Operations on OrderCloud CreditCards."""

    async def list(
        self,
        buyer_id: str,
        *,
        search: Optional[str] = None,
        search_on: Optional[str] = None,
        sort_by: Optional[str] = None,
        page: Optional[int] = None,
        page_size: Optional[int] = None,
        filters: Optional[dict[str, Any]] = None,
    ) -> ListPage[CreditCard]:
        """List credit cards

        Args:
            buyer_id: ID of the buyer.
            search: Word or phrase to search for.
            search_on: Comma-delimited list of fields to search on.
            sort_by: Comma-delimited list of fields to sort by.
            page: Page of results to return. When paginating through many items (> page 30), we recommend the "Last ID" method, as outlined in the Advanced Querying documentation.
            page_size: Number of results to return per page.
            filters: An object or dictionary representing key/value pairs to apply as filters. Valid keys are top-level properties of the returned model or 'xp.???'

        Returns:
            A paginated list of CreditCard objects.
        """
        params = self._build_list_params(
            search=search,
            search_on=search_on,
            sort_by=sort_by,
            page=page,
            page_size=page_size,
            filters=filters,
        )
        resp = await self._http.get(f"/buyers/{buyer_id}/creditcards", **params)
        return self._parse_list(resp.json(), CreditCard)

    async def create(
        self,
        buyer_id: str,
        credit_card: Union[CreditCard, dict[str, Any]],
    ) -> CreditCard:
        """Create a credit card

        Args:
            buyer_id: ID of the buyer.
            credit_card: A ``CreditCard`` model or dict.

        Returns:
            The CreditCard object.
        """
        resp = await self._http.post(
            f"/buyers/{buyer_id}/creditcards", json=self._serialize(credit_card)
        )
        return CreditCard(**resp.json())

    async def get(
        self,
        buyer_id: str,
        credit_card_id: str,
    ) -> CreditCard:
        """Retrieve a credit card

        Args:
            buyer_id: ID of the buyer.
            credit_card_id: ID of the credit card.

        Returns:
            The CreditCard object.
        """
        resp = await self._http.get(f"/buyers/{buyer_id}/creditcards/{credit_card_id}")
        return CreditCard(**resp.json())

    async def save(
        self,
        buyer_id: str,
        credit_card_id: str,
        credit_card: Union[CreditCard, dict[str, Any]],
    ) -> CreditCard:
        """Create or update a credit card

        Args:
            buyer_id: ID of the buyer.
            credit_card_id: ID of the credit card.
            credit_card: A ``CreditCard`` model or dict.

        Returns:
            The CreditCard object.
        """
        resp = await self._http.put(
            f"/buyers/{buyer_id}/creditcards/{credit_card_id}",
            json=self._serialize(credit_card),
        )
        return CreditCard(**resp.json())

    async def delete(
        self,
        buyer_id: str,
        credit_card_id: str,
    ) -> None:
        """Delete a credit card

        Args:
            buyer_id: ID of the buyer.
            credit_card_id: ID of the credit card.
        """
        await self._http.delete(f"/buyers/{buyer_id}/creditcards/{credit_card_id}")

    async def patch(
        self,
        buyer_id: str,
        credit_card_id: str,
        partial: dict[str, Any],
    ) -> CreditCard:
        """Partially update a credit card

        Args:
            buyer_id: ID of the buyer.
            credit_card_id: ID of the credit card.
            partial: A dict of fields to update.

        Returns:
            The CreditCard object.
        """
        resp = await self._http.patch(
            f"/buyers/{buyer_id}/creditcards/{credit_card_id}", json=partial
        )
        return CreditCard(**resp.json())

    async def delete_assignment(
        self,
        buyer_id: str,
        credit_card_id: str,
        *,
        user_id: Optional[str] = None,
        user_group_id: Optional[str] = None,
    ) -> None:
        """Delete a credit card assignment

        Args:
            buyer_id: ID of the buyer.
            credit_card_id: ID of the credit card.
            user_id: ID of the user.
            user_group_id: ID of the user group.
        """
        _params: dict[str, Any] = {}
        if user_id is not None:
            _params["userID"] = user_id
        if user_group_id is not None:
            _params["userGroupID"] = user_group_id
        await self._http.delete(
            f"/buyers/{buyer_id}/creditcards/{credit_card_id}/assignments", **_params
        )

    async def list_assignments(
        self,
        buyer_id: str,
        *,
        credit_card_id: Optional[str] = None,
        user_id: Optional[str] = None,
        user_group_id: Optional[str] = None,
        level: Optional[PartyType] = None,
        page: Optional[int] = None,
        page_size: Optional[int] = None,
    ) -> ListPage[CreditCardAssignment]:
        """List credit card assignments

        Args:
            buyer_id: ID of the buyer.
            credit_card_id: ID of the credit card.
            user_id: ID of the user.
            user_group_id: ID of the user group.
            level: Level of the credit card assignment. Possible values: User, Group, Company, BuyerGroup.
            page: Page of results to return. When paginating through many items (> page 30), we recommend the "Last ID" method, as outlined in the Advanced Querying documentation.
            page_size: Number of results to return per page.

        Returns:
            A paginated list of CreditCardAssignment objects.
        """
        params = self._build_list_params(
            page=page,
            page_size=page_size,
        )
        if credit_card_id is not None:
            params["creditCardID"] = credit_card_id
        if user_id is not None:
            params["userID"] = user_id
        if user_group_id is not None:
            params["userGroupID"] = user_group_id
        if level is not None:
            params["level"] = level
        resp = await self._http.get(f"/buyers/{buyer_id}/creditcards/assignments", **params)
        return self._parse_list(resp.json(), CreditCardAssignment)

    async def save_assignment(
        self,
        buyer_id: str,
        credit_card_assignment: Union[CreditCardAssignment, dict[str, Any]],
    ) -> None:
        """Create or update a credit card assignment

        Args:
            buyer_id: ID of the buyer.
            credit_card_assignment: A ``CreditCardAssignment`` model or dict. Required fields: CreditCardID.
        """
        await self._http.post(
            f"/buyers/{buyer_id}/creditcards/assignments",
            json=self._serialize(credit_card_assignment),
        )
