# GENERATED by tools/codegen — DO NOT EDIT
# Source: ordercloud-openapi-v3.json
"""OrderCloud EntitySyncs API resource."""

from __future__ import annotations
from typing import Any, Union

from ..models.sync import (
    EntitySyncConfig,
    SyncAdminUser,
    SyncBuyer,
    SyncBuyerUser,
    SyncBuyerUserGroup,
    SyncCategory,
    SyncInventoryRecord,
    SyncSupplier,
    SyncSupplierUser,
)
from .base import BaseResource

__all__ = ["EntitySyncsResource"]


class EntitySyncsResource(BaseResource):
    """Operations on OrderCloud EntitySyncs."""

    async def get_admin_users(
        self,
    ) -> EntitySyncConfig:
        """Retrieve the entity sync delivery configuration for admin users

        Returns:
            The EntitySyncConfig object.
        """
        resp = await self._http.get("/integrations/entitysync/adminusers")
        return EntitySyncConfig(**resp.json())

    async def save_admin_users(
        self,
        entity_sync_config: Union[EntitySyncConfig, dict[str, Any]],
    ) -> EntitySyncConfig:
        """Create or update the entity sync delivery configuration for admin users

        Args:
            entity_sync_config: A ``EntitySyncConfig`` model or dict. Required fields: DeliveryConfigID, SyncEntityChanged, SyncEntityDeleted.

        Returns:
            The EntitySyncConfig object.
        """
        resp = await self._http.put(
            "/integrations/entitysync/adminusers",
            json=self._serialize(entity_sync_config),
        )
        return EntitySyncConfig(**resp.json())

    async def delete_admin_users(
        self,
    ) -> None:
        """Delete the entity sync delivery configuration for admin users"""
        await self._http.delete("/integrations/entitysync/adminusers")

    async def patch_admin_users(
        self,
        partial: dict[str, Any],
    ) -> EntitySyncConfig:
        """Partially update the entity sync delivery configuration for admin users

        Args:
            partial: A dict of fields to update.

        Returns:
            The EntitySyncConfig object.
        """
        resp = await self._http.patch("/integrations/entitysync/adminusers", json=partial)
        return EntitySyncConfig(**resp.json())

    async def sync_admin_user(
        self,
        sync_admin_user: Union[SyncAdminUser, dict[str, Any]],
    ) -> None:
        """Sync an admin user

        Args:
            sync_admin_user: A ``SyncAdminUser`` model or dict. Required fields: UserID.
        """
        await self._http.post(
            "/integrations/entitysync/adminusers/sync", json=self._serialize(sync_admin_user)
        )

    async def get_buyers(
        self,
    ) -> EntitySyncConfig:
        """Retrieve the entity sync delivery configuration for buyers

        Returns:
            The EntitySyncConfig object.
        """
        resp = await self._http.get("/integrations/entitysync/buyers")
        return EntitySyncConfig(**resp.json())

    async def save_buyers(
        self,
        entity_sync_config: Union[EntitySyncConfig, dict[str, Any]],
    ) -> EntitySyncConfig:
        """Create or update the entity sync delivery configuration for buyers

        Args:
            entity_sync_config: A ``EntitySyncConfig`` model or dict. Required fields: DeliveryConfigID, SyncEntityChanged, SyncEntityDeleted.

        Returns:
            The EntitySyncConfig object.
        """
        resp = await self._http.put(
            "/integrations/entitysync/buyers",
            json=self._serialize(entity_sync_config),
        )
        return EntitySyncConfig(**resp.json())

    async def delete_buyers(
        self,
    ) -> None:
        """Delete the entity sync delivery configuration for buyers"""
        await self._http.delete("/integrations/entitysync/buyers")

    async def patch_buyers(
        self,
        partial: dict[str, Any],
    ) -> EntitySyncConfig:
        """Partially update the entity sync delivery configuration for buyers

        Args:
            partial: A dict of fields to update.

        Returns:
            The EntitySyncConfig object.
        """
        resp = await self._http.patch("/integrations/entitysync/buyers", json=partial)
        return EntitySyncConfig(**resp.json())

    async def sync_buyer(
        self,
        sync_buyer: Union[SyncBuyer, dict[str, Any]],
    ) -> None:
        """Sync a buyer

        Args:
            sync_buyer: A ``SyncBuyer`` model or dict. Required fields: BuyerID.
        """
        await self._http.post(
            "/integrations/entitysync/buyers/sync", json=self._serialize(sync_buyer)
        )

    async def get_buyer_user_groups(
        self,
    ) -> EntitySyncConfig:
        """Retrieve the entity sync delivery configuration for buyer user groups

        Returns:
            The EntitySyncConfig object.
        """
        resp = await self._http.get("/integrations/entitysync/buyers/usergroups")
        return EntitySyncConfig(**resp.json())

    async def save_user_groups(
        self,
        entity_sync_config: Union[EntitySyncConfig, dict[str, Any]],
    ) -> EntitySyncConfig:
        """Create or update the entity sync delivery configuration for buyer user groups

        Args:
            entity_sync_config: A ``EntitySyncConfig`` model or dict. Required fields: DeliveryConfigID, SyncEntityChanged, SyncEntityDeleted.

        Returns:
            The EntitySyncConfig object.
        """
        resp = await self._http.put(
            "/integrations/entitysync/buyers/usergroups",
            json=self._serialize(entity_sync_config),
        )
        return EntitySyncConfig(**resp.json())

    async def delete_user_groups(
        self,
    ) -> None:
        """Delete the entity sync delivery configuration for buyer user groups"""
        await self._http.delete("/integrations/entitysync/buyers/usergroups")

    async def patch_buyer_user_groups(
        self,
        partial: dict[str, Any],
    ) -> EntitySyncConfig:
        """Partially update the entity sync delivery configuration for buyer user groups

        Args:
            partial: A dict of fields to update.

        Returns:
            The EntitySyncConfig object.
        """
        resp = await self._http.patch("/integrations/entitysync/buyers/usergroups", json=partial)
        return EntitySyncConfig(**resp.json())

    async def sync_buyer_user_group(
        self,
        sync_buyer_user_group: Union[SyncBuyerUserGroup, dict[str, Any]],
    ) -> None:
        """Sync a buyer user group

        Args:
            sync_buyer_user_group: A ``SyncBuyerUserGroup`` model or dict. Required fields: BuyerID, UserGroupID.
        """
        await self._http.post(
            "/integrations/entitysync/buyers/usergroups/sync",
            json=self._serialize(sync_buyer_user_group),
        )

    async def get_buyer_users(
        self,
    ) -> EntitySyncConfig:
        """Retrieve the entity sync delivery configuration for buyer users

        Returns:
            The EntitySyncConfig object.
        """
        resp = await self._http.get("/integrations/entitysync/buyers/users")
        return EntitySyncConfig(**resp.json())

    async def save_buyer_users(
        self,
        entity_sync_config: Union[EntitySyncConfig, dict[str, Any]],
    ) -> EntitySyncConfig:
        """Create or update the entity sync delivery configuration for buyer users

        Args:
            entity_sync_config: A ``EntitySyncConfig`` model or dict. Required fields: DeliveryConfigID, SyncEntityChanged, SyncEntityDeleted.

        Returns:
            The EntitySyncConfig object.
        """
        resp = await self._http.put(
            "/integrations/entitysync/buyers/users",
            json=self._serialize(entity_sync_config),
        )
        return EntitySyncConfig(**resp.json())

    async def delete_buyer_users(
        self,
    ) -> None:
        """Delete the entity sync delivery configuration for buyer users"""
        await self._http.delete("/integrations/entitysync/buyers/users")

    async def patch_buyer_users(
        self,
        partial: dict[str, Any],
    ) -> EntitySyncConfig:
        """Partially update the entity sync delivery configuration for buyer users

        Args:
            partial: A dict of fields to update.

        Returns:
            The EntitySyncConfig object.
        """
        resp = await self._http.patch("/integrations/entitysync/buyers/users", json=partial)
        return EntitySyncConfig(**resp.json())

    async def sync_buyer_user(
        self,
        sync_buyer_user: Union[SyncBuyerUser, dict[str, Any]],
    ) -> None:
        """Sync a buyer user

        Args:
            sync_buyer_user: A ``SyncBuyerUser`` model or dict. Required fields: BuyerID, UserID.
        """
        await self._http.post(
            "/integrations/entitysync/buyers/users/sync", json=self._serialize(sync_buyer_user)
        )

    async def get_categories(
        self,
    ) -> EntitySyncConfig:
        """Retrieve the entity sync delivery configuration for categories

        Returns:
            The EntitySyncConfig object.
        """
        resp = await self._http.get("/integrations/entitysync/categories")
        return EntitySyncConfig(**resp.json())

    async def save_categories(
        self,
        entity_sync_config: Union[EntitySyncConfig, dict[str, Any]],
    ) -> EntitySyncConfig:
        """Create or update the entity sync delivery configuration for categories

        Args:
            entity_sync_config: A ``EntitySyncConfig`` model or dict. Required fields: DeliveryConfigID, SyncEntityChanged, SyncEntityDeleted.

        Returns:
            The EntitySyncConfig object.
        """
        resp = await self._http.put(
            "/integrations/entitysync/categories",
            json=self._serialize(entity_sync_config),
        )
        return EntitySyncConfig(**resp.json())

    async def delete_categories(
        self,
    ) -> None:
        """Delete the entity sync delivery configuration for categories"""
        await self._http.delete("/integrations/entitysync/categories")

    async def patch_categories(
        self,
        partial: dict[str, Any],
    ) -> EntitySyncConfig:
        """Partially update the entity sync delivery configuration for categories

        Args:
            partial: A dict of fields to update.

        Returns:
            The EntitySyncConfig object.
        """
        resp = await self._http.patch("/integrations/entitysync/categories", json=partial)
        return EntitySyncConfig(**resp.json())

    async def sync_category(
        self,
        sync_category: Union[SyncCategory, dict[str, Any]],
    ) -> None:
        """Sync a category

        Args:
            sync_category: A ``SyncCategory`` model or dict. Required fields: CatalogID, CategoryID.
        """
        await self._http.post(
            "/integrations/entitysync/categories/sync", json=self._serialize(sync_category)
        )

    async def get_inventory_records(
        self,
    ) -> EntitySyncConfig:
        """Retrieve the entity sync delivery configuration for inventory records

        Returns:
            The EntitySyncConfig object.
        """
        resp = await self._http.get("/integrations/entitysync/products/inventoryrecords")
        return EntitySyncConfig(**resp.json())

    async def save_inventory_records(
        self,
        entity_sync_config: Union[EntitySyncConfig, dict[str, Any]],
    ) -> EntitySyncConfig:
        """Create or update the entity sync delivery configuration for inventory records

        Args:
            entity_sync_config: A ``EntitySyncConfig`` model or dict. Required fields: DeliveryConfigID, SyncEntityChanged, SyncEntityDeleted.

        Returns:
            The EntitySyncConfig object.
        """
        resp = await self._http.put(
            "/integrations/entitysync/products/inventoryrecords",
            json=self._serialize(entity_sync_config),
        )
        return EntitySyncConfig(**resp.json())

    async def delete_inventory_records(
        self,
    ) -> None:
        """Delete the entity sync delivery configuration for inventory records"""
        await self._http.delete("/integrations/entitysync/products/inventoryrecords")

    async def patch_inventory_records(
        self,
        partial: dict[str, Any],
    ) -> EntitySyncConfig:
        """Partially update the entity sync delivery configuration for inventory records

        Args:
            partial: A dict of fields to update.

        Returns:
            The EntitySyncConfig object.
        """
        resp = await self._http.patch(
            "/integrations/entitysync/products/inventoryrecords", json=partial
        )
        return EntitySyncConfig(**resp.json())

    async def sync_inventory_record(
        self,
        sync_inventory_record: Union[SyncInventoryRecord, dict[str, Any]],
    ) -> None:
        """Sync an inventory record

        Args:
            sync_inventory_record: A ``SyncInventoryRecord`` model or dict. Required fields: ProductID, InventoryRecordID.
        """
        await self._http.post(
            "/integrations/entitysync/products/inventoryrecords/sync",
            json=self._serialize(sync_inventory_record),
        )

    async def sync_supplier(
        self,
        sync_supplier: Union[SyncSupplier, dict[str, Any]],
    ) -> None:
        """Sync a supplier

        Args:
            sync_supplier: A ``SyncSupplier`` model or dict. Required fields: SupplierID.
        """
        await self._http.post(
            "/integrations/entitysync/supplier/sync", json=self._serialize(sync_supplier)
        )

    async def get_suppliers(
        self,
    ) -> EntitySyncConfig:
        """Retrieve the entity sync delivery configuration for suppliers

        Returns:
            The EntitySyncConfig object.
        """
        resp = await self._http.get("/integrations/entitysync/suppliers")
        return EntitySyncConfig(**resp.json())

    async def save_suppliers(
        self,
        entity_sync_config: Union[EntitySyncConfig, dict[str, Any]],
    ) -> EntitySyncConfig:
        """Create or update the entity sync delivery configuration for suppliers

        Args:
            entity_sync_config: A ``EntitySyncConfig`` model or dict. Required fields: DeliveryConfigID, SyncEntityChanged, SyncEntityDeleted.

        Returns:
            The EntitySyncConfig object.
        """
        resp = await self._http.put(
            "/integrations/entitysync/suppliers",
            json=self._serialize(entity_sync_config),
        )
        return EntitySyncConfig(**resp.json())

    async def delete_suppliers(
        self,
    ) -> None:
        """Delete the entity sync delivery configuration for suppliers"""
        await self._http.delete("/integrations/entitysync/suppliers")

    async def patch_suppliers(
        self,
        partial: dict[str, Any],
    ) -> EntitySyncConfig:
        """Partially update the entity sync delivery configuration for suppliers

        Args:
            partial: A dict of fields to update.

        Returns:
            The EntitySyncConfig object.
        """
        resp = await self._http.patch("/integrations/entitysync/suppliers", json=partial)
        return EntitySyncConfig(**resp.json())

    async def get_supplier_users(
        self,
    ) -> EntitySyncConfig:
        """Retrieve the entity sync delivery configuration for supplier users

        Returns:
            The EntitySyncConfig object.
        """
        resp = await self._http.get("/integrations/entitysync/suppliers/users")
        return EntitySyncConfig(**resp.json())

    async def save_supplier_users(
        self,
        entity_sync_config: Union[EntitySyncConfig, dict[str, Any]],
    ) -> EntitySyncConfig:
        """Create or update the entity sync delivery configuration for supplier users

        Args:
            entity_sync_config: A ``EntitySyncConfig`` model or dict. Required fields: DeliveryConfigID, SyncEntityChanged, SyncEntityDeleted.

        Returns:
            The EntitySyncConfig object.
        """
        resp = await self._http.put(
            "/integrations/entitysync/suppliers/users",
            json=self._serialize(entity_sync_config),
        )
        return EntitySyncConfig(**resp.json())

    async def delete_supplier_users(
        self,
    ) -> None:
        """Delete the entity sync delivery configuration for supplier users"""
        await self._http.delete("/integrations/entitysync/suppliers/users")

    async def patch_supplier_users(
        self,
        partial: dict[str, Any],
    ) -> EntitySyncConfig:
        """Partially update the entity sync delivery configuration for supplier users

        Args:
            partial: A dict of fields to update.

        Returns:
            The EntitySyncConfig object.
        """
        resp = await self._http.patch("/integrations/entitysync/suppliers/users", json=partial)
        return EntitySyncConfig(**resp.json())

    async def sync_supplier_user(
        self,
        sync_supplier_user: Union[SyncSupplierUser, dict[str, Any]],
    ) -> None:
        """Sync a supplier user

        Args:
            sync_supplier_user: A ``SyncSupplierUser`` model or dict. Required fields: SupplierID, UserID.
        """
        await self._http.post(
            "/integrations/entitysync/suppliers/users/sync",
            json=self._serialize(sync_supplier_user),
        )
