# GENERATED by tools/codegen — DO NOT EDIT
# Source: ordercloud-openapi-v3.json
"""OrderCloud ErrorConfigs API resource."""

from __future__ import annotations
from typing import Any, Union

from ..models.delivery import ErrorConfig
from .base import BaseResource

__all__ = ["ErrorConfigsResource"]


class ErrorConfigsResource(BaseResource):
    """Operations on OrderCloud ErrorConfigs."""

    async def get(
        self,
    ) -> ErrorConfig:
        """Retrieve an error config

        Returns:
            The ErrorConfig object.
        """
        resp = await self._http.get("/integrations/ErrorConfig")
        return ErrorConfig(**resp.json())

    async def save(
        self,
        error_config: Union[ErrorConfig, dict[str, Any]],
    ) -> ErrorConfig:
        """Create or update an error config

        Args:
            error_config: A ``ErrorConfig`` model or dict. Required fields: DeliveryConfigID.

        Returns:
            The ErrorConfig object.
        """
        resp = await self._http.put(
            "/integrations/ErrorConfig",
            json=self._serialize(error_config),
        )
        return ErrorConfig(**resp.json())

    async def delete(
        self,
    ) -> None:
        """Delete an error config"""
        await self._http.delete("/integrations/ErrorConfig")

    async def patch(
        self,
        partial: dict[str, Any],
    ) -> ErrorConfig:
        """Partially update an error config

        Args:
            partial: A dict of fields to update.

        Returns:
            The ErrorConfig object.
        """
        resp = await self._http.patch("/integrations/ErrorConfig", json=partial)
        return ErrorConfig(**resp.json())

    async def validate(
        self,
    ) -> None:
        """Validates an error config"""
        await self._http.post("/integrations/ErrorConfig/validate")
