# GENERATED by tools/codegen — DO NOT EDIT
# Source: ordercloud-openapi-v3.json
"""OrderCloud GroupOrders API resource."""

from __future__ import annotations
from ..models.auth_models import AccessToken
from .base import BaseResource

__all__ = ["GroupOrdersResource"]


class GroupOrdersResource(BaseResource):
    """Operations on OrderCloud GroupOrders."""

    async def get_token(
        self,
        invitation_id: str,
    ) -> AccessToken:
        """Retrieve a group order token

        Args:
            invitation_id: ID of the invitation.

        Returns:
            The AccessToken object.
        """
        resp = await self._http.post(f"/grouporders/{invitation_id}/token")
        return AccessToken(**resp.json())
