# GENERATED by tools/codegen — DO NOT EDIT
# Source: ordercloud-openapi-v3.json
"""OrderCloud Incrementors API resource."""

from __future__ import annotations
from typing import Any, Optional, Union

from ..models.misc import Incrementor
from ..models.shared import ListPage
from .base import BaseResource

__all__ = ["IncrementorsResource"]


class IncrementorsResource(BaseResource):
    """Operations on OrderCloud Incrementors."""

    async def list(
        self,
        *,
        search: Optional[str] = None,
        search_on: Optional[str] = None,
        sort_by: Optional[str] = None,
        page: Optional[int] = None,
        page_size: Optional[int] = None,
        filters: Optional[dict[str, Any]] = None,
    ) -> ListPage[Incrementor]:
        """List incrementors

        Args:
            search: Word or phrase to search for.
            search_on: Comma-delimited list of fields to search on.
            sort_by: Comma-delimited list of fields to sort by.
            page: Page of results to return. When paginating through many items (> page 30), we recommend the "Last ID" method, as outlined in the Advanced Querying documentation.
            page_size: Number of results to return per page.
            filters: An object or dictionary representing key/value pairs to apply as filters. Valid keys are top-level properties of the returned model or 'xp.???'

        Returns:
            A paginated list of Incrementor objects.
        """
        params = self._build_list_params(
            search=search,
            search_on=search_on,
            sort_by=sort_by,
            page=page,
            page_size=page_size,
            filters=filters,
        )
        resp = await self._http.get("/incrementors", **params)
        return self._parse_list(resp.json(), Incrementor)

    async def create(
        self,
        incrementor: Union[Incrementor, dict[str, Any]],
    ) -> Incrementor:
        """Create an incrementor

        Args:
            incrementor: A ``Incrementor`` model or dict. Required fields: LastNumber, LeftPaddingCount.

        Returns:
            The Incrementor object.
        """
        resp = await self._http.post("/incrementors", json=self._serialize(incrementor))
        return Incrementor(**resp.json())

    async def get(
        self,
        incrementor_id: str,
    ) -> Incrementor:
        """Retrieve an incrementor

        Args:
            incrementor_id: ID of the incrementor.

        Returns:
            The Incrementor object.
        """
        resp = await self._http.get(f"/incrementors/{incrementor_id}")
        return Incrementor(**resp.json())

    async def save(
        self,
        incrementor_id: str,
        incrementor: Union[Incrementor, dict[str, Any]],
    ) -> Incrementor:
        """Create or update an incrementor

        Args:
            incrementor_id: ID of the incrementor.
            incrementor: A ``Incrementor`` model or dict. Required fields: LastNumber, LeftPaddingCount.

        Returns:
            The Incrementor object.
        """
        resp = await self._http.put(
            f"/incrementors/{incrementor_id}",
            json=self._serialize(incrementor),
        )
        return Incrementor(**resp.json())

    async def delete(
        self,
        incrementor_id: str,
    ) -> None:
        """Delete an incrementor

        Args:
            incrementor_id: ID of the incrementor.
        """
        await self._http.delete(f"/incrementors/{incrementor_id}")

    async def patch(
        self,
        incrementor_id: str,
        partial: dict[str, Any],
    ) -> Incrementor:
        """Partially update an incrementor

        Args:
            incrementor_id: ID of the incrementor.
            partial: A dict of fields to update.

        Returns:
            The Incrementor object.
        """
        resp = await self._http.patch(f"/incrementors/{incrementor_id}", json=partial)
        return Incrementor(**resp.json())
