# GENERATED by tools/codegen — DO NOT EDIT
# Source: ordercloud-openapi-v3.json
"""OrderCloud InventoryRecords API resource."""

from __future__ import annotations
from typing import Any, Optional, Union

from ..models.assignments import InventoryRecordAssignment
from ..models.inventory_record import InventoryRecord
from ..models.shared import ListPage
from .base import BaseResource

__all__ = ["InventoryRecordsResource"]


class InventoryRecordsResource(BaseResource):
    """Operations on OrderCloud InventoryRecords."""

    async def list(
        self,
        product_id: str,
        *,
        search: Optional[str] = None,
        search_on: Optional[str] = None,
        sort_by: Optional[str] = None,
        page: Optional[int] = None,
        page_size: Optional[int] = None,
        filters: Optional[dict[str, Any]] = None,
        include_address: Optional[bool] = None,
    ) -> ListPage[InventoryRecord]:
        """List inventory records

        Args:
            product_id: ID of the product.
            search: Word or phrase to search for.
            search_on: Comma-delimited list of fields to search on.
            sort_by: Comma-delimited list of fields to sort by.
            page: Page of results to return. When paginating through many items (> page 30), we recommend the "Last ID" method, as outlined in the Advanced Querying documentation.
            page_size: Number of results to return per page.
            filters: An object or dictionary representing key/value pairs to apply as filters. Valid keys are top-level properties of the returned model or 'xp.???'
            include_address: Include address of the inventory record.

        Returns:
            A paginated list of InventoryRecord objects.
        """
        params = self._build_list_params(
            search=search,
            search_on=search_on,
            sort_by=sort_by,
            page=page,
            page_size=page_size,
            filters=filters,
        )
        if include_address is not None:
            params["includeAddress"] = include_address
        resp = await self._http.get(f"/products/{product_id}/inventoryrecords", **params)
        return self._parse_list(resp.json(), InventoryRecord)

    async def create(
        self,
        product_id: str,
        inventory_record: Union[InventoryRecord, dict[str, Any]],
    ) -> InventoryRecord:
        """Create an inventory record

        Args:
            product_id: ID of the product.
            inventory_record: A ``InventoryRecord`` model or dict. Required fields: AddressID.

        Returns:
            The InventoryRecord object.
        """
        resp = await self._http.post(
            f"/products/{product_id}/inventoryrecords", json=self._serialize(inventory_record)
        )
        return InventoryRecord(**resp.json())

    async def get(
        self,
        product_id: str,
        inventory_record_id: str,
    ) -> InventoryRecord:
        """Retrieve an inventory record

        Args:
            product_id: ID of the product.
            inventory_record_id: ID of the inventory record.

        Returns:
            The InventoryRecord object.
        """
        resp = await self._http.get(
            f"/products/{product_id}/inventoryrecords/{inventory_record_id}"
        )
        return InventoryRecord(**resp.json())

    async def save(
        self,
        product_id: str,
        inventory_record_id: str,
        inventory_record: Union[InventoryRecord, dict[str, Any]],
    ) -> InventoryRecord:
        """Create or update an inventory record

        Args:
            product_id: ID of the product.
            inventory_record_id: ID of the inventory record.
            inventory_record: A ``InventoryRecord`` model or dict. Required fields: AddressID.

        Returns:
            The InventoryRecord object.
        """
        resp = await self._http.put(
            f"/products/{product_id}/inventoryrecords/{inventory_record_id}",
            json=self._serialize(inventory_record),
        )
        return InventoryRecord(**resp.json())

    async def delete(
        self,
        product_id: str,
        inventory_record_id: str,
    ) -> None:
        """Delete an inventory record

        Args:
            product_id: ID of the product.
            inventory_record_id: ID of the inventory record.
        """
        await self._http.delete(f"/products/{product_id}/inventoryrecords/{inventory_record_id}")

    async def patch(
        self,
        product_id: str,
        inventory_record_id: str,
        partial: dict[str, Any],
    ) -> InventoryRecord:
        """Partially update an inventory record

        Args:
            product_id: ID of the product.
            inventory_record_id: ID of the inventory record.
            partial: A dict of fields to update.

        Returns:
            The InventoryRecord object.
        """
        resp = await self._http.patch(
            f"/products/{product_id}/inventoryrecords/{inventory_record_id}", json=partial
        )
        return InventoryRecord(**resp.json())

    async def delete_assignment(
        self,
        product_id: str,
        inventory_record_id: str,
        *,
        buyer_id: Optional[str] = None,
        user_id: Optional[str] = None,
        user_group_id: Optional[str] = None,
    ) -> None:
        """Delete an inventory record assignment

        Args:
            product_id: ID of the product.
            inventory_record_id: ID of the inventory record.
            buyer_id: ID of the buyer.
            user_id: ID of the user.
            user_group_id: ID of the user group.
        """
        await self._http.delete(
            f"/products/{product_id}/inventoryrecords/{inventory_record_id}/assignments"
        )

    async def list_assignments(
        self,
        product_id: str,
        *,
        buyer_id: Optional[str] = None,
        inventory_record_id: Optional[str] = None,
        user_group_id: Optional[str] = None,
        level: Optional[str] = None,
        page: Optional[int] = None,
        page_size: Optional[int] = None,
    ) -> ListPage[InventoryRecordAssignment]:
        """List inventory record assignments

        Args:
            product_id: ID of the product.
            buyer_id: ID of the buyer.
            inventory_record_id: ID of the inventory record.
            user_group_id: ID of the user group.
            level: Level of the inventory record assignment. Possible values: Group, Company, BuyerGroup.
            page: Page of results to return. When paginating through many items (> page 30), we recommend the "Last ID" method, as outlined in the Advanced Querying documentation.
            page_size: Number of results to return per page.

        Returns:
            A paginated list of InventoryRecordAssignment objects.
        """
        params = self._build_list_params(
            page=page,
            page_size=page_size,
        )
        if buyer_id is not None:
            params["buyerID"] = buyer_id
        if inventory_record_id is not None:
            params["inventoryRecordID"] = inventory_record_id
        if user_group_id is not None:
            params["userGroupID"] = user_group_id
        if level is not None:
            params["level"] = level
        resp = await self._http.get(
            f"/products/{product_id}/inventoryrecords/assignments", **params
        )
        return self._parse_list(resp.json(), InventoryRecordAssignment)

    async def save_assignment(
        self,
        product_id: str,
        inventory_record_assignment: Union[InventoryRecordAssignment, dict[str, Any]],
    ) -> None:
        """Create or update an inventory record assignment

        Args:
            product_id: ID of the product.
            inventory_record_assignment: A ``InventoryRecordAssignment`` model or dict. Required fields: InventoryRecordID, BuyerID.
        """
        await self._http.post(
            f"/products/{product_id}/inventoryrecords/assignments",
            json=self._serialize(inventory_record_assignment),
        )

    async def list_variant(
        self,
        product_id: str,
        variant_id: str,
        *,
        search: Optional[str] = None,
        search_on: Optional[str] = None,
        sort_by: Optional[str] = None,
        page: Optional[int] = None,
        page_size: Optional[int] = None,
        filters: Optional[dict[str, Any]] = None,
        include_address: Optional[bool] = None,
    ) -> ListPage[InventoryRecord]:
        """Get a list of variant inventory records

        Args:
            product_id: ID of the product.
            variant_id: ID of the variant.
            search: Word or phrase to search for.
            search_on: Comma-delimited list of fields to search on.
            sort_by: Comma-delimited list of fields to sort by.
            page: Page of results to return. When paginating through many items (> page 30), we recommend the "Last ID" method, as outlined in the Advanced Querying documentation.
            page_size: Number of results to return per page.
            filters: An object or dictionary representing key/value pairs to apply as filters. Valid keys are top-level properties of the returned model or 'xp.???'
            include_address: Include address of the inventory record.

        Returns:
            A paginated list of InventoryRecord objects.
        """
        params = self._build_list_params(
            search=search,
            search_on=search_on,
            sort_by=sort_by,
            page=page,
            page_size=page_size,
            filters=filters,
        )
        if include_address is not None:
            params["includeAddress"] = include_address
        resp = await self._http.get(
            f"/products/{product_id}/variants/{variant_id}/inventoryrecords", **params
        )
        return self._parse_list(resp.json(), InventoryRecord)

    async def create_variant(
        self,
        product_id: str,
        variant_id: str,
        inventory_record: Union[InventoryRecord, dict[str, Any]],
    ) -> InventoryRecord:
        """Create a new variant inventory record

        Args:
            product_id: ID of the product.
            variant_id: ID of the variant.
            inventory_record: A ``InventoryRecord`` model or dict. Required fields: AddressID.

        Returns:
            The InventoryRecord object.
        """
        resp = await self._http.post(
            f"/products/{product_id}/variants/{variant_id}/inventoryrecords",
            json=self._serialize(inventory_record),
        )
        return InventoryRecord(**resp.json())

    async def get_variant(
        self,
        product_id: str,
        variant_id: str,
        inventory_record_id: str,
    ) -> InventoryRecord:
        """Get a single variant inventory record

        Args:
            product_id: ID of the product.
            variant_id: ID of the variant.
            inventory_record_id: ID of the inventory record.

        Returns:
            The InventoryRecord object.
        """
        resp = await self._http.get(
            f"/products/{product_id}/variants/{variant_id}/inventoryrecords/{inventory_record_id}"
        )
        return InventoryRecord(**resp.json())

    async def save_variant(
        self,
        product_id: str,
        variant_id: str,
        inventory_record_id: str,
        inventory_record: Union[InventoryRecord, dict[str, Any]],
    ) -> InventoryRecord:
        """Create or update a variant inventory record

        Args:
            product_id: ID of the product.
            variant_id: ID of the variant.
            inventory_record_id: ID of the inventory record.
            inventory_record: A ``InventoryRecord`` model or dict. Required fields: AddressID.

        Returns:
            The InventoryRecord object.
        """
        resp = await self._http.put(
            f"/products/{product_id}/variants/{variant_id}/inventoryrecords/{inventory_record_id}",
            json=self._serialize(inventory_record),
        )
        return InventoryRecord(**resp.json())

    async def delete_variant(
        self,
        product_id: str,
        variant_id: str,
        inventory_record_id: str,
    ) -> None:
        """Delete a variant inventory record

        Args:
            product_id: ID of the product.
            variant_id: ID of the variant.
            inventory_record_id: ID of the inventory record.
        """
        await self._http.delete(
            f"/products/{product_id}/variants/{variant_id}/inventoryrecords/{inventory_record_id}"
        )

    async def patch_variant(
        self,
        product_id: str,
        variant_id: str,
        inventory_record_id: str,
        partial: dict[str, Any],
    ) -> InventoryRecord:
        """Partially update a variant inventory record

        Args:
            product_id: ID of the product.
            variant_id: ID of the variant.
            inventory_record_id: ID of the inventory record.
            partial: A dict of fields to update.

        Returns:
            The InventoryRecord object.
        """
        resp = await self._http.patch(
            f"/products/{product_id}/variants/{variant_id}/inventoryrecords/{inventory_record_id}",
            json=partial,
        )
        return InventoryRecord(**resp.json())

    async def delete_variant_assignment(
        self,
        product_id: str,
        variant_id: str,
        inventory_record_id: str,
        *,
        buyer_id: Optional[str] = None,
        user_id: Optional[str] = None,
        user_group_id: Optional[str] = None,
    ) -> None:
        """Delete an inventory record variant assignment

        Args:
            product_id: ID of the product.
            variant_id: ID of the variant.
            inventory_record_id: ID of the inventory record.
            buyer_id: ID of the buyer.
            user_id: ID of the user.
            user_group_id: ID of the user group.
        """
        await self._http.delete(
            f"/products/{product_id}/variants/{variant_id}/inventoryrecords/{inventory_record_id}/assignments"
        )

    async def list_variant_assignments(
        self,
        product_id: str,
        variant_id: str,
        *,
        buyer_id: Optional[str] = None,
        inventory_record_id: Optional[str] = None,
        user_group_id: Optional[str] = None,
        level: Optional[str] = None,
        page: Optional[int] = None,
        page_size: Optional[int] = None,
    ) -> ListPage[InventoryRecordAssignment]:
        """List inventory record variant assignments

        Args:
            product_id: ID of the product.
            variant_id: ID of the variant.
            buyer_id: ID of the buyer.
            inventory_record_id: ID of the inventory record.
            user_group_id: ID of the user group.
            level: Level of the inventory record assignment. Possible values: Group, Company, BuyerGroup.
            page: Page of results to return. When paginating through many items (> page 30), we recommend the "Last ID" method, as outlined in the Advanced Querying documentation.
            page_size: Number of results to return per page.

        Returns:
            A paginated list of InventoryRecordAssignment objects.
        """
        params = self._build_list_params(
            page=page,
            page_size=page_size,
        )
        if buyer_id is not None:
            params["buyerID"] = buyer_id
        if inventory_record_id is not None:
            params["inventoryRecordID"] = inventory_record_id
        if user_group_id is not None:
            params["userGroupID"] = user_group_id
        if level is not None:
            params["level"] = level
        resp = await self._http.get(
            f"/products/{product_id}/variants/{variant_id}/inventoryrecords/assignments", **params
        )
        return self._parse_list(resp.json(), InventoryRecordAssignment)

    async def save_variant_assignment(
        self,
        product_id: str,
        variant_id: str,
        inventory_record_assignment: Union[InventoryRecordAssignment, dict[str, Any]],
    ) -> None:
        """Create or update an inventory record variant assignment

        Args:
            product_id: ID of the product.
            variant_id: ID of the variant.
            inventory_record_assignment: A ``InventoryRecordAssignment`` model or dict. Required fields: InventoryRecordID, BuyerID.
        """
        await self._http.post(
            f"/products/{product_id}/variants/{variant_id}/inventoryrecords/assignments",
            json=self._serialize(inventory_record_assignment),
        )
