# GENERATED by tools/codegen — DO NOT EDIT
# Source: ordercloud-openapi-v3.json
"""OrderCloud LineItems API resource."""

from __future__ import annotations
from typing import Any, Optional, Union

from ..models.address import Address
from ..models.line_item import LineItem
from ..models.misc import OrderDirection, SearchType
from ..models.order import ExtendedLineItem
from ..models.shared import ListPage
from .base import BaseResource

__all__ = ["LineItemsResource"]


class LineItemsResource(BaseResource):
    """Operations on OrderCloud LineItems."""

    async def list_across_orders(
        self,
        direction: OrderDirection,
        *,
        buyer_id: Optional[str] = None,
        supplier_id: Optional[str] = None,
        from_: Optional[str] = None,
        to: Optional[str] = None,
        search: Optional[str] = None,
        search_on: Optional[str] = None,
        search_type: Optional[SearchType] = None,
        sort_by: Optional[str] = None,
        page: Optional[int] = None,
        page_size: Optional[int] = None,
        filters: Optional[dict[str, Any]] = None,
    ) -> ListPage[ExtendedLineItem]:
        """List line item across orders

        Args:
            direction: Direction of the order, from the current user's perspective.
            buyer_id: ID of the buyer.
            supplier_id: ID of the supplier.
            from_: Lower bound of date range that the order was created.
            to: Upper bound of date range that the order was created.
            search: Word or phrase to search for.
            search_on: Comma-delimited list of fields to search on.
            search_type: Type of search to perform.
            sort_by: Comma-delimited list of fields to sort by.
            page: Page of results to return. When paginating through many items (> page 30), we recommend the "Last ID" method, as outlined in the Advanced Querying documentation.
            page_size: Number of results to return per page.
            filters: An object or dictionary representing key/value pairs to apply as filters. Valid keys are top-level properties of the returned model or 'xp.???'

        Returns:
            A paginated list of ExtendedLineItem objects.
        """
        params = self._build_list_params(
            search=search,
            search_on=search_on,
            sort_by=sort_by,
            page=page,
            page_size=page_size,
            filters=filters,
        )
        if buyer_id is not None:
            params["buyerID"] = buyer_id
        if supplier_id is not None:
            params["supplierID"] = supplier_id
        if from_ is not None:
            params["from"] = from_
        if to is not None:
            params["to"] = to
        if search_type is not None:
            params["searchType"] = search_type
        resp = await self._http.get(f"/lineitems/{direction}", **params)
        return self._parse_list(resp.json(), ExtendedLineItem)

    async def list(
        self,
        direction: OrderDirection,
        order_id: str,
        *,
        search: Optional[str] = None,
        search_on: Optional[str] = None,
        sort_by: Optional[str] = None,
        page: Optional[int] = None,
        page_size: Optional[int] = None,
        filters: Optional[dict[str, Any]] = None,
    ) -> ListPage[LineItem]:
        """List line items

        Args:
            direction: Direction of the order, from the current user's perspective.
            order_id: ID of the order.
            search: Word or phrase to search for.
            search_on: Comma-delimited list of fields to search on.
            sort_by: Comma-delimited list of fields to sort by.
            page: Page of results to return. When paginating through many items (> page 30), we recommend the "Last ID" method, as outlined in the Advanced Querying documentation.
            page_size: Number of results to return per page.
            filters: An object or dictionary representing key/value pairs to apply as filters. Valid keys are top-level properties of the returned model or 'xp.???'

        Returns:
            A paginated list of LineItem objects.
        """
        params = self._build_list_params(
            search=search,
            search_on=search_on,
            sort_by=sort_by,
            page=page,
            page_size=page_size,
            filters=filters,
        )
        resp = await self._http.get(f"/orders/{direction}/{order_id}/lineitems", **params)
        return self._parse_list(resp.json(), LineItem)

    async def create(
        self,
        direction: OrderDirection,
        order_id: str,
        line_item: Union[LineItem, dict[str, Any]],
    ) -> LineItem:
        """Create a line item

        Args:
            direction: Direction of the order, from the current user's perspective.
            order_id: ID of the order.
            line_item: A ``LineItem`` model or dict. Required fields: ProductID.

        Returns:
            The LineItem object.
        """
        resp = await self._http.post(
            f"/orders/{direction}/{order_id}/lineitems", json=self._serialize(line_item)
        )
        return LineItem(**resp.json())

    async def get(
        self,
        direction: OrderDirection,
        order_id: str,
        line_item_id: str,
    ) -> LineItem:
        """Retrieve a line item

        Args:
            direction: Direction of the order, from the current user's perspective.
            order_id: ID of the order.
            line_item_id: ID of the line item.

        Returns:
            The LineItem object.
        """
        resp = await self._http.get(f"/orders/{direction}/{order_id}/lineitems/{line_item_id}")
        return LineItem(**resp.json())

    async def save(
        self,
        direction: OrderDirection,
        order_id: str,
        line_item_id: str,
        line_item: Union[LineItem, dict[str, Any]],
    ) -> LineItem:
        """Create or update a line item

        Args:
            direction: Direction of the order, from the current user's perspective.
            order_id: ID of the order.
            line_item_id: ID of the line item.
            line_item: A ``LineItem`` model or dict. Required fields: ProductID.

        Returns:
            The LineItem object.
        """
        resp = await self._http.put(
            f"/orders/{direction}/{order_id}/lineitems/{line_item_id}",
            json=self._serialize(line_item),
        )
        return LineItem(**resp.json())

    async def delete(
        self,
        direction: OrderDirection,
        order_id: str,
        line_item_id: str,
    ) -> None:
        """Delete a line item

        Args:
            direction: Direction of the order, from the current user's perspective.
            order_id: ID of the order.
            line_item_id: ID of the line item.
        """
        await self._http.delete(f"/orders/{direction}/{order_id}/lineitems/{line_item_id}")

    async def patch(
        self,
        direction: OrderDirection,
        order_id: str,
        line_item_id: str,
        partial: dict[str, Any],
    ) -> LineItem:
        """Partially update a line item

        Args:
            direction: Direction of the order, from the current user's perspective.
            order_id: ID of the order.
            line_item_id: ID of the line item.
            partial: A dict of fields to update.

        Returns:
            The LineItem object.
        """
        resp = await self._http.patch(
            f"/orders/{direction}/{order_id}/lineitems/{line_item_id}", json=partial
        )
        return LineItem(**resp.json())

    async def set_shipping_address(
        self,
        direction: OrderDirection,
        order_id: str,
        line_item_id: str,
        address: Union[Address, dict[str, Any]],
    ) -> LineItem:
        """Set a shipping address

        Args:
            direction: Direction of the order, from the current user's perspective.
            order_id: ID of the order.
            line_item_id: ID of the line item.
            address: A ``Address`` model or dict. Required fields: Street1, City, Country.

        Returns:
            The LineItem object.
        """
        resp = await self._http.put(
            f"/orders/{direction}/{order_id}/lineitems/{line_item_id}/shipto",
            json=self._serialize(address),
        )
        return LineItem(**resp.json())

    async def patch_shipping_address(
        self,
        direction: OrderDirection,
        order_id: str,
        line_item_id: str,
        partial: dict[str, Any],
    ) -> LineItem:
        """Partially update a line item shipping address

        Args:
            direction: Direction of the order, from the current user's perspective.
            order_id: ID of the order.
            line_item_id: ID of the line item.
            partial: A dict of fields to update.

        Returns:
            The LineItem object.
        """
        resp = await self._http.patch(
            f"/orders/{direction}/{order_id}/lineitems/{line_item_id}/shipto", json=partial
        )
        return LineItem(**resp.json())
