# GENERATED by tools/codegen — DO NOT EDIT
# Source: ordercloud-openapi-v3.json
"""OrderCloud Locales API resource."""

from __future__ import annotations
from typing import Any, Optional, Union

from ..models.assignments import LocaleAssignment
from ..models.user import Locale
from ..models.shared import ListPage
from .base import BaseResource

__all__ = ["LocalesResource"]


class LocalesResource(BaseResource):
    """Operations on OrderCloud Locales."""

    async def list(
        self,
        *,
        search: Optional[str] = None,
        search_on: Optional[str] = None,
        sort_by: Optional[str] = None,
        page: Optional[int] = None,
        page_size: Optional[int] = None,
        filters: Optional[dict[str, Any]] = None,
    ) -> ListPage[Locale]:
        """List locales

        Args:
            search: Word or phrase to search for.
            search_on: Comma-delimited list of fields to search on.
            sort_by: Comma-delimited list of fields to sort by.
            page: Page of results to return. When paginating through many items (> page 30), we recommend the "Last ID" method, as outlined in the Advanced Querying documentation.
            page_size: Number of results to return per page.
            filters: An object or dictionary representing key/value pairs to apply as filters. Valid keys are top-level properties of the returned model or 'xp.???'

        Returns:
            A paginated list of Locale objects.
        """
        params = self._build_list_params(
            search=search,
            search_on=search_on,
            sort_by=sort_by,
            page=page,
            page_size=page_size,
            filters=filters,
        )
        resp = await self._http.get("/locales", **params)
        return self._parse_list(resp.json(), Locale)

    async def create(
        self,
        locale: Union[Locale, dict[str, Any]],
    ) -> Locale:
        """Create a locale

        Args:
            locale: A ``Locale`` model or dict. Required fields: Currency.

        Returns:
            The Locale object.
        """
        resp = await self._http.post("/locales", json=self._serialize(locale))
        return Locale(**resp.json())

    async def get(
        self,
        locale_id: str,
    ) -> Locale:
        """Retrieve a locale

        Args:
            locale_id: ID of the locale.

        Returns:
            The Locale object.
        """
        resp = await self._http.get(f"/locales/{locale_id}")
        return Locale(**resp.json())

    async def save(
        self,
        locale_id: str,
        locale: Union[Locale, dict[str, Any]],
    ) -> Locale:
        """Create or update a locale

        Args:
            locale_id: ID of the locale.
            locale: A ``Locale`` model or dict. Required fields: Currency.

        Returns:
            The Locale object.
        """
        resp = await self._http.put(
            f"/locales/{locale_id}",
            json=self._serialize(locale),
        )
        return Locale(**resp.json())

    async def delete(
        self,
        locale_id: str,
    ) -> None:
        """Delete a locale

        Args:
            locale_id: ID of the locale.
        """
        await self._http.delete(f"/locales/{locale_id}")

    async def patch(
        self,
        locale_id: str,
        partial: dict[str, Any],
    ) -> Locale:
        """Partially update a locale

        Args:
            locale_id: ID of the locale.
            partial: A dict of fields to update.

        Returns:
            The Locale object.
        """
        resp = await self._http.patch(f"/locales/{locale_id}", json=partial)
        return Locale(**resp.json())

    async def delete_assignment(
        self,
        locale_id: str,
        *,
        buyer_id: Optional[str],
        user_id: Optional[str] = None,
        user_group_id: Optional[str] = None,
    ) -> None:
        """Delete a locale assignment

        Args:
            locale_id: ID of the locale.
            buyer_id: ID of the buyer.
            user_id: ID of the user.
            user_group_id: ID of the user group.
        """
        _params: dict[str, Any] = {}
        if buyer_id is not None:
            _params["buyerID"] = buyer_id
        if user_id is not None:
            _params["userID"] = user_id
        if user_group_id is not None:
            _params["userGroupID"] = user_group_id
        await self._http.delete(f"/locales/{locale_id}/assignments", **_params)

    async def list_assignments(
        self,
        *,
        buyer_id: Optional[str] = None,
        locale_id: Optional[str] = None,
        user_group_id: Optional[str] = None,
        level: Optional[str] = None,
        page: Optional[int] = None,
        page_size: Optional[int] = None,
    ) -> ListPage[LocaleAssignment]:
        """List locale assignments

        Args:
            buyer_id: ID of the buyer.
            locale_id: ID of the locale.
            user_group_id: ID of the user group.
            level: Level of the locale assignment. Possible values: Group, Company, BuyerGroup.
            page: Page of results to return. When paginating through many items (> page 30), we recommend the "Last ID" method, as outlined in the Advanced Querying documentation.
            page_size: Number of results to return per page.

        Returns:
            A paginated list of LocaleAssignment objects.
        """
        params = self._build_list_params(
            page=page,
            page_size=page_size,
        )
        if buyer_id is not None:
            params["buyerID"] = buyer_id
        if locale_id is not None:
            params["localeID"] = locale_id
        if user_group_id is not None:
            params["userGroupID"] = user_group_id
        if level is not None:
            params["level"] = level
        resp = await self._http.get("/locales/assignments", **params)
        return self._parse_list(resp.json(), LocaleAssignment)

    async def save_assignment(
        self,
        locale_assignment: Union[LocaleAssignment, dict[str, Any]],
    ) -> None:
        """Create or update a locale assignment

        Args:
            locale_assignment: A ``LocaleAssignment`` model or dict. Required fields: LocaleID, BuyerID.
        """
        await self._http.post("/locales/assignments", json=self._serialize(locale_assignment))
