# GENERATED by tools/codegen — DO NOT EDIT
# Source: ordercloud-openapi-v3.json
"""OrderCloud MessageSenders API resource."""

from __future__ import annotations
from typing import Any, Optional, Union

from ..models.assignments import MessageCCListenerAssignment, MessageSenderAssignment
from ..models.message_sender import MessageSender
from ..models.shared import ListPage
from .base import BaseResource

__all__ = ["MessageSendersResource"]


class MessageSendersResource(BaseResource):
    """Operations on OrderCloud MessageSenders."""

    async def list(
        self,
        *,
        search: Optional[str] = None,
        search_on: Optional[str] = None,
        sort_by: Optional[str] = None,
        page: Optional[int] = None,
        page_size: Optional[int] = None,
        filters: Optional[dict[str, Any]] = None,
    ) -> ListPage[MessageSender]:
        """List message senders

        Args:
            search: Word or phrase to search for.
            search_on: Comma-delimited list of fields to search on.
            sort_by: Comma-delimited list of fields to sort by.
            page: Page of results to return. When paginating through many items (> page 30), we recommend the "Last ID" method, as outlined in the Advanced Querying documentation.
            page_size: Number of results to return per page.
            filters: An object or dictionary representing key/value pairs to apply as filters. Valid keys are top-level properties of the returned model or 'xp.???'

        Returns:
            A paginated list of MessageSender objects.
        """
        params = self._build_list_params(
            search=search,
            search_on=search_on,
            sort_by=sort_by,
            page=page,
            page_size=page_size,
            filters=filters,
        )
        resp = await self._http.get("/messagesenders", **params)
        return self._parse_list(resp.json(), MessageSender)

    async def create(
        self,
        message_sender: Union[MessageSender, dict[str, Any]],
    ) -> MessageSender:
        """Create a message sender

        Args:
            message_sender: A ``MessageSender`` model or dict. Required fields: Name, MessageTypes, DeliveryConfigID.

        Returns:
            The MessageSender object.
        """
        resp = await self._http.post("/messagesenders", json=self._serialize(message_sender))
        return MessageSender(**resp.json())

    async def get(
        self,
        message_sender_id: str,
    ) -> MessageSender:
        """Retrieve a message sender

        Args:
            message_sender_id: ID of the message sender.

        Returns:
            The MessageSender object.
        """
        resp = await self._http.get(f"/messagesenders/{message_sender_id}")
        return MessageSender(**resp.json())

    async def save(
        self,
        message_sender_id: str,
        message_sender: Union[MessageSender, dict[str, Any]],
    ) -> MessageSender:
        """Create or update a message sender

        Args:
            message_sender_id: ID of the message sender.
            message_sender: A ``MessageSender`` model or dict. Required fields: Name, MessageTypes, DeliveryConfigID.

        Returns:
            The MessageSender object.
        """
        resp = await self._http.put(
            f"/messagesenders/{message_sender_id}",
            json=self._serialize(message_sender),
        )
        return MessageSender(**resp.json())

    async def delete(
        self,
        message_sender_id: str,
    ) -> None:
        """Delete a message sender

        Args:
            message_sender_id: ID of the message sender.
        """
        await self._http.delete(f"/messagesenders/{message_sender_id}")

    async def patch(
        self,
        message_sender_id: str,
        partial: dict[str, Any],
    ) -> MessageSender:
        """Partially update a message sender

        Args:
            message_sender_id: ID of the message sender.
            partial: A dict of fields to update.

        Returns:
            The MessageSender object.
        """
        resp = await self._http.patch(f"/messagesenders/{message_sender_id}", json=partial)
        return MessageSender(**resp.json())

    async def delete_assignment(
        self,
        message_sender_id: str,
        *,
        buyer_id: Optional[str] = None,
        user_id: Optional[str] = None,
        user_group_id: Optional[str] = None,
        supplier_id: Optional[str] = None,
    ) -> None:
        """Delete a message sender assignment

        Args:
            message_sender_id: ID of the message sender.
            buyer_id: ID of the buyer.
            user_id: ID of the user.
            user_group_id: ID of the user group.
            supplier_id: ID of the supplier.
        """
        await self._http.delete(f"/messagesenders/{message_sender_id}/assignments")

    async def list_assignments(
        self,
        *,
        buyer_id: Optional[str] = None,
        message_sender_id: Optional[str] = None,
        user_group_id: Optional[str] = None,
        level: Optional[str] = None,
        page: Optional[int] = None,
        page_size: Optional[int] = None,
        supplier_id: Optional[str] = None,
    ) -> ListPage[MessageSenderAssignment]:
        """List message sender assignments

        Args:
            buyer_id: ID of the buyer.
            message_sender_id: ID of the message sender.
            user_group_id: ID of the user group.
            level: Level of the message sender assignment. Possible values: Group, Company, BuyerGroup.
            page: Page of results to return. When paginating through many items (> page 30), we recommend the "Last ID" method, as outlined in the Advanced Querying documentation.
            page_size: Number of results to return per page.
            supplier_id: ID of the supplier.

        Returns:
            A paginated list of MessageSenderAssignment objects.
        """
        params = self._build_list_params(
            page=page,
            page_size=page_size,
        )
        if buyer_id is not None:
            params["buyerID"] = buyer_id
        if message_sender_id is not None:
            params["messageSenderID"] = message_sender_id
        if user_group_id is not None:
            params["userGroupID"] = user_group_id
        if level is not None:
            params["level"] = level
        if supplier_id is not None:
            params["supplierID"] = supplier_id
        resp = await self._http.get("/messagesenders/assignments", **params)
        return self._parse_list(resp.json(), MessageSenderAssignment)

    async def save_assignment(
        self,
        message_sender_assignment: Union[MessageSenderAssignment, dict[str, Any]],
    ) -> None:
        """Create or update a message sender assignment

        Args:
            message_sender_assignment: A ``MessageSenderAssignment`` model or dict. Required fields: MessageSenderID.
        """
        await self._http.post(
            "/messagesenders/assignments", json=self._serialize(message_sender_assignment)
        )

    async def list_cc_listener_assignments(
        self,
        *,
        search: Optional[str] = None,
        search_on: Optional[str] = None,
        sort_by: Optional[str] = None,
        page: Optional[int] = None,
        page_size: Optional[int] = None,
        filters: Optional[dict[str, Any]] = None,
    ) -> ListPage[MessageCCListenerAssignment]:
        """List message sender cc listener assignments

        Args:
            search: Word or phrase to search for.
            search_on: Comma-delimited list of fields to search on.
            sort_by: Comma-delimited list of fields to sort by.
            page: Page of results to return. When paginating through many items (> page 30), we recommend the "Last ID" method, as outlined in the Advanced Querying documentation.
            page_size: Number of results to return per page.
            filters: An object or dictionary representing key/value pairs to apply as filters. Valid keys are top-level properties of the returned model or 'xp.???'

        Returns:
            A paginated list of MessageCCListenerAssignment objects.
        """
        params = self._build_list_params(
            search=search,
            search_on=search_on,
            sort_by=sort_by,
            page=page,
            page_size=page_size,
            filters=filters,
        )
        resp = await self._http.get("/messagesenders/CCListenerAssignments", **params)
        return self._parse_list(resp.json(), MessageCCListenerAssignment)

    async def save_cc_listener_assignment(
        self,
        message_cc_listener_assignment: Union[MessageCCListenerAssignment, dict[str, Any]],
    ) -> None:
        """Create or update a message sender cc listener assignment

        Args:
            message_cc_listener_assignment: A ``MessageCCListenerAssignment`` model or dict. Required fields: MessageSenderAssignment, MessageType.
        """
        await self._http.post(
            "/messagesenders/CCListenerAssignments",
            json=self._serialize(message_cc_listener_assignment),
        )
