# GENERATED by tools/codegen — DO NOT EDIT
# Source: ordercloud-openapi-v3.json
"""OrderCloud PriceSchedules API resource."""

from __future__ import annotations
from typing import Any, Optional, Union

from ..models.price_schedule import PriceBreak, PriceSchedule
from ..models.shared import ListPage
from .base import BaseResource

__all__ = ["PriceSchedulesResource"]


class PriceSchedulesResource(BaseResource):
    """Operations on OrderCloud PriceSchedules."""

    async def list(
        self,
        *,
        search: Optional[str] = None,
        search_on: Optional[str] = None,
        sort_by: Optional[str] = None,
        page: Optional[int] = None,
        page_size: Optional[int] = None,
        filters: Optional[dict[str, Any]] = None,
    ) -> ListPage[PriceSchedule]:
        """List price schedules

        Args:
            search: Word or phrase to search for.
            search_on: Comma-delimited list of fields to search on.
            sort_by: Comma-delimited list of fields to sort by.
            page: Page of results to return. When paginating through many items (> page 30), we recommend the "Last ID" method, as outlined in the Advanced Querying documentation.
            page_size: Number of results to return per page.
            filters: An object or dictionary representing key/value pairs to apply as filters. Valid keys are top-level properties of the returned model or 'xp.???'

        Returns:
            A paginated list of PriceSchedule objects.
        """
        params = self._build_list_params(
            search=search,
            search_on=search_on,
            sort_by=sort_by,
            page=page,
            page_size=page_size,
            filters=filters,
        )
        resp = await self._http.get("/priceschedules", **params)
        return self._parse_list(resp.json(), PriceSchedule)

    async def create(
        self,
        price_schedule: Union[PriceSchedule, dict[str, Any]],
    ) -> PriceSchedule:
        """Create a price schedule

        Args:
            price_schedule: A ``PriceSchedule`` model or dict. Required fields: Name.

        Returns:
            The PriceSchedule object.
        """
        resp = await self._http.post("/priceschedules", json=self._serialize(price_schedule))
        return PriceSchedule(**resp.json())

    async def get(
        self,
        price_schedule_id: str,
    ) -> PriceSchedule:
        """Retrieve a price schedule

        Args:
            price_schedule_id: ID of the price schedule.

        Returns:
            The PriceSchedule object.
        """
        resp = await self._http.get(f"/priceschedules/{price_schedule_id}")
        return PriceSchedule(**resp.json())

    async def save(
        self,
        price_schedule_id: str,
        price_schedule: Union[PriceSchedule, dict[str, Any]],
    ) -> PriceSchedule:
        """Create or update a price schedule

        Args:
            price_schedule_id: ID of the price schedule.
            price_schedule: A ``PriceSchedule`` model or dict. Required fields: Name.

        Returns:
            The PriceSchedule object.
        """
        resp = await self._http.put(
            f"/priceschedules/{price_schedule_id}",
            json=self._serialize(price_schedule),
        )
        return PriceSchedule(**resp.json())

    async def delete(
        self,
        price_schedule_id: str,
    ) -> None:
        """Delete a price schedule

        Args:
            price_schedule_id: ID of the price schedule.
        """
        await self._http.delete(f"/priceschedules/{price_schedule_id}")

    async def patch(
        self,
        price_schedule_id: str,
        partial: dict[str, Any],
    ) -> PriceSchedule:
        """Partially update a price schedule

        Args:
            price_schedule_id: ID of the price schedule.
            partial: A dict of fields to update.

        Returns:
            The PriceSchedule object.
        """
        resp = await self._http.patch(f"/priceschedules/{price_schedule_id}", json=partial)
        return PriceSchedule(**resp.json())

    async def save_price_break(
        self,
        price_schedule_id: str,
        price_break: Union[PriceBreak, dict[str, Any]],
    ) -> PriceSchedule:
        """Create or update a price schedule price break

        Args:
            price_schedule_id: ID of the price schedule.
            price_break: A ``PriceBreak`` model or dict. Required fields: Quantity, Price.

        Returns:
            The PriceSchedule object.
        """
        resp = await self._http.post(
            f"/priceschedules/{price_schedule_id}/PriceBreaks", json=self._serialize(price_break)
        )
        return PriceSchedule(**resp.json())

    async def delete_price_break(
        self,
        price_schedule_id: str,
        *,
        quantity: Optional[int] = None,
    ) -> None:
        """Delete a price schedule price break

        Args:
            price_schedule_id: ID of the price schedule.
            quantity: Quantity of the price schedule.
        """
        await self._http.delete(f"/priceschedules/{price_schedule_id}/PriceBreaks")
