# GENERATED by tools/codegen — DO NOT EDIT
# Source: ordercloud-openapi-v3.json
"""OrderCloud ProductCollections API resource."""

from __future__ import annotations
from typing import Any, Optional

from ..models.misc import SearchType
from ..models.product_collection import ProductCollection, ProductCollectionProduct
from ..models.shared import ListPage, MetaWithFacets
from .base import BaseResource

__all__ = ["ProductCollectionsResource"]


class ProductCollectionsResource(BaseResource):
    """Operations on OrderCloud ProductCollections."""

    async def list(
        self,
        buyer_id: str,
        *,
        search: Optional[str] = None,
        search_on: Optional[str] = None,
        sort_by: Optional[str] = None,
        page: Optional[int] = None,
        page_size: Optional[int] = None,
        filters: Optional[dict[str, Any]] = None,
    ) -> ListPage[ProductCollection]:
        """List product collections

        Args:
            buyer_id: ID of the buyer.
            search: Word or phrase to search for.
            search_on: Comma-delimited list of fields to search on.
            sort_by: Comma-delimited list of fields to sort by.
            page: Page of results to return. When paginating through many items (> page 30), we recommend the "Last ID" method, as outlined in the Advanced Querying documentation.
            page_size: Number of results to return per page.
            filters: An object or dictionary representing key/value pairs to apply as filters. Valid keys are top-level properties of the returned model or 'xp.???'

        Returns:
            A paginated list of ProductCollection objects.
        """
        params = self._build_list_params(
            search=search,
            search_on=search_on,
            sort_by=sort_by,
            page=page,
            page_size=page_size,
            filters=filters,
        )
        resp = await self._http.get(f"/buyers/{buyer_id}/productcollections", **params)
        return self._parse_list(resp.json(), ProductCollection)

    async def get(
        self,
        buyer_id: str,
        product_collection_id: str,
    ) -> ProductCollection:
        """Retrieve a product collection

        Args:
            buyer_id: ID of the buyer.
            product_collection_id: ID of the product collection.

        Returns:
            The ProductCollection object.
        """
        resp = await self._http.get(
            f"/buyers/{buyer_id}/productcollections/{product_collection_id}"
        )
        return ProductCollection(**resp.json())

    async def list_entries(
        self,
        buyer_id: str,
        product_collection_id: str,
        *,
        search: Optional[str] = None,
        search_on: Optional[str] = None,
        search_type: Optional[SearchType] = None,
        sort_by: Optional[str] = None,
        page: Optional[int] = None,
        page_size: Optional[int] = None,
        filters: Optional[dict[str, Any]] = None,
    ) -> ListPage[ProductCollectionProduct]:
        """List product collection entries

        Args:
            buyer_id: ID of the buyer.
            product_collection_id: ID of the product collection.
            search: Word or phrase to search for.
            search_on: Comma-delimited list of fields to search on.
            search_type: Type of search to perform.
            sort_by: Comma-delimited list of fields to sort by.
            page: Page of results to return. When paginating through many items (> page 30), we recommend the "Last ID" method, as outlined in the Advanced Querying documentation.
            page_size: Number of results to return per page.
            filters: An object or dictionary representing key/value pairs to apply as filters. Valid keys are top-level properties of the returned model or 'xp.???'

        Returns:
            A paginated list of ProductCollectionProduct objects.
        """
        params = self._build_list_params(
            search=search,
            search_on=search_on,
            sort_by=sort_by,
            page=page,
            page_size=page_size,
            filters=filters,
        )
        if search_type is not None:
            params["searchType"] = search_type
        resp = await self._http.get(
            f"/buyers/{buyer_id}/productcollections/{product_collection_id}/products", **params
        )
        return self._parse_list(resp.json(), ProductCollectionProduct, meta_cls=MetaWithFacets)
