# GENERATED by tools/codegen — DO NOT EDIT
# Source: ordercloud-openapi-v3.json
"""OrderCloud Products API resource."""

from __future__ import annotations
from typing import Any, Optional, Union

from ..models.assignments import ProductAssignment
from ..models.misc import SearchType
from ..models.product import Product, ProductSupplier, Variant, VariantOverrides
from ..models.spec import Spec
from ..models.shared import ListPage, MetaWithFacets
from .base import BaseResource

__all__ = ["ProductsResource"]


class ProductsResource(BaseResource):
    """Operations on OrderCloud Products."""

    async def list(
        self,
        *,
        catalog_id: Optional[str] = None,
        category_id: Optional[str] = None,
        supplier_id: Optional[str] = None,
        search: Optional[str] = None,
        search_on: Optional[str] = None,
        search_type: Optional[SearchType] = None,
        sort_by: Optional[str] = None,
        page: Optional[int] = None,
        page_size: Optional[int] = None,
        filters: Optional[dict[str, Any]] = None,
    ) -> ListPage[Product]:
        """List products

        Args:
            catalog_id: ID of the catalog.
            category_id: ID of the category.
            supplier_id: ID of the supplier.
            search: Word or phrase to search for.
            search_on: Comma-delimited list of fields to search on.
            search_type: Type of search to perform.
            sort_by: Comma-delimited list of fields to sort by.
            page: Page of results to return. When paginating through many items (> page 30), we recommend the "Last ID" method, as outlined in the Advanced Querying documentation.
            page_size: Number of results to return per page.
            filters: An object or dictionary representing key/value pairs to apply as filters. Valid keys are top-level properties of the returned model or 'xp.???'

        Returns:
            A paginated list of Product objects.
        """
        params = self._build_list_params(
            search=search,
            search_on=search_on,
            sort_by=sort_by,
            page=page,
            page_size=page_size,
            filters=filters,
        )
        if catalog_id is not None:
            params["catalogID"] = catalog_id
        if category_id is not None:
            params["categoryID"] = category_id
        if supplier_id is not None:
            params["supplierID"] = supplier_id
        if search_type is not None:
            params["searchType"] = search_type
        resp = await self._http.get("/products", **params)
        return self._parse_list(resp.json(), Product, meta_cls=MetaWithFacets)

    async def create(
        self,
        product: Union[Product, dict[str, Any]],
    ) -> Product:
        """Create a product

        Args:
            product: A ``Product`` model or dict. Required fields: Name.

        Returns:
            The Product object.
        """
        resp = await self._http.post("/products", json=self._serialize(product))
        return Product(**resp.json())

    async def get(
        self,
        product_id: str,
    ) -> Product:
        """Retrieve a product

        Args:
            product_id: ID of the product.

        Returns:
            The Product object.
        """
        resp = await self._http.get(f"/products/{product_id}")
        return Product(**resp.json())

    async def save(
        self,
        product_id: str,
        product: Union[Product, dict[str, Any]],
    ) -> Product:
        """Create or update a product

        Args:
            product_id: ID of the product.
            product: A ``Product`` model or dict. Required fields: Name.

        Returns:
            The Product object.
        """
        resp = await self._http.put(
            f"/products/{product_id}",
            json=self._serialize(product),
        )
        return Product(**resp.json())

    async def delete(
        self,
        product_id: str,
    ) -> None:
        """Delete a product

        Args:
            product_id: ID of the product.
        """
        await self._http.delete(f"/products/{product_id}")

    async def patch(
        self,
        product_id: str,
        partial: dict[str, Any],
    ) -> Product:
        """Partially update a product

        Args:
            product_id: ID of the product.
            partial: A dict of fields to update.

        Returns:
            The Product object.
        """
        resp = await self._http.patch(f"/products/{product_id}", json=partial)
        return Product(**resp.json())

    async def delete_assignment(
        self,
        product_id: str,
        buyer_id: str,
        *,
        user_id: Optional[str] = None,
        user_group_id: Optional[str] = None,
        seller_id: Optional[str] = None,
    ) -> None:
        """Delete a product assignment

        Args:
            product_id: ID of the product.
            buyer_id: ID of the buyer.
            user_id: ID of the user.
            user_group_id: ID of the user group.
            seller_id: ID of the seller.
        """
        await self._http.delete(f"/products/{product_id}/assignments/{buyer_id}")

    async def list_specs(
        self,
        product_id: str,
        *,
        search: Optional[str] = None,
        search_on: Optional[str] = None,
        sort_by: Optional[str] = None,
        page: Optional[int] = None,
        page_size: Optional[int] = None,
        filters: Optional[dict[str, Any]] = None,
    ) -> ListPage[Spec]:
        """List product specs

        Args:
            product_id: ID of the product.
            search: Word or phrase to search for.
            search_on: Comma-delimited list of fields to search on.
            sort_by: Comma-delimited list of fields to sort by.
            page: Page of results to return. When paginating through many items (> page 30), we recommend the "Last ID" method, as outlined in the Advanced Querying documentation.
            page_size: Number of results to return per page.
            filters: An object or dictionary representing key/value pairs to apply as filters. Valid keys are top-level properties of the returned model or 'xp.???'

        Returns:
            A paginated list of Spec objects.
        """
        params = self._build_list_params(
            search=search,
            search_on=search_on,
            sort_by=sort_by,
            page=page,
            page_size=page_size,
            filters=filters,
        )
        resp = await self._http.get(f"/products/{product_id}/specs", **params)
        return self._parse_list(resp.json(), Spec)

    async def list_suppliers(
        self,
        product_id: str,
        *,
        search: Optional[str] = None,
        search_on: Optional[str] = None,
        sort_by: Optional[str] = None,
        page: Optional[int] = None,
        page_size: Optional[int] = None,
        filters: Optional[dict[str, Any]] = None,
    ) -> ListPage[ProductSupplier]:
        """List product suppliers

        Args:
            product_id: ID of the product.
            search: Word or phrase to search for.
            search_on: Comma-delimited list of fields to search on.
            sort_by: Comma-delimited list of fields to sort by.
            page: Page of results to return. When paginating through many items (> page 30), we recommend the "Last ID" method, as outlined in the Advanced Querying documentation.
            page_size: Number of results to return per page.
            filters: An object or dictionary representing key/value pairs to apply as filters. Valid keys are top-level properties of the returned model or 'xp.???'

        Returns:
            A paginated list of ProductSupplier objects.
        """
        params = self._build_list_params(
            search=search,
            search_on=search_on,
            sort_by=sort_by,
            page=page,
            page_size=page_size,
            filters=filters,
        )
        resp = await self._http.get(f"/products/{product_id}/suppliers", **params)
        return self._parse_list(resp.json(), ProductSupplier)

    async def save_supplier(
        self,
        product_id: str,
        supplier_id: str,
        *,
        default_price_schedule_id: Optional[str] = None,
    ) -> None:
        """Create or update a product supplier

        Args:
            product_id: ID of the product.
            supplier_id: ID of the supplier.
            default_price_schedule_id: ID of the default price schedule.
        """
        await self._http.put(f"/products/{product_id}/suppliers/{supplier_id}")

    async def remove_supplier(
        self,
        product_id: str,
        supplier_id: str,
    ) -> None:
        """Remove a product supplier

        Args:
            product_id: ID of the product.
            supplier_id: ID of the supplier.
        """
        await self._http.delete(f"/products/{product_id}/suppliers/{supplier_id}")

    async def list_variants(
        self,
        product_id: str,
        *,
        search: Optional[str] = None,
        search_on: Optional[str] = None,
        sort_by: Optional[str] = None,
        page: Optional[int] = None,
        page_size: Optional[int] = None,
        filters: Optional[dict[str, Any]] = None,
    ) -> ListPage[Variant]:
        """List product variants

        Args:
            product_id: ID of the product.
            search: Word or phrase to search for.
            search_on: Comma-delimited list of fields to search on.
            sort_by: Comma-delimited list of fields to sort by.
            page: Page of results to return. When paginating through many items (> page 30), we recommend the "Last ID" method, as outlined in the Advanced Querying documentation.
            page_size: Number of results to return per page.
            filters: An object or dictionary representing key/value pairs to apply as filters. Valid keys are top-level properties of the returned model or 'xp.???'

        Returns:
            A paginated list of Variant objects.
        """
        params = self._build_list_params(
            search=search,
            search_on=search_on,
            sort_by=sort_by,
            page=page,
            page_size=page_size,
            filters=filters,
        )
        resp = await self._http.get(f"/products/{product_id}/variants", **params)
        return self._parse_list(resp.json(), Variant)

    async def get_variant(
        self,
        product_id: str,
        variant_id: str,
    ) -> Variant:
        """Retrieve a product variant

        Args:
            product_id: ID of the product.
            variant_id: ID of the variant.

        Returns:
            The Variant object.
        """
        resp = await self._http.get(f"/products/{product_id}/variants/{variant_id}")
        return Variant(**resp.json())

    async def save_variant(
        self,
        product_id: str,
        variant_id: str,
        variant: Union[Variant, dict[str, Any]],
    ) -> Variant:
        """Update a product variant

        Args:
            product_id: ID of the product.
            variant_id: ID of the variant.
            variant: A ``Variant`` model or dict.

        Returns:
            The Variant object.
        """
        resp = await self._http.put(
            f"/products/{product_id}/variants/{variant_id}",
            json=self._serialize(variant),
        )
        return Variant(**resp.json())

    async def patch_variant(
        self,
        product_id: str,
        variant_id: str,
        partial: dict[str, Any],
    ) -> Variant:
        """Partially update a product variant

        Args:
            product_id: ID of the product.
            variant_id: ID of the variant.
            partial: A dict of fields to update.

        Returns:
            The Variant object.
        """
        resp = await self._http.patch(f"/products/{product_id}/variants/{variant_id}", json=partial)
        return Variant(**resp.json())

    async def generate_variants(
        self,
        product_id: str,
        variant_overrides: Union[VariantOverrides, dict[str, Any]],
        *,
        overwrite_existing: Optional[bool] = None,
    ) -> Product:
        """Generate variants

        Args:
            product_id: ID of the product.
            variant_overrides: A ``VariantOverrides`` model or dict.
            overwrite_existing: Overwrite existing of the product.

        Returns:
            The Product object.
        """
        resp = await self._http.post(
            f"/products/{product_id}/variants/generate", json=self._serialize(variant_overrides)
        )
        return Product(**resp.json())

    async def list_assignments(
        self,
        *,
        product_id: Optional[str] = None,
        price_schedule_id: Optional[str] = None,
        buyer_id: Optional[str] = None,
        user_group_id: Optional[str] = None,
        level: Optional[str] = None,
        page: Optional[int] = None,
        page_size: Optional[int] = None,
    ) -> ListPage[ProductAssignment]:
        """List product assignments

        Args:
            product_id: ID of the product.
            price_schedule_id: ID of the price schedule.
            buyer_id: ID of the buyer.
            user_group_id: ID of the user group.
            level: Level of the product assignment. Possible values: Group, Company, BuyerGroup.
            page: Page of results to return. When paginating through many items (> page 30), we recommend the "Last ID" method, as outlined in the Advanced Querying documentation.
            page_size: Number of results to return per page.

        Returns:
            A paginated list of ProductAssignment objects.
        """
        params = self._build_list_params(
            page=page,
            page_size=page_size,
        )
        if product_id is not None:
            params["productID"] = product_id
        if price_schedule_id is not None:
            params["priceScheduleID"] = price_schedule_id
        if buyer_id is not None:
            params["buyerID"] = buyer_id
        if user_group_id is not None:
            params["userGroupID"] = user_group_id
        if level is not None:
            params["level"] = level
        resp = await self._http.get("/products/assignments", **params)
        return self._parse_list(resp.json(), ProductAssignment)

    async def save_assignment(
        self,
        product_assignment: Union[ProductAssignment, dict[str, Any]],
    ) -> None:
        """Create or update a product assignment

        Args:
            product_assignment: A ``ProductAssignment`` model or dict. Required fields: ProductID, BuyerID.
        """
        await self._http.post("/products/assignments", json=self._serialize(product_assignment))
