# GENERATED by tools/codegen — DO NOT EDIT
# Source: ordercloud-openapi-v3.json
"""OrderCloud ProductSyncs API resource."""

from __future__ import annotations
from typing import Any, Union

from ..models.sync import ProductSyncConfig, SyncProduct
from .base import BaseResource

__all__ = ["ProductSyncsResource"]


class ProductSyncsResource(BaseResource):
    """Operations on OrderCloud ProductSyncs."""

    async def get(
        self,
    ) -> ProductSyncConfig:
        """Retrieve a product sync

        Returns:
            The ProductSyncConfig object.
        """
        resp = await self._http.get("/integrations/productsync")
        return ProductSyncConfig(**resp.json())

    async def save(
        self,
        product_sync_config: Union[ProductSyncConfig, dict[str, Any]],
    ) -> ProductSyncConfig:
        """Create or update a product sync

        Args:
            product_sync_config: A ``ProductSyncConfig`` model or dict. Required fields: SyncProductChanged, SyncProductDeleted, DeliveryConfigID.

        Returns:
            The ProductSyncConfig object.
        """
        resp = await self._http.put(
            "/integrations/productsync",
            json=self._serialize(product_sync_config),
        )
        return ProductSyncConfig(**resp.json())

    async def delete(
        self,
    ) -> None:
        """Delete a product sync"""
        await self._http.delete("/integrations/productsync")

    async def patch(
        self,
        partial: dict[str, Any],
    ) -> ProductSyncConfig:
        """Partially update a product sync

        Args:
            partial: A dict of fields to update.

        Returns:
            The ProductSyncConfig object.
        """
        resp = await self._http.patch("/integrations/productsync", json=partial)
        return ProductSyncConfig(**resp.json())

    async def sync(
        self,
        sync_product: Union[SyncProduct, dict[str, Any]],
    ) -> None:
        """Sync a product

        Args:
            sync_product: A ``SyncProduct`` model or dict. Required fields: ProductID.
        """
        await self._http.post("/integrations/productsync/sync", json=self._serialize(sync_product))
