# GENERATED by tools/codegen — DO NOT EDIT
# Source: ordercloud-openapi-v3.json
"""OrderCloud Promotions API resource."""

from __future__ import annotations
from typing import Any, Optional, Union

from ..models.assignments import PromotionAssignment
from ..models.promotion import Promotion
from ..models.shared import ListPage
from .base import BaseResource

__all__ = ["PromotionsResource"]


class PromotionsResource(BaseResource):
    """Operations on OrderCloud Promotions."""

    async def list(
        self,
        *,
        search: Optional[str] = None,
        search_on: Optional[str] = None,
        sort_by: Optional[str] = None,
        page: Optional[int] = None,
        page_size: Optional[int] = None,
        filters: Optional[dict[str, Any]] = None,
    ) -> ListPage[Promotion]:
        """List promotions

        Args:
            search: Word or phrase to search for.
            search_on: Comma-delimited list of fields to search on.
            sort_by: Comma-delimited list of fields to sort by.
            page: Page of results to return. When paginating through many items (> page 30), we recommend the "Last ID" method, as outlined in the Advanced Querying documentation.
            page_size: Number of results to return per page.
            filters: An object or dictionary representing key/value pairs to apply as filters. Valid keys are top-level properties of the returned model or 'xp.???'

        Returns:
            A paginated list of Promotion objects.
        """
        params = self._build_list_params(
            search=search,
            search_on=search_on,
            sort_by=sort_by,
            page=page,
            page_size=page_size,
            filters=filters,
        )
        resp = await self._http.get("/promotions", **params)
        return self._parse_list(resp.json(), Promotion)

    async def create(
        self,
        promotion: Union[Promotion, dict[str, Any]],
    ) -> Promotion:
        """Create a promotion

        Args:
            promotion: A ``Promotion`` model or dict. Required fields: Code, EligibleExpression.

        Returns:
            The Promotion object.
        """
        resp = await self._http.post("/promotions", json=self._serialize(promotion))
        return Promotion(**resp.json())

    async def get(
        self,
        promotion_id: str,
    ) -> Promotion:
        """Retrieve a promotion

        Args:
            promotion_id: ID of the promotion.

        Returns:
            The Promotion object.
        """
        resp = await self._http.get(f"/promotions/{promotion_id}")
        return Promotion(**resp.json())

    async def save(
        self,
        promotion_id: str,
        promotion: Union[Promotion, dict[str, Any]],
    ) -> Promotion:
        """Create or update a promotion

        Args:
            promotion_id: ID of the promotion.
            promotion: A ``Promotion`` model or dict. Required fields: Code, EligibleExpression.

        Returns:
            The Promotion object.
        """
        resp = await self._http.put(
            f"/promotions/{promotion_id}",
            json=self._serialize(promotion),
        )
        return Promotion(**resp.json())

    async def delete(
        self,
        promotion_id: str,
    ) -> None:
        """Delete a promotion

        Args:
            promotion_id: ID of the promotion.
        """
        await self._http.delete(f"/promotions/{promotion_id}")

    async def patch(
        self,
        promotion_id: str,
        partial: dict[str, Any],
    ) -> Promotion:
        """Partially update a promotion

        Args:
            promotion_id: ID of the promotion.
            partial: A dict of fields to update.

        Returns:
            The Promotion object.
        """
        resp = await self._http.patch(f"/promotions/{promotion_id}", json=partial)
        return Promotion(**resp.json())

    async def delete_assignment(
        self,
        promotion_id: str,
        *,
        buyer_id: Optional[str],
        user_id: Optional[str] = None,
        user_group_id: Optional[str] = None,
    ) -> None:
        """Delete a promotion assignment

        Args:
            promotion_id: ID of the promotion.
            buyer_id: ID of the buyer.
            user_id: ID of the user.
            user_group_id: ID of the user group.
        """
        _params: dict[str, Any] = {}
        if buyer_id is not None:
            _params["buyerID"] = buyer_id
        if user_id is not None:
            _params["userID"] = user_id
        if user_group_id is not None:
            _params["userGroupID"] = user_group_id
        await self._http.delete(f"/promotions/{promotion_id}/assignments", **_params)

    async def list_assignments(
        self,
        *,
        buyer_id: Optional[str] = None,
        promotion_id: Optional[str] = None,
        user_group_id: Optional[str] = None,
        level: Optional[str] = None,
        page: Optional[int] = None,
        page_size: Optional[int] = None,
    ) -> ListPage[PromotionAssignment]:
        """List promotion assignments

        Args:
            buyer_id: ID of the buyer.
            promotion_id: ID of the promotion.
            user_group_id: ID of the user group.
            level: Level of the promotion assignment. Possible values: Group, Company, BuyerGroup.
            page: Page of results to return. When paginating through many items (> page 30), we recommend the "Last ID" method, as outlined in the Advanced Querying documentation.
            page_size: Number of results to return per page.

        Returns:
            A paginated list of PromotionAssignment objects.
        """
        params = self._build_list_params(
            page=page,
            page_size=page_size,
        )
        if buyer_id is not None:
            params["buyerID"] = buyer_id
        if promotion_id is not None:
            params["promotionID"] = promotion_id
        if user_group_id is not None:
            params["userGroupID"] = user_group_id
        if level is not None:
            params["level"] = level
        resp = await self._http.get("/promotions/assignments", **params)
        return self._parse_list(resp.json(), PromotionAssignment)

    async def save_assignment(
        self,
        promotion_assignment: Union[PromotionAssignment, dict[str, Any]],
    ) -> None:
        """Create or update a promotion assignment

        Args:
            promotion_assignment: A ``PromotionAssignment`` model or dict. Required fields: PromotionID, BuyerID.
        """
        await self._http.post("/promotions/assignments", json=self._serialize(promotion_assignment))
