# GENERATED by tools/codegen — DO NOT EDIT
# Source: ordercloud-openapi-v3.json
"""OrderCloud PromotionIntegrations API resource."""

from __future__ import annotations
from typing import Any, Union

from ..models.promotion import PromotionIntegration
from .base import BaseResource

__all__ = ["PromotionIntegrationsResource"]


class PromotionIntegrationsResource(BaseResource):
    """Operations on OrderCloud PromotionIntegrations."""

    async def get(
        self,
    ) -> PromotionIntegration:
        """Retrieve a promotion integration

        Returns:
            The PromotionIntegration object.
        """
        resp = await self._http.get("/integrations/promotion")
        return PromotionIntegration(**resp.json())

    async def save(
        self,
        promotion_integration: Union[PromotionIntegration, dict[str, Any]],
    ) -> PromotionIntegration:
        """Create or update a promotion integration

        Args:
            promotion_integration: A ``PromotionIntegration`` model or dict. Required fields: HashKey.

        Returns:
            The PromotionIntegration object.
        """
        resp = await self._http.put(
            "/integrations/promotion",
            json=self._serialize(promotion_integration),
        )
        return PromotionIntegration(**resp.json())

    async def delete(
        self,
    ) -> None:
        """Delete a promotion integration"""
        await self._http.delete("/integrations/promotion")

    async def patch(
        self,
        partial: dict[str, Any],
    ) -> PromotionIntegration:
        """Partially update a promotion integration

        Args:
            partial: A dict of fields to update.

        Returns:
            The PromotionIntegration object.
        """
        resp = await self._http.patch("/integrations/promotion", json=partial)
        return PromotionIntegration(**resp.json())
