# GENERATED by tools/codegen — DO NOT EDIT
# Source: ordercloud-openapi-v3.json
"""OrderCloud SellerApprovalRules API resource."""

from __future__ import annotations
from typing import Any, Optional, Union

from ..models.approval import SellerApprovalRule
from ..models.shared import ListPage
from .base import BaseResource

__all__ = ["SellerApprovalRulesResource"]


class SellerApprovalRulesResource(BaseResource):
    """Operations on OrderCloud SellerApprovalRules."""

    async def list(
        self,
        *,
        search: Optional[str] = None,
        search_on: Optional[str] = None,
        sort_by: Optional[str] = None,
        page: Optional[int] = None,
        page_size: Optional[int] = None,
        filters: Optional[dict[str, Any]] = None,
    ) -> ListPage[SellerApprovalRule]:
        """List seller approval rules

        Args:
            search: Word or phrase to search for.
            search_on: Comma-delimited list of fields to search on.
            sort_by: Comma-delimited list of fields to sort by.
            page: Page of results to return. When paginating through many items (> page 30), we recommend the "Last ID" method, as outlined in the Advanced Querying documentation.
            page_size: Number of results to return per page.
            filters: An object or dictionary representing key/value pairs to apply as filters. Valid keys are top-level properties of the returned model or 'xp.???'

        Returns:
            A paginated list of SellerApprovalRule objects.
        """
        params = self._build_list_params(
            search=search,
            search_on=search_on,
            sort_by=sort_by,
            page=page,
            page_size=page_size,
            filters=filters,
        )
        resp = await self._http.get("/approvalrules", **params)
        return self._parse_list(resp.json(), SellerApprovalRule)

    async def create(
        self,
        seller_approval_rule: Union[SellerApprovalRule, dict[str, Any]],
    ) -> SellerApprovalRule:
        """Create a seller approval rule

        Args:
            seller_approval_rule: A ``SellerApprovalRule`` model or dict. Required fields: ApprovalType, ApprovingGroupID, RuleExpression.

        Returns:
            The SellerApprovalRule object.
        """
        resp = await self._http.post("/approvalrules", json=self._serialize(seller_approval_rule))
        return SellerApprovalRule(**resp.json())

    async def get(
        self,
        approval_rule_id: str,
    ) -> SellerApprovalRule:
        """Retrieve a seller approval rule

        Args:
            approval_rule_id: ID of the approval rule.

        Returns:
            The SellerApprovalRule object.
        """
        resp = await self._http.get(f"/approvalrules/{approval_rule_id}")
        return SellerApprovalRule(**resp.json())

    async def save(
        self,
        approval_rule_id: str,
        seller_approval_rule: Union[SellerApprovalRule, dict[str, Any]],
    ) -> SellerApprovalRule:
        """Create or update a seller approval rule

        Args:
            approval_rule_id: ID of the approval rule.
            seller_approval_rule: A ``SellerApprovalRule`` model or dict. Required fields: ApprovalType, ApprovingGroupID, RuleExpression.

        Returns:
            The SellerApprovalRule object.
        """
        resp = await self._http.put(
            f"/approvalrules/{approval_rule_id}",
            json=self._serialize(seller_approval_rule),
        )
        return SellerApprovalRule(**resp.json())

    async def delete(
        self,
        approval_rule_id: str,
    ) -> None:
        """Delete a seller approval rule

        Args:
            approval_rule_id: ID of the approval rule.
        """
        await self._http.delete(f"/approvalrules/{approval_rule_id}")

    async def patch(
        self,
        approval_rule_id: str,
        partial: dict[str, Any],
    ) -> SellerApprovalRule:
        """Partially update a seller approval rule

        Args:
            approval_rule_id: ID of the approval rule.
            partial: A dict of fields to update.

        Returns:
            The SellerApprovalRule object.
        """
        resp = await self._http.patch(f"/approvalrules/{approval_rule_id}", json=partial)
        return SellerApprovalRule(**resp.json())
