# GENERATED by tools/codegen — DO NOT EDIT
# Source: ordercloud-openapi-v3.json
"""OrderCloud Shipments API resource."""

from __future__ import annotations
from typing import Any, Optional, Union

from ..models.address import Address
from ..models.shipment import Shipment, ShipmentItem
from ..models.shared import ListPage
from .base import BaseResource

__all__ = ["ShipmentsResource"]


class ShipmentsResource(BaseResource):
    """Operations on OrderCloud Shipments."""

    async def list(
        self,
        *,
        order_id: Optional[str] = None,
        search: Optional[str] = None,
        search_on: Optional[str] = None,
        sort_by: Optional[str] = None,
        page: Optional[int] = None,
        page_size: Optional[int] = None,
        filters: Optional[dict[str, Any]] = None,
    ) -> ListPage[Shipment]:
        """List shipments

        Args:
            order_id: ID of the order.
            search: Word or phrase to search for.
            search_on: Comma-delimited list of fields to search on.
            sort_by: Comma-delimited list of fields to sort by.
            page: Page of results to return. When paginating through many items (> page 30), we recommend the "Last ID" method, as outlined in the Advanced Querying documentation.
            page_size: Number of results to return per page.
            filters: An object or dictionary representing key/value pairs to apply as filters. Valid keys are top-level properties of the returned model or 'xp.???'

        Returns:
            A paginated list of Shipment objects.
        """
        params = self._build_list_params(
            search=search,
            search_on=search_on,
            sort_by=sort_by,
            page=page,
            page_size=page_size,
            filters=filters,
        )
        if order_id is not None:
            params["orderID"] = order_id
        resp = await self._http.get("/shipments", **params)
        return self._parse_list(resp.json(), Shipment)

    async def create(
        self,
        shipment: Union[Shipment, dict[str, Any]],
    ) -> Shipment:
        """Create a shipment

        Args:
            shipment: A ``Shipment`` model or dict.

        Returns:
            The Shipment object.
        """
        resp = await self._http.post("/shipments", json=self._serialize(shipment))
        return Shipment(**resp.json())

    async def get(
        self,
        shipment_id: str,
    ) -> Shipment:
        """Retrieve a shipment

        Args:
            shipment_id: ID of the shipment.

        Returns:
            The Shipment object.
        """
        resp = await self._http.get(f"/shipments/{shipment_id}")
        return Shipment(**resp.json())

    async def save(
        self,
        shipment_id: str,
        shipment: Union[Shipment, dict[str, Any]],
    ) -> Shipment:
        """Create or update a shipment

        Args:
            shipment_id: ID of the shipment.
            shipment: A ``Shipment`` model or dict.

        Returns:
            The Shipment object.
        """
        resp = await self._http.put(
            f"/shipments/{shipment_id}",
            json=self._serialize(shipment),
        )
        return Shipment(**resp.json())

    async def delete(
        self,
        shipment_id: str,
    ) -> None:
        """Delete a shipment

        Args:
            shipment_id: ID of the shipment.
        """
        await self._http.delete(f"/shipments/{shipment_id}")

    async def patch(
        self,
        shipment_id: str,
        partial: dict[str, Any],
    ) -> Shipment:
        """Partially update a shipment

        Args:
            shipment_id: ID of the shipment.
            partial: A dict of fields to update.

        Returns:
            The Shipment object.
        """
        resp = await self._http.patch(f"/shipments/{shipment_id}", json=partial)
        return Shipment(**resp.json())

    async def list_items(
        self,
        shipment_id: str,
        *,
        sort_by: Optional[str] = None,
        page: Optional[int] = None,
        page_size: Optional[int] = None,
        filters: Optional[dict[str, Any]] = None,
    ) -> ListPage[ShipmentItem]:
        """List shipment items

        Args:
            shipment_id: ID of the shipment.
            sort_by: Comma-delimited list of fields to sort by.
            page: Page of results to return. When paginating through many items (> page 30), we recommend the "Last ID" method, as outlined in the Advanced Querying documentation.
            page_size: Number of results to return per page.
            filters: An object or dictionary representing key/value pairs to apply as filters. Valid keys are top-level properties of the returned model or 'xp.???'

        Returns:
            A paginated list of ShipmentItem objects.
        """
        params = self._build_list_params(
            sort_by=sort_by,
            page=page,
            page_size=page_size,
            filters=filters,
        )
        resp = await self._http.get(f"/shipments/{shipment_id}/items", **params)
        return self._parse_list(resp.json(), ShipmentItem)

    async def save_item(
        self,
        shipment_id: str,
        shipment_item: Union[ShipmentItem, dict[str, Any]],
    ) -> ShipmentItem:
        """Create or update a shipment item

        Args:
            shipment_id: ID of the shipment.
            shipment_item: A ``ShipmentItem`` model or dict. Required fields: OrderID, LineItemID, QuantityShipped.

        Returns:
            The ShipmentItem object.
        """
        resp = await self._http.post(
            f"/shipments/{shipment_id}/items", json=self._serialize(shipment_item)
        )
        return ShipmentItem(**resp.json())

    async def get_item(
        self,
        shipment_id: str,
        order_id: str,
        line_item_id: str,
    ) -> ShipmentItem:
        """Retrieve a shipment item

        Args:
            shipment_id: ID of the shipment.
            order_id: ID of the order.
            line_item_id: ID of the line item.

        Returns:
            The ShipmentItem object.
        """
        resp = await self._http.get(f"/shipments/{shipment_id}/items/{order_id}/{line_item_id}")
        return ShipmentItem(**resp.json())

    async def delete_item(
        self,
        shipment_id: str,
        order_id: str,
        line_item_id: str,
    ) -> None:
        """Delete a shipment item

        Args:
            shipment_id: ID of the shipment.
            order_id: ID of the order.
            line_item_id: ID of the line item.
        """
        await self._http.delete(f"/shipments/{shipment_id}/items/{order_id}/{line_item_id}")

    async def set_ship_from_address(
        self,
        shipment_id: str,
        address: Union[Address, dict[str, Any]],
    ) -> Shipment:
        """Set a ship from address

        Args:
            shipment_id: ID of the shipment.
            address: A ``Address`` model or dict. Required fields: Street1, City, Country.

        Returns:
            The Shipment object.
        """
        resp = await self._http.put(
            f"/shipments/{shipment_id}/shipfrom",
            json=self._serialize(address),
        )
        return Shipment(**resp.json())

    async def set_ship_to_address(
        self,
        shipment_id: str,
        address: Union[Address, dict[str, Any]],
    ) -> Shipment:
        """Set a ship to address

        Args:
            shipment_id: ID of the shipment.
            address: A ``Address`` model or dict. Required fields: Street1, City, Country.

        Returns:
            The Shipment object.
        """
        resp = await self._http.put(
            f"/shipments/{shipment_id}/shipto",
            json=self._serialize(address),
        )
        return Shipment(**resp.json())
