# GENERATED by tools/codegen — DO NOT EDIT
# Source: ordercloud-openapi-v3.json
"""OrderCloud SubscriptionIntegrations API resource."""

from __future__ import annotations
from typing import Any, Union

from ..models.subscription import SubscriptionIntegration
from .base import BaseResource

__all__ = ["SubscriptionIntegrationsResource"]


class SubscriptionIntegrationsResource(BaseResource):
    """Operations on OrderCloud SubscriptionIntegrations."""

    async def get(
        self,
    ) -> SubscriptionIntegration:
        """Retrieve a subscription integration

        Returns:
            The SubscriptionIntegration object.
        """
        resp = await self._http.get("/integrations/subscription")
        return SubscriptionIntegration(**resp.json())

    async def save(
        self,
        subscription_integration: Union[SubscriptionIntegration, dict[str, Any]],
    ) -> SubscriptionIntegration:
        """Create or update a subscription integration

        Args:
            subscription_integration: A ``SubscriptionIntegration`` model or dict. Required fields: ApiClientID, HashKey.

        Returns:
            The SubscriptionIntegration object.
        """
        resp = await self._http.put(
            "/integrations/subscription",
            json=self._serialize(subscription_integration),
        )
        return SubscriptionIntegration(**resp.json())

    async def delete(
        self,
    ) -> None:
        """Delete a subscription integration"""
        await self._http.delete("/integrations/subscription")

    async def patch(
        self,
        partial: dict[str, Any],
    ) -> SubscriptionIntegration:
        """Partially update a subscription integration

        Args:
            partial: A dict of fields to update.

        Returns:
            The SubscriptionIntegration object.
        """
        resp = await self._http.patch("/integrations/subscription", json=partial)
        return SubscriptionIntegration(**resp.json())
