# GENERATED by tools/codegen — DO NOT EDIT
# Source: ordercloud-openapi-v3.json
"""OrderCloud Subscriptions API resource."""

from __future__ import annotations
from typing import Any, Optional, Union

from ..models.subscription import Subscription
from ..models.shared import ListPage
from .base import BaseResource

__all__ = ["SubscriptionsResource"]


class SubscriptionsResource(BaseResource):
    """Operations on OrderCloud Subscriptions."""

    async def list(
        self,
        *,
        search: Optional[str] = None,
        search_on: Optional[str] = None,
        sort_by: Optional[str] = None,
        page: Optional[int] = None,
        page_size: Optional[int] = None,
        filters: Optional[dict[str, Any]] = None,
    ) -> ListPage[Subscription]:
        """List subscriptions

        Args:
            search: Word or phrase to search for.
            search_on: Comma-delimited list of fields to search on.
            sort_by: Comma-delimited list of fields to sort by.
            page: Page of results to return. When paginating through many items (> page 30), we recommend the "Last ID" method, as outlined in the Advanced Querying documentation.
            page_size: Number of results to return per page.
            filters: An object or dictionary representing key/value pairs to apply as filters. Valid keys are top-level properties of the returned model or 'xp.???'

        Returns:
            A paginated list of Subscription objects.
        """
        params = self._build_list_params(
            search=search,
            search_on=search_on,
            sort_by=sort_by,
            page=page,
            page_size=page_size,
            filters=filters,
        )
        resp = await self._http.get("/subscriptions", **params)
        return self._parse_list(resp.json(), Subscription)

    async def create(
        self,
        subscription: Union[Subscription, dict[str, Any]],
    ) -> Subscription:
        """Create a subscription

        Args:
            subscription: A ``Subscription`` model or dict. Required fields: Frequency, Interval, NextOrderDate.

        Returns:
            The Subscription object.
        """
        resp = await self._http.post("/subscriptions", json=self._serialize(subscription))
        return Subscription(**resp.json())

    async def get(
        self,
        subscription_id: str,
    ) -> Subscription:
        """Retrieve a subscription

        Args:
            subscription_id: ID of the subscription.

        Returns:
            The Subscription object.
        """
        resp = await self._http.get(f"/subscriptions/{subscription_id}")
        return Subscription(**resp.json())

    async def save(
        self,
        subscription_id: str,
        subscription: Union[Subscription, dict[str, Any]],
    ) -> Subscription:
        """Create or update a subscription

        Args:
            subscription_id: ID of the subscription.
            subscription: A ``Subscription`` model or dict. Required fields: Frequency, Interval, NextOrderDate.

        Returns:
            The Subscription object.
        """
        resp = await self._http.put(
            f"/subscriptions/{subscription_id}",
            json=self._serialize(subscription),
        )
        return Subscription(**resp.json())

    async def delete(
        self,
        subscription_id: str,
    ) -> None:
        """Delete a subscription

        Args:
            subscription_id: ID of the subscription.
        """
        await self._http.delete(f"/subscriptions/{subscription_id}")

    async def patch(
        self,
        subscription_id: str,
        partial: dict[str, Any],
    ) -> Subscription:
        """Partially update a subscription

        Args:
            subscription_id: ID of the subscription.
            partial: A dict of fields to update.

        Returns:
            The Subscription object.
        """
        resp = await self._http.patch(f"/subscriptions/{subscription_id}", json=partial)
        return Subscription(**resp.json())
