# GENERATED by tools/codegen — DO NOT EDIT
# Source: ordercloud-openapi-v3.json
"""OrderCloud Suppliers API resource."""

from __future__ import annotations
from typing import Any, Optional, Union

from ..models.supplier import Supplier, SupplierBuyer
from ..models.shared import ListPage
from .base import BaseResource

__all__ = ["SuppliersResource"]


class SuppliersResource(BaseResource):
    """Operations on OrderCloud Suppliers."""

    async def list(
        self,
        *,
        search: Optional[str] = None,
        search_on: Optional[str] = None,
        sort_by: Optional[str] = None,
        page: Optional[int] = None,
        page_size: Optional[int] = None,
        filters: Optional[dict[str, Any]] = None,
    ) -> ListPage[Supplier]:
        """List suppliers

        Args:
            search: Word or phrase to search for.
            search_on: Comma-delimited list of fields to search on.
            sort_by: Comma-delimited list of fields to sort by.
            page: Page of results to return. When paginating through many items (> page 30), we recommend the "Last ID" method, as outlined in the Advanced Querying documentation.
            page_size: Number of results to return per page.
            filters: An object or dictionary representing key/value pairs to apply as filters. Valid keys are top-level properties of the returned model or 'xp.???'

        Returns:
            A paginated list of Supplier objects.
        """
        params = self._build_list_params(
            search=search,
            search_on=search_on,
            sort_by=sort_by,
            page=page,
            page_size=page_size,
            filters=filters,
        )
        resp = await self._http.get("/suppliers", **params)
        return self._parse_list(resp.json(), Supplier)

    async def create(
        self,
        supplier: Union[Supplier, dict[str, Any]],
    ) -> Supplier:
        """Create a supplier

        Args:
            supplier: A ``Supplier`` model or dict. Required fields: Name.

        Returns:
            The Supplier object.
        """
        resp = await self._http.post("/suppliers", json=self._serialize(supplier))
        return Supplier(**resp.json())

    async def get(
        self,
        supplier_id: str,
    ) -> Supplier:
        """Retrieve a supplier

        Args:
            supplier_id: ID of the supplier.

        Returns:
            The Supplier object.
        """
        resp = await self._http.get(f"/suppliers/{supplier_id}")
        return Supplier(**resp.json())

    async def save(
        self,
        supplier_id: str,
        supplier: Union[Supplier, dict[str, Any]],
    ) -> Supplier:
        """Create or update a supplier

        Args:
            supplier_id: ID of the supplier.
            supplier: A ``Supplier`` model or dict. Required fields: Name.

        Returns:
            The Supplier object.
        """
        resp = await self._http.put(
            f"/suppliers/{supplier_id}",
            json=self._serialize(supplier),
        )
        return Supplier(**resp.json())

    async def delete(
        self,
        supplier_id: str,
    ) -> None:
        """Delete a supplier

        Args:
            supplier_id: ID of the supplier.
        """
        await self._http.delete(f"/suppliers/{supplier_id}")

    async def patch(
        self,
        supplier_id: str,
        partial: dict[str, Any],
    ) -> Supplier:
        """Partially update a supplier

        Args:
            supplier_id: ID of the supplier.
            partial: A dict of fields to update.

        Returns:
            The Supplier object.
        """
        resp = await self._http.patch(f"/suppliers/{supplier_id}", json=partial)
        return Supplier(**resp.json())

    async def list_buyers(
        self,
        supplier_id: str,
        *,
        search: Optional[str] = None,
        search_on: Optional[str] = None,
        sort_by: Optional[str] = None,
        page: Optional[int] = None,
        page_size: Optional[int] = None,
        filters: Optional[dict[str, Any]] = None,
    ) -> ListPage[SupplierBuyer]:
        """List supplier buyers

        Args:
            supplier_id: ID of the supplier.
            search: Word or phrase to search for.
            search_on: Comma-delimited list of fields to search on.
            sort_by: Comma-delimited list of fields to sort by.
            page: Page of results to return. When paginating through many items (> page 30), we recommend the "Last ID" method, as outlined in the Advanced Querying documentation.
            page_size: Number of results to return per page.
            filters: An object or dictionary representing key/value pairs to apply as filters. Valid keys are top-level properties of the returned model or 'xp.???'

        Returns:
            A paginated list of SupplierBuyer objects.
        """
        params = self._build_list_params(
            search=search,
            search_on=search_on,
            sort_by=sort_by,
            page=page,
            page_size=page_size,
            filters=filters,
        )
        resp = await self._http.get(f"/suppliers/{supplier_id}/buyers", **params)
        return self._parse_list(resp.json(), SupplierBuyer)

    async def save_buyer(
        self,
        supplier_id: str,
        buyer_id: str,
    ) -> None:
        """Create or update a supplier buyer

        Args:
            supplier_id: ID of the supplier.
            buyer_id: ID of the buyer.
        """
        await self._http.put(f"/suppliers/{supplier_id}/buyers/{buyer_id}")

    async def delete_buyer(
        self,
        supplier_id: str,
        buyer_id: str,
    ) -> None:
        """Delete a supplier buyer

        Args:
            supplier_id: ID of the supplier.
            buyer_id: ID of the buyer.
        """
        await self._http.delete(f"/suppliers/{supplier_id}/buyers/{buyer_id}")
