# GENERATED by tools/codegen — DO NOT EDIT
# Source: ordercloud-openapi-v3.json
"""OrderCloud Webhooks API resource."""

from __future__ import annotations
from typing import Any, Optional, Union

from ..models.webhook import Webhook
from ..models.shared import ListPage
from .base import BaseResource

__all__ = ["WebhooksResource"]


class WebhooksResource(BaseResource):
    """Operations on OrderCloud Webhooks."""

    async def list(
        self,
        *,
        search: Optional[str] = None,
        search_on: Optional[str] = None,
        sort_by: Optional[str] = None,
        page: Optional[int] = None,
        page_size: Optional[int] = None,
        filters: Optional[dict[str, Any]] = None,
    ) -> ListPage[Webhook]:
        """List webhooks

        Args:
            search: Word or phrase to search for.
            search_on: Comma-delimited list of fields to search on.
            sort_by: Comma-delimited list of fields to sort by.
            page: Page of results to return. When paginating through many items (> page 30), we recommend the "Last ID" method, as outlined in the Advanced Querying documentation.
            page_size: Number of results to return per page.
            filters: An object or dictionary representing key/value pairs to apply as filters. Valid keys are top-level properties of the returned model or 'xp.???'

        Returns:
            A paginated list of Webhook objects.
        """
        params = self._build_list_params(
            search=search,
            search_on=search_on,
            sort_by=sort_by,
            page=page,
            page_size=page_size,
            filters=filters,
        )
        resp = await self._http.get("/webhooks", **params)
        return self._parse_list(resp.json(), Webhook)

    async def create(
        self,
        webhook: Union[Webhook, dict[str, Any]],
    ) -> Webhook:
        """Create a webhook

        Args:
            webhook: A ``Webhook`` model or dict. Required fields: Name.

        Returns:
            The Webhook object.
        """
        resp = await self._http.post("/webhooks", json=self._serialize(webhook))
        return Webhook(**resp.json())

    async def get(
        self,
        webhook_id: str,
    ) -> Webhook:
        """Retrieve a webhook

        Args:
            webhook_id: ID of the webhook.

        Returns:
            The Webhook object.
        """
        resp = await self._http.get(f"/webhooks/{webhook_id}")
        return Webhook(**resp.json())

    async def save(
        self,
        webhook_id: str,
        webhook: Union[Webhook, dict[str, Any]],
    ) -> Webhook:
        """Create or update a webhook

        Args:
            webhook_id: ID of the webhook.
            webhook: A ``Webhook`` model or dict. Required fields: Name.

        Returns:
            The Webhook object.
        """
        resp = await self._http.put(
            f"/webhooks/{webhook_id}",
            json=self._serialize(webhook),
        )
        return Webhook(**resp.json())

    async def delete(
        self,
        webhook_id: str,
    ) -> None:
        """Delete a webhook

        Args:
            webhook_id: ID of the webhook.
        """
        await self._http.delete(f"/webhooks/{webhook_id}")

    async def patch(
        self,
        webhook_id: str,
        partial: dict[str, Any],
    ) -> Webhook:
        """Partially update a webhook

        Args:
            webhook_id: ID of the webhook.
            partial: A dict of fields to update.

        Returns:
            The Webhook object.
        """
        resp = await self._http.patch(f"/webhooks/{webhook_id}", json=partial)
        return Webhook(**resp.json())
