"""Credential-bearing path values never reach the SDK's log lines.

Two layers: a scan of the committed generated resource modules, which fails
if a future generator run emits a credential-bearing path without redaction,
and end-to-end calls through the real generated methods.
"""

from __future__ import annotations

import ast
import logging
from pathlib import Path

import pytest
import respx
from httpx import Response

from ordercloud.errors import OrderCloudError
from ordercloud.http import HttpClient
from ordercloud.resources.forgotten_credentials import ForgottenCredentialsResource
from ordercloud.resources.group_orders import GroupOrdersResource
from ordercloud.resources.me import MeResource
from ordercloud.resources.products import ProductsResource
from tools.codegen.naming import path_param_to_snake
from tools.codegen.sensitivity import (
    NOT_SENSITIVE_PATH_PARAMS,
    REDACTION_MARKER,
    SENSITIVE_PATH_PARAMS,
)

from .conftest import TEST_BASE_URL

RESOURCES_DIR = Path(__file__).resolve().parent.parent / "src" / "ordercloud" / "resources"
GENERATED_HEADER = "# GENERATED by tools/codegen"
HTTP_METHODS = {"get", "post", "put", "patch", "delete", "request"}

# Python names a generated path may interpolate into a logged form.  A name
# that is also the snake_case form of a sensitive spec name is not cleared.
CLEARED_NAMES = {path_param_to_snake(n) for n in NOT_SENSITIVE_PATH_PARAMS} - {
    path_param_to_snake(n) for n in SENSITIVE_PATH_PARAMS
}


# ---------------------------------------------------------------------------
# Generated-code scan
# ---------------------------------------------------------------------------


def _interpolated_names(node: ast.JoinedStr) -> list[str] | None:
    """Names interpolated by an f-string, or ``None`` if any part is not a bare name."""
    names = []
    for value in node.values:
        if isinstance(value, ast.FormattedValue):
            if (
                not isinstance(value.value, ast.Name)
                or value.conversion != -1
                or value.format_spec is not None
            ):
                return None
            names.append(value.value.id)
    return names


def _literal_text(node: ast.JoinedStr) -> str:
    return "".join(
        v.value for v in node.values if isinstance(v, ast.Constant) and isinstance(v.value, str)
    )


def _check_logged_string(node: ast.expr, what: str) -> str | None:
    """Return a problem description if ``node`` may log anything but cleared names."""
    if isinstance(node, ast.Constant) and isinstance(node.value, str):
        return None
    if isinstance(node, ast.JoinedStr):
        names = _interpolated_names(node)
        if names is None:
            return f"{what} interpolates something other than a bare name"
        uncleared = sorted(set(names) - CLEARED_NAMES)
        if uncleared:
            return f"{what} interpolates uncleared names {uncleared}"
        return None
    return f"{what} is a {type(node).__name__}, not a string literal or f-string"


def _check_path_arg(node: ast.expr) -> tuple[str, str | None]:
    """Classify an HTTP call's path argument: ``(kind, problem or None)``."""
    if isinstance(node, ast.Call):
        if not (isinstance(node.func, ast.Name) and node.func.id == "SensitivePath"):
            return "call", "path is a call to something other than SensitivePath"
        kwargs = {k.arg: k.value for k in node.keywords}
        if node.args or set(kwargs) != {"wire", "log_form"}:
            return "sensitive", "SensitivePath must be built with wire= and log_form= only"
        wire, log_form = kwargs["wire"], kwargs["log_form"]
        if not isinstance(wire, (ast.JoinedStr, ast.Constant)):
            return "sensitive", "SensitivePath wire is not a string literal or f-string"
        problem = _check_logged_string(log_form, "SensitivePath log_form")
        if problem:
            return "sensitive", problem
        text = log_form.value if isinstance(log_form, ast.Constant) else _literal_text(log_form)
        if REDACTION_MARKER not in text:
            return "sensitive", "SensitivePath log_form does not contain the redaction marker"
        return "sensitive", None
    return "plain", _check_logged_string(node, "path")


def _is_http_call(node: ast.AST) -> bool:
    """Whether ``node`` is ``self._http.<method>(...)``."""
    return (
        isinstance(node, ast.Call)
        and isinstance(node.func, ast.Attribute)
        and node.func.attr in HTTP_METHODS
        and isinstance(node.func.value, ast.Attribute)
        and node.func.value.attr == "_http"
        and isinstance(node.func.value.value, ast.Name)
        and node.func.value.value.id == "self"
    )


class TestGeneratedResourceScan:
    def test_every_logged_path_is_redacted_or_cleared(self):
        problems: list[str] = []
        modules = 0
        methods = 0
        calls = 0
        sensitive_by_module: dict[str, int] = {}

        for path in sorted(RESOURCES_DIR.glob("*.py")):
            source = path.read_text(encoding="utf-8")
            if not source.startswith(GENERATED_HEADER):
                continue
            modules += 1
            tree = ast.parse(source)
            for cls in (n for n in tree.body if isinstance(n, ast.ClassDef)):
                methods += sum(isinstance(n, ast.AsyncFunctionDef) for n in cls.body)
            for node in ast.walk(tree):
                if not _is_http_call(node):
                    continue
                calls += 1
                where = f"{path.name}:{node.lineno}"
                if not node.args:
                    problems.append(f"{where}: HTTP call without a positional path")
                    continue
                kind, problem = _check_path_arg(node.args[0])
                if problem:
                    problems.append(f"{where}: {problem}")
                if kind == "sensitive":
                    sensitive_by_module[path.name] = sensitive_by_module.get(path.name, 0) + 1

        assert problems == []
        # Not vacuous: the scan saw the generated code, one HTTP call per method,
        # and the known credential-bearing routes in their redacted form.
        assert modules >= 60
        assert methods > 600
        assert calls == methods
        assert sensitive_by_module.get("forgotten_credentials.py", 0) >= 1
        assert sensitive_by_module.get("group_orders.py", 0) >= 1
        assert sensitive_by_module.get("me.py", 0) >= 8

    def test_scan_rejects_an_unredacted_credential_path(self):
        """The checker itself fails on the shape the redaction replaced."""
        call = ast.parse('self._http.put(f"/password/reset/{verification_code}")').body[0]
        assert isinstance(call, ast.Expr) and _is_http_call(call.value)
        _, problem = _check_path_arg(call.value.args[0])
        assert problem is not None and "verification_code" in problem

    def test_scan_rejects_a_sensitive_path_logging_the_secret(self):
        expr = ast.parse(
            'SensitivePath(wire=f"/grouporders/{invitation_id}/token", '
            'log_form=f"/grouporders/{invitation_id}/token")'
        ).body[0]
        assert isinstance(expr, ast.Expr)
        _, problem = _check_path_arg(expr.value)
        assert problem is not None and "invitation_id" in problem


# ---------------------------------------------------------------------------
# End to end through the generated methods
# ---------------------------------------------------------------------------

CODE = "vc-7Q2X9-reset"
INVITE = "inv-K81Z-group"
ANON = "anon-token-W3T5"


def _ordercloud_messages(caplog: pytest.LogCaptureFixture) -> list[str]:
    return [r.getMessage() for r in caplog.records if r.name.startswith("ordercloud")]


def _leaks(caplog: pytest.LogCaptureFixture, secret: str) -> list[str]:
    return [
        f"{r.getMessage()} {r.msg!r} {r.args!r}"
        for r in caplog.records
        if r.name.startswith("ordercloud") and secret in f"{r.getMessage()} {r.msg!r} {r.args!r}"
    ]


class TestEndToEndRedaction:
    @respx.mock
    async def test_password_reset_logs_marker_not_code(
        self, http_client: HttpClient, caplog: pytest.LogCaptureFixture
    ):
        route = respx.put(f"{TEST_BASE_URL}/password/reset/{CODE}").mock(return_value=Response(204))
        with caplog.at_level(logging.DEBUG, logger="ordercloud"):
            await ForgottenCredentialsResource(http_client).reset_password_by_verification_code(
                CODE, {"ClientID": "c", "Username": "u", "Password": "p"}
            )
        assert route.call_count == 1
        messages = _ordercloud_messages(caplog)
        assert "Request: PUT /password/reset/***" in messages
        assert "Response: PUT /password/reset/*** 204" in messages
        assert _leaks(caplog, CODE) == []

    @respx.mock
    async def test_group_order_token_logs_marker_not_invitation(
        self, http_client: HttpClient, caplog: pytest.LogCaptureFixture
    ):
        route = respx.post(f"{TEST_BASE_URL}/grouporders/{INVITE}/token").mock(
            return_value=Response(200, json={"access_token": "tok", "expires_in": 600})
        )
        with caplog.at_level(logging.DEBUG, logger="ordercloud"):
            token = await GroupOrdersResource(http_client).get_token(INVITE)
        assert route.call_count == 1
        assert token.access_token == "tok"
        assert "Request: POST /grouporders/***/token" in _ordercloud_messages(caplog)
        assert _leaks(caplog, INVITE) == []

    @respx.mock
    async def test_collection_invitation_keeps_collection_id_redacts_invitation(
        self, http_client: HttpClient, caplog: pytest.LogCaptureFixture
    ):
        route = respx.post(
            f"{TEST_BASE_URL}/me/productcollections/col-1/invitations/accept/{INVITE}"
        ).mock(return_value=Response(204))
        with caplog.at_level(logging.DEBUG, logger="ordercloud"):
            await MeResource(http_client).accept_product_collection_invitation("col-1", INVITE)
        assert route.call_count == 1
        assert (
            "Request: POST /me/productcollections/col-1/invitations/accept/***"
            in _ordercloud_messages(caplog)
        )
        assert _leaks(caplog, INVITE) == []

    @respx.mock
    async def test_ordinary_path_is_logged_unchanged(
        self, http_client: HttpClient, caplog: pytest.LogCaptureFixture
    ):
        respx.get(f"{TEST_BASE_URL}/products/p-123").mock(
            return_value=Response(200, json={"ID": "p-123"})
        )
        with caplog.at_level(logging.DEBUG, logger="ordercloud"):
            await ProductsResource(http_client).get("p-123")
        messages = _ordercloud_messages(caplog)
        assert "Request: GET /products/p-123" in messages
        assert "Response: GET /products/p-123 200" in messages

    @respx.mock
    async def test_query_parameter_token_is_not_logged(
        self, http_client: HttpClient, caplog: pytest.LogCaptureFixture
    ):
        route = respx.put(f"{TEST_BASE_URL}/me/orders").mock(return_value=Response(204))
        with caplog.at_level(logging.DEBUG, logger="ordercloud"):
            await MeResource(http_client).transfer_anon_user_order(anon_user_token=ANON)
        # The token really was sent, so the absence below is meaningful.
        assert route.calls[0].request.url.params["anonUserToken"] == ANON
        assert "Request: PUT /me/orders" in _ordercloud_messages(caplog)
        assert _leaks(caplog, ANON) == []

    @respx.mock
    async def test_error_on_reset_route_does_not_carry_code(
        self, http_client: HttpClient, caplog: pytest.LogCaptureFixture
    ):
        respx.put(f"{TEST_BASE_URL}/password/reset/{CODE}").mock(
            return_value=Response(
                400,
                json={
                    "Errors": [{"ErrorCode": "NotFound", "Message": "Invalid verification code"}]
                },
            )
        )
        with caplog.at_level(logging.DEBUG, logger="ordercloud"):
            with pytest.raises(OrderCloudError) as exc_info:
                await ForgottenCredentialsResource(http_client).reset_password_by_verification_code(
                    CODE, {"ClientID": "c", "Username": "u"}
                )
        assert exc_info.value.status_code == 400
        assert CODE not in str(exc_info.value)
        assert _leaks(caplog, CODE) == []
