# GENERATED by tools/codegen — DO NOT EDIT
# Source: ordercloud-openapi-v3.json
"""OrderCloud ApprovalStatus and related models."""

from __future__ import annotations
from enum import Enum
from typing import Any, Optional

from .shared import OrderCloudModel

__all__ = ["ApprovalStatus", "ApprovalType", "ApprovalRule", "SellerApprovalRule"]


class ApprovalStatus(str, Enum):
    """"""

    Pending = "Pending"
    Approved = "Approved"
    Declined = "Declined"


class ApprovalType(str, Enum):
    """"""

    Order = "Order"
    OrderReturn = "OrderReturn"


class ApprovalRule(OrderCloudModel):
    """An OrderCloud ApprovalRule.

    Attributes:
        ID:
        Name:
        Description:
        ApprovingGroupID:
        RuleExpression: The expression evaluated to determine an order requires approval. See rules engine documentation for formatting details.
        xp:
    """

    ID: Optional[str] = None
    Name: Optional[str] = None
    Description: Optional[str] = None
    ApprovingGroupID: Optional[str] = None
    RuleExpression: Optional[str] = None
    xp: Optional[dict[str, Any]] = None


class SellerApprovalRule(OrderCloudModel):
    """An OrderCloud SellerApprovalRule.

    Attributes:
        OwnerID: ID of the organization who owns the rule. Only the marketplace owner can write a value other than their own organization ID. The value is used to look up the ApprovingGroupID.
        ApprovalType: OrderReturn is the only ApprovalType supported currently.
        ID:
        Name:
        Description:
        ApprovingGroupID:
        RuleExpression: The expression evaluated to determine an order requires approval. See rules engine documentation for formatting details.
        xp:
    """

    OwnerID: Optional[str] = None
    ApprovalType: Optional[_ApprovalType] = None
    ID: Optional[str] = None
    Name: Optional[str] = None
    Description: Optional[str] = None
    ApprovingGroupID: Optional[str] = None
    RuleExpression: Optional[str] = None
    xp: Optional[dict[str, Any]] = None


_ApprovalType = ApprovalType
