# GENERATED by tools/codegen — DO NOT EDIT
# Source: ordercloud-openapi-v3.json
"""OrderCloud ApprovalStatus and related models."""

from __future__ import annotations
from typing import Generic, Optional
from pydantic import Field

from .shared import OrderCloudEnum, OrderCloudModel, XP

__all__ = ["ApprovalStatus", "ApprovalType", "ApprovalRule", "SellerApprovalRule"]


class ApprovalStatus(OrderCloudEnum):
    """"""

    Pending = "Pending"
    Approved = "Approved"
    Declined = "Declined"


class ApprovalType(OrderCloudEnum):
    """"""

    Order = "Order"
    OrderReturn = "OrderReturn"


class ApprovalRule(OrderCloudModel, Generic[XP]):
    """An OrderCloud ApprovalRule.

    Attributes:
        id:
        name:
        description:
        approving_group_id:
        rule_expression: The expression evaluated to determine an order requires approval. See rules engine documentation for formatting details.
        xp:
    """

    id: Optional[str] = Field(None, alias="ID")
    name: Optional[str] = Field(None, alias="Name")
    description: Optional[str] = Field(None, alias="Description")
    approving_group_id: Optional[str] = Field(None, alias="ApprovingGroupID")
    rule_expression: Optional[str] = Field(None, alias="RuleExpression")
    xp: Optional[XP] = Field(None, alias="xp")


class SellerApprovalRule(OrderCloudModel, Generic[XP]):
    """An OrderCloud SellerApprovalRule.

    Attributes:
        owner_id: ID of the organization who owns the rule. Only the marketplace owner can write a value other than their own organization ID. The value is used to look up the ApprovingGroupID.
        approval_type: OrderReturn is the only ApprovalType supported currently.
        id:
        name:
        description:
        approving_group_id:
        rule_expression: The expression evaluated to determine an order requires approval. See rules engine documentation for formatting details.
        xp:
    """

    owner_id: Optional[str] = Field(None, alias="OwnerID")
    approval_type: Optional[_ApprovalType] = Field(None, alias="ApprovalType")
    id: Optional[str] = Field(None, alias="ID")
    name: Optional[str] = Field(None, alias="Name")
    description: Optional[str] = Field(None, alias="Description")
    approving_group_id: Optional[str] = Field(None, alias="ApprovingGroupID")
    rule_expression: Optional[str] = Field(None, alias="RuleExpression")
    xp: Optional[XP] = Field(None, alias="xp")


_ApprovalType = ApprovalType
