# GENERATED by tools/codegen — DO NOT EDIT
# Source: ordercloud-openapi-v3.json
"""OrderCloud AccessToken and related models."""

from __future__ import annotations
from typing import Optional

from .shared import OrderCloudModel
from .misc import ApiRole

__all__ = [
    "AccessToken",
    "AccessTokenBasic",
    "ImpersonateTokenRequest",
    "OneTimePasswordRequest",
    "PasswordReset",
    "PasswordResetRequest",
    "TokenPasswordReset",
]


class AccessToken(OrderCloudModel):
    """An OrderCloud AccessToken.

    Attributes:
        access_token:
        expires_in:
        token_type:
        refresh_token:
    """

    access_token: Optional[str] = None
    expires_in: Optional[int] = None
    token_type: Optional[str] = None
    refresh_token: Optional[str] = None


class AccessTokenBasic(OrderCloudModel):
    """An OrderCloud AccessTokenBasic.

    Attributes:
        access_token:
    """

    access_token: Optional[str] = None


class ImpersonateTokenRequest(OrderCloudModel):
    """An OrderCloud ImpersonateTokenRequest.

    Attributes:
        ClientID:
        Roles:
        CustomRoles:
    """

    ClientID: Optional[str] = None
    Roles: Optional[list[ApiRole]] = None
    CustomRoles: Optional[list[str]] = None


class OneTimePasswordRequest(OrderCloudModel):
    """An OrderCloud OneTimePasswordRequest.

    Attributes:
        ClientID:
        Username:
        Email:
    """

    ClientID: Optional[str] = None
    Username: Optional[str] = None
    Email: Optional[str] = None


class PasswordReset(OrderCloudModel):
    """An OrderCloud PasswordReset.

    Attributes:
        ClientID:
        Username:
        Password:
    """

    ClientID: Optional[str] = None
    Username: Optional[str] = None
    Password: Optional[str] = None


class PasswordResetRequest(OrderCloudModel):
    """An OrderCloud PasswordResetRequest.

    Attributes:
        ClientID:
        Email:
        Username:
        URL:
    """

    ClientID: Optional[str] = None
    Email: Optional[str] = None
    Username: Optional[str] = None
    URL: Optional[str] = None


class TokenPasswordReset(OrderCloudModel):
    """An OrderCloud TokenPasswordReset.

    Attributes:
        NewPassword:
    """

    NewPassword: Optional[str] = None
