# GENERATED by tools/codegen — DO NOT EDIT
# Source: ordercloud-openapi-v3.json
"""OrderCloud AccessToken and related models."""

from __future__ import annotations
from typing import Optional
from pydantic import Field

from .shared import OrderCloudModel
from .misc import ApiRole

__all__ = [
    "AccessToken",
    "AccessTokenBasic",
    "ImpersonateTokenRequest",
    "OneTimePasswordRequest",
    "PasswordReset",
    "PasswordResetRequest",
    "TokenPasswordReset",
]


class AccessToken(OrderCloudModel):
    """An OrderCloud AccessToken.

    Attributes:
        access_token:
        expires_in:
        token_type:
        refresh_token:
    """

    access_token: Optional[str] = Field(None, alias="access_token")
    expires_in: Optional[int] = Field(None, alias="expires_in")
    token_type: Optional[str] = Field(None, alias="token_type")
    refresh_token: Optional[str] = Field(None, alias="refresh_token")


class AccessTokenBasic(OrderCloudModel):
    """An OrderCloud AccessTokenBasic.

    Attributes:
        access_token:
    """

    access_token: Optional[str] = Field(None, alias="access_token")


class ImpersonateTokenRequest(OrderCloudModel):
    """An OrderCloud ImpersonateTokenRequest.

    Attributes:
        client_id:
        roles:
        custom_roles:
    """

    client_id: Optional[str] = Field(None, alias="ClientID")
    roles: Optional[list[ApiRole]] = Field(None, alias="Roles")
    custom_roles: Optional[list[str]] = Field(None, alias="CustomRoles")


class OneTimePasswordRequest(OrderCloudModel):
    """An OrderCloud OneTimePasswordRequest.

    Attributes:
        client_id:
        username:
        email:
    """

    client_id: Optional[str] = Field(None, alias="ClientID")
    username: Optional[str] = Field(None, alias="Username")
    email: Optional[str] = Field(None, alias="Email")


class PasswordReset(OrderCloudModel):
    """An OrderCloud PasswordReset.

    Attributes:
        client_id:
        username:
        password:
    """

    client_id: Optional[str] = Field(None, alias="ClientID")
    username: Optional[str] = Field(None, alias="Username")
    password: Optional[str] = Field(None, alias="Password")


class PasswordResetRequest(OrderCloudModel):
    """An OrderCloud PasswordResetRequest.

    Attributes:
        client_id:
        email:
        username:
        url:
    """

    client_id: Optional[str] = Field(None, alias="ClientID")
    email: Optional[str] = Field(None, alias="Email")
    username: Optional[str] = Field(None, alias="Username")
    url: Optional[str] = Field(None, alias="URL")


class TokenPasswordReset(OrderCloudModel):
    """An OrderCloud TokenPasswordReset.

    Attributes:
        new_password:
    """

    new_password: Optional[str] = Field(None, alias="NewPassword")
