# GENERATED by tools/codegen — DO NOT EDIT
# Source: ordercloud-openapi-v3.json
"""OrderCloud Catalog models."""

from __future__ import annotations
from typing import Any, Optional

from .shared import OrderCloudModel

__all__ = ["Catalog"]


class Catalog(OrderCloudModel):
    """An OrderCloud Catalog.

    Attributes:
        ID:
        OwnerID: ID of the organization that owns the catalog. Only the marketplace owner can override the OwnerID on create.
        Name:
        Description:
        Active: Categories and products within to this catalog will not be visible to buyer users if false.
        CategoryCount:  (read-only)
        xp:
    """

    ID: Optional[str] = None
    OwnerID: Optional[str] = None
    Name: Optional[str] = None
    Description: Optional[str] = None
    Active: Optional[bool] = None
    CategoryCount: int = 0
    xp: Optional[dict[str, Any]] = None
