# GENERATED by tools/codegen — DO NOT EDIT
# Source: ordercloud-openapi-v3.json
"""OrderCloud Category models."""

from __future__ import annotations
from typing import Any, Optional

from .shared import OrderCloudModel

__all__ = ["Category"]


class Category(OrderCloudModel):
    """An OrderCloud Category.

    Attributes:
        ID:
        Name:
        Description:
        ListOrder: Order that the category appears within its parent or catalog (if root level).
        Active: If false, buyers cannot see this category or any categories or products under it.
        ParentID: ID of the parent category.
        ChildCount: Number of categories that are *immediate* children of this category. (read-only)
        xp:
    """

    ID: Optional[str] = None
    Name: Optional[str] = None
    Description: Optional[str] = None
    ListOrder: Optional[int] = None
    Active: Optional[bool] = None
    ParentID: Optional[str] = None
    ChildCount: int = 0
    xp: Optional[dict[str, Any]] = None
