# GENERATED by tools/codegen — DO NOT EDIT
# Source: ordercloud-openapi-v3.json
"""OrderCloud Category models."""

from __future__ import annotations
from typing import Generic, Optional
from pydantic import Field

from .shared import OrderCloudModel, XP

__all__ = ["Category"]


class Category(OrderCloudModel, Generic[XP]):
    """An OrderCloud Category.

    Attributes:
        id:
        name:
        description:
        list_order: Order that the category appears within its parent or catalog (if root level).
        active: If false, buyers cannot see this category or any categories or products under it.
        parent_id: ID of the parent category.
        child_count: Number of categories that are *immediate* children of this category. (read-only)
        xp:
    """

    id: Optional[str] = Field(None, alias="ID")
    name: Optional[str] = Field(None, alias="Name")
    description: Optional[str] = Field(None, alias="Description")
    list_order: Optional[int] = Field(None, alias="ListOrder")
    active: Optional[bool] = Field(None, alias="Active")
    parent_id: Optional[str] = Field(None, alias="ParentID")
    child_count: int = Field(0, alias="ChildCount")
    xp: Optional[XP] = Field(None, alias="xp")
