# GENERATED by tools/codegen — DO NOT EDIT
# Source: ordercloud-openapi-v3.json
"""OrderCloud CostCenter models."""

from __future__ import annotations
from typing import Generic, Optional

from .shared import OrderCloudModel, XP

__all__ = ["CostCenter"]


class CostCenter(OrderCloudModel, Generic[XP]):
    """An OrderCloud CostCenter.

    Attributes:
        ID:
        Name:
        Description:
        xp:
    """

    ID: Optional[str] = None
    Name: Optional[str] = None
    Description: Optional[str] = None
    xp: Optional[XP] = None
