# GENERATED by tools/codegen — DO NOT EDIT
# Source: ordercloud-openapi-v3.json
"""OrderCloud CreditCard models."""

from __future__ import annotations
from typing import Any, Optional

from .shared import OrderCloudModel

__all__ = ["CreditCard"]


class CreditCard(OrderCloudModel):
    """An OrderCloud CreditCard.

    Attributes:
        ID:
        Token: Token provided by the credit card processor used to reference the card with that processor.
        DateCreated:  (read-only)
        CardType:
        PartialAccountNumber:
        CardholderName:
        ExpirationDate:
        xp:
    """

    ID: Optional[str] = None
    Token: Optional[str] = None
    DateCreated: Optional[str] = None
    CardType: Optional[str] = None
    PartialAccountNumber: Optional[str] = None
    CardholderName: Optional[str] = None
    ExpirationDate: Optional[str] = None
    xp: Optional[dict[str, Any]] = None
