# GENERATED by tools/codegen — DO NOT EDIT
# Source: ordercloud-openapi-v3.json
"""OrderCloud KafkaConfig and related models."""

from __future__ import annotations
from typing import Any, Optional

from .shared import OrderCloudModel
from .message_sender import MessageSenderConfig

__all__ = [
    "KafkaConfig",
    "HttpConfig",
    "EventHubConfig",
    "AzureBlobConfig",
    "AzureTableConfig",
    "CosmosDbConfig",
    "MailchimpConfig",
    "ContentHubConfig",
    "SearchIngestionContent",
    "SearchIngestionHttpContent",
    "SearchIngestion",
    "DeliveryTargets",
    "DeliveryConfig",
    "SendEvent",
    "DiscoverEvent",
    "ErrorConfig",
]


class KafkaConfig(OrderCloudModel):
    """An OrderCloud KafkaConfig.

    Attributes:
        BootstrapServers:
        SaslUsername:
        SaslPassword:
        Topic:
    """

    BootstrapServers: Optional[str] = None
    SaslUsername: Optional[str] = None
    SaslPassword: Optional[str] = None
    Topic: Optional[str] = None


class HttpConfig(OrderCloudModel):
    """An OrderCloud HttpConfig.

    Attributes:
        Endpoint:
        Secret:
        CustomAuthHeaderName:
        CustomAuthHeaderValue:
    """

    Endpoint: Optional[str] = None
    Secret: Optional[str] = None
    CustomAuthHeaderName: Optional[str] = None
    CustomAuthHeaderValue: Optional[str] = None


class EventHubConfig(OrderCloudModel):
    """An OrderCloud EventHubConfig.

    Attributes:
        EventHubName:
        ConnectionString:
    """

    EventHubName: Optional[str] = None
    ConnectionString: Optional[str] = None


class AzureBlobConfig(OrderCloudModel):
    """An OrderCloud AzureBlobConfig.

    Attributes:
        ConnectionString: Storage account connection string.
        OverrideContainerName:
    """

    ConnectionString: Optional[str] = None
    OverrideContainerName: Optional[str] = None


class AzureTableConfig(OrderCloudModel):
    """An OrderCloud AzureTableConfig.

    Attributes:
        ConnectionString: Storage account connection string.
        OverrideTableName:
    """

    ConnectionString: Optional[str] = None
    OverrideTableName: Optional[str] = None


class CosmosDbConfig(OrderCloudModel):
    """An OrderCloud CosmosDbConfig.

    Attributes:
        ConnectionString: Storage account connection string.
        OverrideDatabaseName:
    """

    ConnectionString: Optional[str] = None
    OverrideDatabaseName: Optional[str] = None


class MailchimpConfig(OrderCloudModel):
    """An OrderCloud MailchimpConfig.

    Attributes:
        ApiKey: The Mailchimp API key. If this property is not set, the default OrderCloud Mailchimp instance is used. The default instance is intended for test purposes only.
    """

    ApiKey: Optional[str] = None


class ContentHubConfig(OrderCloudModel):
    """An OrderCloud ContentHubConfig.

    Attributes:
        ApiKey:
        Endpoint:
        TargetSchemaName:
        ConfigData: Any custom property mapping should be included here.
    """

    ApiKey: Optional[str] = None
    Endpoint: Optional[str] = None
    TargetSchemaName: Optional[str] = None
    ConfigData: Optional[dict[str, Any]] = None


class SearchIngestionContent(OrderCloudModel):
    """An OrderCloud SearchIngestionContent.

    Attributes:
        Locales: Supported search ingestion locales.
        Http:
    """

    Locales: Optional[list[str]] = None
    Http: Optional[SearchIngestionHttpContent] = None


class SearchIngestionHttpContent(OrderCloudModel):
    """An OrderCloud SearchIngestionHttpContent.

    Attributes:
        Endpoint:
        CustomAuthHeaderName: Security feature that allows your middleware to verify the digital signature in the request header to ensure you only accept trusted data.
        CustomAuthHeaderValue: The header value that can be passed to your middleware.
    """

    Endpoint: Optional[str] = None
    CustomAuthHeaderName: Optional[str] = None
    CustomAuthHeaderValue: Optional[str] = None


class SearchIngestion(OrderCloudModel):
    """An OrderCloud SearchIngestion.

    Attributes:
        Domain:
        Source:
        Endpoint:
        Entity:
        ApiKey:
        Content:
    """

    Domain: Optional[str] = None
    Source: Optional[str] = None
    Endpoint: Optional[str] = None
    Entity: Optional[str] = None
    ApiKey: Optional[str] = None
    Content: Optional[SearchIngestionContent] = None


class DeliveryTargets(OrderCloudModel):
    """An OrderCloud DeliveryTargets.

    Attributes:
        Kafka:
        Http:
        SearchIngestion:
        SendEvent:
        DiscoverEvent:
        EventHub:
        AzureBlob:
        AzureTable:
        CosmosDb:
        Mailchimp:
        MessageSender:
        ContentHub:
    """

    Kafka: Optional[KafkaConfig] = None
    Http: Optional[HttpConfig] = None
    SearchIngestion: Optional[_SearchIngestion] = None
    SendEvent: Optional[_SendEvent] = None
    DiscoverEvent: Optional[_DiscoverEvent] = None
    EventHub: Optional[EventHubConfig] = None
    AzureBlob: Optional[AzureBlobConfig] = None
    AzureTable: Optional[AzureTableConfig] = None
    CosmosDb: Optional[CosmosDbConfig] = None
    Mailchimp: Optional[MailchimpConfig] = None
    MessageSender: Optional[MessageSenderConfig] = None
    ContentHub: Optional[ContentHubConfig] = None


class DeliveryConfig(OrderCloudModel):
    """An OrderCloud DeliveryConfig.

    Attributes:
        ID:
        Name:
        Enabled:
        DeliveryTargets:
    """

    ID: Optional[str] = None
    Name: Optional[str] = None
    Enabled: Optional[bool] = None
    DeliveryTargets: Optional[_DeliveryTargets] = None


class SendEvent(OrderCloudModel):
    """An OrderCloud SendEvent.

    Attributes:
        SiteID:
        ServiceEndpoint:
    """

    SiteID: Optional[str] = None
    ServiceEndpoint: Optional[str] = None


class DiscoverEvent(OrderCloudModel):
    """An OrderCloud DiscoverEvent.

    Attributes:
        ClientID:
        ApiKey:
        ServiceEndpoint:
    """

    ClientID: Optional[str] = None
    ApiKey: Optional[str] = None
    ServiceEndpoint: Optional[str] = None


class ErrorConfig(OrderCloudModel):
    """An OrderCloud ErrorConfig.

    Attributes:
        DeliveryConfigID:
    """

    DeliveryConfigID: Optional[str] = None


_SearchIngestion = SearchIngestion


_SendEvent = SendEvent


_DiscoverEvent = DiscoverEvent


_DeliveryTargets = DeliveryTargets
