# GENERATED by tools/codegen — DO NOT EDIT
# Source: ordercloud-openapi-v3.json
"""OrderCloud DiscountBreak, DiscountedPrices, Discount models."""

from __future__ import annotations
from typing import Generic, Optional

from .shared import OrderCloudModel, XP

__all__ = ["DiscountBreak", "DiscountedPrices", "Discount"]


class DiscountBreak(OrderCloudModel):
    """An OrderCloud DiscountBreak.

    Attributes:
        Quantity: Minimum quantity required for this discount tier.
        Amount: Percentage discount (e.g., 10.5 for 10.5% off). Must be between 0 and 100.
    """

    Quantity: Optional[int] = None
    Amount: Optional[float] = None


class DiscountedPrices(OrderCloudModel):
    """An OrderCloud DiscountedPrices.

    Attributes:
        Price: Discounted price per unit.
        SalePrice: Discounted sale price per unit.
        SubscriptionPrice: Discounted subscription price per unit.
        BundlePrice: Discounted bundle price per unit.
    """

    Price: Optional[float] = None
    SalePrice: Optional[float] = None
    SubscriptionPrice: Optional[float] = None
    BundlePrice: Optional[float] = None


class Discount(OrderCloudModel, Generic[XP]):
    """An OrderCloud Discount.

    Attributes:
        ID:
        Description:
        DiscountBreaks: Quantity-based percentage discount tiers. Each tier specifies a minimum quantity and percentage discount amount.
        ProductFilter:
        CatalogID:
        CategoryID:
        ProductID:
        xp:
    """

    ID: Optional[str] = None
    Description: Optional[str] = None
    DiscountBreaks: Optional[list[DiscountBreak]] = None
    ProductFilter: Optional[str] = None
    CatalogID: Optional[str] = None
    CategoryID: Optional[str] = None
    ProductID: Optional[str] = None
    xp: Optional[XP] = None
