# GENERATED by tools/codegen — DO NOT EDIT
# Source: ordercloud-openapi-v3.json
"""OrderCloud InventoryIntegration, InventoryRecord models."""

from __future__ import annotations
from typing import Any, Optional

from .shared import OrderCloudModel
from .address import Address

__all__ = ["InventoryIntegration", "InventoryRecord"]
_Address = Address


class InventoryIntegration(OrderCloudModel):
    """An OrderCloud InventoryIntegration.

    Attributes:
        DeliveryConfigID:
        LimitNotifications: When true, events will only fire when QuantityAvailable changes in the following ways: is equal to or less than 0, increases from 0 or less than 0 to a positive number, is equal to or less than NotificationPoint, increases from a number equal to or less than the NotificationPoint to a number greater than the NotificationPoint.
    """

    DeliveryConfigID: Optional[str] = None
    LimitNotifications: Optional[bool] = None


class InventoryRecord(OrderCloudModel):
    """An OrderCloud InventoryRecord.

    Attributes:
        ID:
        OwnerID:
        AllowAllBuyers: Allow inventory record to be used by all buyers without creating explicit assignments.
        Address:  (read-only)
        AddressID: AddressID is required because an inventory record represents a location where physical inventory for a given product exists.
        OrderCanExceed:
        QuantityAvailable:
        NotificationPoint:
        LastUpdated:  (read-only)
        xp:
    """

    ID: Optional[str] = None
    OwnerID: Optional[str] = None
    AllowAllBuyers: bool = True
    Address: Optional[_Address] = None
    AddressID: Optional[str] = None
    OrderCanExceed: Optional[bool] = None
    QuantityAvailable: Optional[int] = None
    NotificationPoint: Optional[int] = None
    LastUpdated: Optional[str] = None
    xp: Optional[dict[str, Any]] = None
