# GENERATED by tools/codegen — DO NOT EDIT
# Source: ordercloud-openapi-v3.json
"""OrderCloud InventoryIntegration, InventoryRecord models."""

from __future__ import annotations
from typing import Generic, Optional
from pydantic import Field

from .shared import OrderCloudModel, XP
from .address import Address

__all__ = ["InventoryIntegration", "InventoryRecord"]
_Address = Address


class InventoryIntegration(OrderCloudModel):
    """An OrderCloud InventoryIntegration.

    Attributes:
        delivery_config_id:
        limit_notifications: When true, events will only fire when QuantityAvailable changes in the following ways: is equal to or less than 0, increases from 0 or less than 0 to a positive number, is equal to or less than NotificationPoint, increases from a number equal to or less than the NotificationPoint to a number greater than the NotificationPoint.
    """

    delivery_config_id: Optional[str] = Field(None, alias="DeliveryConfigID")
    limit_notifications: Optional[bool] = Field(None, alias="LimitNotifications")


class InventoryRecord(OrderCloudModel, Generic[XP]):
    """An OrderCloud InventoryRecord.

    Attributes:
        id:
        owner_id:
        allow_all_buyers: Allow inventory record to be used by all buyers without creating explicit assignments.
        address:  (read-only)
        address_id: AddressID is required because an inventory record represents a location where physical inventory for a given product exists.
        order_can_exceed:
        quantity_available:
        notification_point:
        last_updated:  (read-only)
        xp:
    """

    id: Optional[str] = Field(None, alias="ID")
    owner_id: Optional[str] = Field(None, alias="OwnerID")
    allow_all_buyers: bool = Field(True, alias="AllowAllBuyers")
    address: Optional[_Address] = Field(None, alias="Address")
    address_id: Optional[str] = Field(None, alias="AddressID")
    order_can_exceed: Optional[bool] = Field(None, alias="OrderCanExceed")
    quantity_available: Optional[int] = Field(None, alias="QuantityAvailable")
    notification_point: Optional[int] = Field(None, alias="NotificationPoint")
    last_updated: Optional[str] = Field(None, alias="LastUpdated")
    xp: Optional[XP] = Field(None, alias="xp")
