# GENERATED by tools/codegen — DO NOT EDIT
# Source: ordercloud-openapi-v3.json
"""OrderCloud MessageType, MessageSenderConfig, MessageSender models."""

from __future__ import annotations
from typing import Generic, Optional

from .shared import OrderCloudEnum, OrderCloudModel, XP
from .misc import ApiRole

__all__ = ["MessageType", "MessageSenderConfig", "MessageSender"]


class MessageType(OrderCloudEnum):
    """"""

    OrderDeclined = "OrderDeclined"
    OrderSubmitted = "OrderSubmitted"
    ShipmentCreated = "ShipmentCreated"
    ForgottenPassword = "ForgottenPassword"
    ForgottenUsername = "ForgottenUsername"
    OrderSubmittedForYourApproval = "OrderSubmittedForYourApproval"
    OrderSubmittedForApproval = "OrderSubmittedForApproval"
    OrderApproved = "OrderApproved"
    OrderSubmittedForYourApprovalHasBeenApproved = "OrderSubmittedForYourApprovalHasBeenApproved"
    OrderSubmittedForYourApprovalHasBeenDeclined = "OrderSubmittedForYourApprovalHasBeenDeclined"
    NewUserInvitation = "NewUserInvitation"
    OrderReturnDeclined = "OrderReturnDeclined"
    OrderReturnSubmitted = "OrderReturnSubmitted"
    OrderReturnSubmittedForYourApproval = "OrderReturnSubmittedForYourApproval"
    OrderReturnSubmittedForApproval = "OrderReturnSubmittedForApproval"
    OrderReturnApproved = "OrderReturnApproved"
    OrderReturnSubmittedForYourApprovalHasBeenApproved = (
        "OrderReturnSubmittedForYourApprovalHasBeenApproved"
    )
    OrderReturnSubmittedForYourApprovalHasBeenDeclined = (
        "OrderReturnSubmittedForYourApprovalHasBeenDeclined"
    )
    OrderReturnCompleted = "OrderReturnCompleted"
    SubscriptionReminder = "SubscriptionReminder"
    ProductCollectionInvitationAccepted = "ProductCollectionInvitationAccepted"
    ProductCollectionInvitationDeclined = "ProductCollectionInvitationDeclined"
    OneTimePassword = "OneTimePassword"


class MessageSenderConfig(OrderCloudModel):
    """An OrderCloud MessageSenderConfig.

    Attributes:
        Secret:
        Endpoint:
    """

    Secret: Optional[str] = None
    Endpoint: Optional[str] = None


class MessageSender(OrderCloudModel, Generic[XP]):
    """An OrderCloud MessageSender.

    Attributes:
        ID:
        Name:
        MessageTypes:
        Description:
        ElevatedRoles: If additional data not provided by the message sender is needed, provide any elevated roles needed to make additional calls.
        xp:
        DeliveryConfigID:
        AllowAllBuyers: Allow message sender to trigger for all buyers without creating explicit assignments.
    """

    ID: Optional[str] = None
    Name: Optional[str] = None
    MessageTypes: Optional[list[MessageType]] = None
    Description: Optional[str] = None
    ElevatedRoles: Optional[list[ApiRole]] = None
    xp: Optional[XP] = None
    DeliveryConfigID: Optional[str] = None
    AllowAllBuyers: bool = False
