# GENERATED by tools/codegen — DO NOT EDIT
# Source: ordercloud-openapi-v3.json
"""OrderCloud AccessLevel and related models."""

from __future__ import annotations
from enum import Enum
from typing import Any, Optional

from .shared import OrderCloudModel

__all__ = [
    "AccessLevel",
    "ApiRole",
    "CommerceRole",
    "OrderDirection",
    "OrderStatus",
    "PartyType",
    "SearchType",
    "XpThingType",
    "Incrementor",
    "XpIndex",
    "ProductFacet",
    "GroupOrderInvitation",
]


class AccessLevel(str, Enum):
    """"""

    Private = "Private"
    Public = "Public"
    Shareable = "Shareable"


class ApiRole(str, Enum):
    """"""

    ApiClientAdmin = "ApiClientAdmin"
    ApiClientReader = "ApiClientReader"
    AddressAdmin = "AddressAdmin"
    AddressReader = "AddressReader"
    AdminAddressAdmin = "AdminAddressAdmin"
    AdminAddressReader = "AdminAddressReader"
    AdminUserAdmin = "AdminUserAdmin"
    AdminUserGroupAdmin = "AdminUserGroupAdmin"
    AdminUserGroupReader = "AdminUserGroupReader"
    AdminUserReader = "AdminUserReader"
    ApprovalRuleAdmin = "ApprovalRuleAdmin"
    ApprovalRuleReader = "ApprovalRuleReader"
    BundleAdmin = "BundleAdmin"
    BundleAssignmentAdmin = "BundleAssignmentAdmin"
    BundleReader = "BundleReader"
    BuyerAdmin = "BuyerAdmin"
    BuyerImpersonation = "BuyerImpersonation"
    BuyerReader = "BuyerReader"
    BuyerUserAdmin = "BuyerUserAdmin"
    BuyerUserReader = "BuyerUserReader"
    CatalogAdmin = "CatalogAdmin"
    CatalogReader = "CatalogReader"
    CategoryAdmin = "CategoryAdmin"
    CategoryReader = "CategoryReader"
    CostCenterAdmin = "CostCenterAdmin"
    CostCenterReader = "CostCenterReader"
    CreditCardAdmin = "CreditCardAdmin"
    CreditCardReader = "CreditCardReader"
    EntitySyncConfigAdmin = "EntitySyncConfigAdmin"
    FullAccess = "FullAccess"
    IncrementorAdmin = "IncrementorAdmin"
    IncrementorReader = "IncrementorReader"
    LocaleReader = "LocaleReader"
    LocaleAdmin = "LocaleAdmin"
    MeAddressAdmin = "MeAddressAdmin"
    MeAdmin = "MeAdmin"
    MeCreditCardAdmin = "MeCreditCardAdmin"
    MessageConfigAssignmentAdmin = "MessageConfigAssignmentAdmin"
    MeSubscriptionAdmin = "MeSubscriptionAdmin"
    MeXpAdmin = "MeXpAdmin"
    OrderAdmin = "OrderAdmin"
    OrderReader = "OrderReader"
    OverrideShipping = "OverrideShipping"
    OverrideTax = "OverrideTax"
    OverrideUnitPrice = "OverrideUnitPrice"
    PasswordReset = "PasswordReset"
    PriceScheduleAdmin = "PriceScheduleAdmin"
    PriceScheduleReader = "PriceScheduleReader"
    ProductAdmin = "ProductAdmin"
    ProductAssignmentAdmin = "ProductAssignmentAdmin"
    ProductCollectionReader = "ProductCollectionReader"
    ProductFacetAdmin = "ProductFacetAdmin"
    ProductFacetReader = "ProductFacetReader"
    ProductReader = "ProductReader"
    ProductSyncConfigAdmin = "ProductSyncConfigAdmin"
    PromotionAdmin = "PromotionAdmin"
    PromotionReader = "PromotionReader"
    SecurityProfileAdmin = "SecurityProfileAdmin"
    SecurityProfileReader = "SecurityProfileReader"
    SetSecurityProfile = "SetSecurityProfile"
    ShipmentAdmin = "ShipmentAdmin"
    ShipmentReader = "ShipmentReader"
    Shopper = "Shopper"
    SpendingAccountAdmin = "SpendingAccountAdmin"
    SpendingAccountReader = "SpendingAccountReader"
    SubscriptionAdmin = "SubscriptionAdmin"
    SubscriptionReader = "SubscriptionReader"
    SupplierAddressAdmin = "SupplierAddressAdmin"
    SupplierAddressReader = "SupplierAddressReader"
    SupplierAdmin = "SupplierAdmin"
    SupplierReader = "SupplierReader"
    SupplierUserAdmin = "SupplierUserAdmin"
    SupplierUserGroupAdmin = "SupplierUserGroupAdmin"
    SupplierUserGroupReader = "SupplierUserGroupReader"
    SupplierUserReader = "SupplierUserReader"
    UnsubmittedOrderReader = "UnsubmittedOrderReader"
    UserGroupAdmin = "UserGroupAdmin"
    UserGroupReader = "UserGroupReader"
    OpenIDConnectReader = "OpenIDConnectReader"
    OpenIDConnectAdmin = "OpenIDConnectAdmin"
    MessageSenderReader = "MessageSenderReader"
    MessageSenderAdmin = "MessageSenderAdmin"
    XpIndexAdmin = "XpIndexAdmin"
    WebhookReader = "WebhookReader"
    WebhookAdmin = "WebhookAdmin"
    IntegrationEventReader = "IntegrationEventReader"
    IntegrationEventAdmin = "IntegrationEventAdmin"
    TrackingEventReader = "TrackingEventReader"
    TrackingEventAdmin = "TrackingEventAdmin"
    DeliveryConfigAdmin = "DeliveryConfigAdmin"
    OrderSyncConfigAdmin = "OrderSyncConfigAdmin"
    ErrorConfigAdmin = "ErrorConfigAdmin"


class CommerceRole(str, Enum):
    """"""

    Buyer = "Buyer"
    Seller = "Seller"
    Supplier = "Supplier"


class OrderDirection(str, Enum):
    """Direction of the order, from the current user's perspective."""

    Incoming = "Incoming"
    Outgoing = "Outgoing"
    All = "All"


class OrderStatus(str, Enum):
    """"""

    Unsubmitted = "Unsubmitted"
    AwaitingApproval = "AwaitingApproval"
    Declined = "Declined"
    Open = "Open"
    Completed = "Completed"
    Canceled = "Canceled"


class PartyType(str, Enum):
    """"""

    User = "User"
    Group = "Group"
    Company = "Company"
    BuyerGroup = "BuyerGroup"


class SearchType(str, Enum):
    """"""

    AnyTerm = "AnyTerm"
    AllTermsAnyField = "AllTermsAnyField"
    AllTermsSameField = "AllTermsSameField"
    ExactPhrase = "ExactPhrase"
    ExactPhrasePrefix = "ExactPhrasePrefix"


class XpThingType(str, Enum):
    """"""

    Address = "Address"
    Variant = "Variant"
    Order = "Order"
    OrderReturn = "OrderReturn"
    LineItem = "LineItem"
    CostCenter = "CostCenter"
    CreditCard = "CreditCard"
    Payment = "Payment"
    Spec = "Spec"
    SpecOption = "SpecOption"
    UserGroup = "UserGroup"
    Company = "Company"
    Category = "Category"
    PriceSchedule = "PriceSchedule"
    Shipment = "Shipment"
    SpendingAccount = "SpendingAccount"
    User = "User"
    Promotion = "Promotion"
    ApprovalRule = "ApprovalRule"
    SellerApprovalRule = "SellerApprovalRule"
    Catalog = "Catalog"
    ProductFacet = "ProductFacet"
    MessageSender = "MessageSender"
    InventoryRecord = "InventoryRecord"
    ProductCollection = "ProductCollection"
    Subscription = "Subscription"
    GroupOrderInvitation = "GroupOrderInvitation"
    BuyerGroup = "BuyerGroup"
    Discount = "Discount"


class Incrementor(OrderCloudModel):
    """An OrderCloud Incrementor.

    Attributes:
        ID: The string "{replace-with-incrementor-ID}" can be passed into any ID field to populate the next ID in the sequence. It can also be prefixed with other ID safe characters.
        Name:
        LastNumber: Increments as IDs are generated.
        LeftPaddingCount: Use to enforce a minimum incrementor ID length. For example if your LastNumber is 0 and LeftPaddingCount is 4, your first generated ID will be 0001.
    """

    ID: Optional[str] = None
    Name: Optional[str] = None
    LastNumber: Optional[int] = None
    LeftPaddingCount: Optional[int] = None


class XpIndex(OrderCloudModel):
    """An OrderCloud XpIndex.

    Attributes:
        ThingType:
        Key:
    """

    ThingType: Optional[XpThingType] = None
    Key: Optional[str] = None


class ProductFacet(OrderCloudModel):
    """An OrderCloud ProductFacet.

    Attributes:
        ID:
        Name:
        XpPath: Identifies full path to XP field used for this facet. If not provided, facet value assumed to be stored at product.XP.{facet ID}.
        ListOrder:
        MinCount: Minimum count required or a facet value to be returned in list metadata. If you want zero-count values returned, set this to 0.
        xp:
    """

    ID: Optional[str] = None
    Name: Optional[str] = None
    XpPath: Optional[str] = None
    ListOrder: Optional[int] = None
    MinCount: int = 1
    xp: Optional[dict[str, Any]] = None


class GroupOrderInvitation(OrderCloudModel):
    """An OrderCloud GroupOrderInvitation.

    Attributes:
        ID:  (read-only)
        ExpirationDate: Maximum 1 year.
        Name:
        OrderID:
        OrderStatus:  (read-only)
        xp:
    """

    ID: Optional[str] = None
    ExpirationDate: Optional[str] = None
    Name: Optional[str] = None
    OrderID: Optional[str] = None
    OrderStatus: Optional[OrderStatus] = None
    xp: Optional[dict[str, Any]] = None
