# GENERATED by tools/codegen — DO NOT EDIT
# Source: ordercloud-openapi-v3.json
"""OrderCloud OrderReturnItem, OrderReturnApproval, OrderReturn models."""

from __future__ import annotations
from typing import Generic, Optional

from .shared import OrderCloudModel, XP
from .approval import ApprovalStatus
from .misc import OrderStatus
from .user import User

__all__ = ["OrderReturnItem", "OrderReturnApproval", "OrderReturn"]


class OrderReturnItem(OrderCloudModel):
    """An OrderCloud OrderReturnItem.

    Attributes:
        LineItemID:
        Quantity:
        RefundAmount:
        Comments:
    """

    LineItemID: Optional[str] = None
    Quantity: int = 0
    RefundAmount: Optional[float] = None
    Comments: Optional[str] = None


class OrderReturnApproval(OrderCloudModel):
    """An OrderCloud OrderReturnApproval.

    Attributes:
        OrderReturnID:
        ApprovalRuleID:  (read-only)
        ApprovingGroupID:  (read-only)
        Status:  (read-only)
        DateCreated:  (read-only)
        DateCompleted:  (read-only)
        Approver:  (read-only)
        Comments:  (read-only)
    """

    OrderReturnID: Optional[str] = None
    ApprovalRuleID: Optional[str] = None
    ApprovingGroupID: Optional[str] = None
    Status: Optional[ApprovalStatus] = None
    DateCreated: Optional[str] = None
    DateCompleted: Optional[str] = None
    Approver: Optional[User] = None
    Comments: Optional[str] = None


class OrderReturn(OrderCloudModel, Generic[XP]):
    """An OrderCloud OrderReturn.

    Attributes:
        ID:
        OrderID:
        PaymentIDs: IDs of payments associated with this order return. (read-only)
        Status:  (read-only)
        DateCreated:  (read-only)
        DateSubmitted: Will be null until the order return passes from the buyer to the seller, including when Status is PendingApproval. (read-only)
        DateApproved:  (read-only)
        DateDeclined:  (read-only)
        DateCanceled:  (read-only)
        DateCompleted: Populated when payment to customer has been completed. (read-only)
        LastUpdated:  (read-only)
        RefundAmount: Sum of all RefundAmounts for items. This value can be overridden by a user with the OrderAdmin role. To remove the override set the value to null.
        Comments:
        ItemsToReturn:
        xp:
    """

    ID: Optional[str] = None
    OrderID: Optional[str] = None
    PaymentIDs: Optional[list[str]] = None
    Status: Optional[OrderStatus] = None
    DateCreated: Optional[str] = None
    DateSubmitted: Optional[str] = None
    DateApproved: Optional[str] = None
    DateDeclined: Optional[str] = None
    DateCanceled: Optional[str] = None
    DateCompleted: Optional[str] = None
    LastUpdated: Optional[str] = None
    RefundAmount: Optional[float] = None
    Comments: Optional[str] = None
    ItemsToReturn: Optional[list[OrderReturnItem]] = None
    xp: Optional[XP] = None
