# GENERATED by tools/codegen — DO NOT EDIT
# Source: ordercloud-openapi-v3.json
"""OrderCloud OrderReturnItem, OrderReturnApproval, OrderReturn models."""

from __future__ import annotations
from typing import Generic, Optional
from pydantic import Field

from .shared import OrderCloudModel, XP
from .approval import ApprovalStatus
from .misc import OrderStatus
from .user import User

__all__ = ["OrderReturnItem", "OrderReturnApproval", "OrderReturn"]


class OrderReturnItem(OrderCloudModel):
    """An OrderCloud OrderReturnItem.

    Attributes:
        line_item_id:
        quantity:
        refund_amount:
        comments:
    """

    line_item_id: Optional[str] = Field(None, alias="LineItemID")
    quantity: int = Field(0, alias="Quantity")
    refund_amount: Optional[float] = Field(None, alias="RefundAmount")
    comments: Optional[str] = Field(None, alias="Comments")


class OrderReturnApproval(OrderCloudModel):
    """An OrderCloud OrderReturnApproval.

    Attributes:
        order_return_id:
        approval_rule_id:  (read-only)
        approving_group_id:  (read-only)
        status:  (read-only)
        date_created:  (read-only)
        date_completed:  (read-only)
        approver:  (read-only)
        comments:  (read-only)
    """

    order_return_id: Optional[str] = Field(None, alias="OrderReturnID")
    approval_rule_id: Optional[str] = Field(None, alias="ApprovalRuleID")
    approving_group_id: Optional[str] = Field(None, alias="ApprovingGroupID")
    status: Optional[ApprovalStatus] = Field(None, alias="Status")
    date_created: Optional[str] = Field(None, alias="DateCreated")
    date_completed: Optional[str] = Field(None, alias="DateCompleted")
    approver: Optional[User] = Field(None, alias="Approver")
    comments: Optional[str] = Field(None, alias="Comments")


class OrderReturn(OrderCloudModel, Generic[XP]):
    """An OrderCloud OrderReturn.

    Attributes:
        id:
        order_id:
        payment_i_ds: IDs of payments associated with this order return. (read-only)
        status:  (read-only)
        date_created:  (read-only)
        date_submitted: Will be null until the order return passes from the buyer to the seller, including when Status is PendingApproval. (read-only)
        date_approved:  (read-only)
        date_declined:  (read-only)
        date_canceled:  (read-only)
        date_completed: Populated when payment to customer has been completed. (read-only)
        last_updated:  (read-only)
        refund_amount: Sum of all RefundAmounts for items. This value can be overridden by a user with the OrderAdmin role. To remove the override set the value to null.
        comments:
        items_to_return:
        xp:
    """

    id: Optional[str] = Field(None, alias="ID")
    order_id: Optional[str] = Field(None, alias="OrderID")
    payment_i_ds: Optional[list[str]] = Field(None, alias="PaymentIDs")
    status: Optional[OrderStatus] = Field(None, alias="Status")
    date_created: Optional[str] = Field(None, alias="DateCreated")
    date_submitted: Optional[str] = Field(None, alias="DateSubmitted")
    date_approved: Optional[str] = Field(None, alias="DateApproved")
    date_declined: Optional[str] = Field(None, alias="DateDeclined")
    date_canceled: Optional[str] = Field(None, alias="DateCanceled")
    date_completed: Optional[str] = Field(None, alias="DateCompleted")
    last_updated: Optional[str] = Field(None, alias="LastUpdated")
    refund_amount: Optional[float] = Field(None, alias="RefundAmount")
    comments: Optional[str] = Field(None, alias="Comments")
    items_to_return: Optional[list[OrderReturnItem]] = Field(None, alias="ItemsToReturn")
    xp: Optional[XP] = Field(None, alias="xp")
