# GENERATED by tools/codegen — DO NOT EDIT
# Source: ordercloud-openapi-v3.json
"""OrderCloud PriceMarkupType, PriceBreak, PriceSchedule models."""

from __future__ import annotations
from typing import Generic, Optional

from .shared import OrderCloudEnum, OrderCloudModel, XP

__all__ = ["PriceMarkupType", "PriceBreak", "PriceSchedule"]


class PriceMarkupType(OrderCloudEnum):
    """"""

    NoMarkup = "NoMarkup"
    AmountPerQuantity = "AmountPerQuantity"
    AmountTotal = "AmountTotal"
    Percentage = "Percentage"


class PriceBreak(OrderCloudModel):
    """An OrderCloud PriceBreak.

    Attributes:
        Quantity: Most commonly 1, except when offering tiered/bulk pricing.
        Price: Price per unit.
        SalePrice: Sale Price per unit. If the current date/time is within the PriceSchedule SaleStart and SaleEnd, this SalePrice will be used.
        SubscriptionPrice: Subscription Price per unit. If set, this price is used when a subscription order is created.
        BundlePrice: Bundle Price per unit. If set, this price is used when an item being added to an order is part of a bundle.
    """

    Quantity: Optional[int] = None
    Price: Optional[float] = None
    SalePrice: Optional[float] = None
    SubscriptionPrice: Optional[float] = None
    BundlePrice: Optional[float] = None


class PriceSchedule(OrderCloudModel, Generic[XP]):
    """An OrderCloud PriceSchedule.

    Attributes:
        PriceBreaks:
        OwnerID: ID of the organization that owns the PriceSchedule. Only the marketplace owner can override the OwnerID on create.
        ID:
        Name:
        ApplyTax: For reference only for calculating tax, does not influence any OrderCloud behavior.
        ApplyShipping: For reference only for calculating shipping cost, does not influence any OrderCloud behavior.
        MinQuantity: The minimum line item Quantity when UseCumulativeQuantity is false.
        MaxQuantity: The maximum line item Quantity when UseCumulativeQuantity is false.
        UseCumulativeQuantity: If true, line item quantities will be aggregated by productID when determining which price break applies, and when Min/Max quantities are met. Else, each line item is treated separately.
        RestrictedQuantity: If true, this product can only be ordered in quantities that exactly match one of the price breaks on this schedule.
        Currency: We recommend using ISO-4217 currency codes for compatibility with tax and payment processors.
        SaleStart: Starting date/time for PriceBreak.SalePrice to be used as the price for the LineItem. Requires that the PriceBreak.SalePrice value is set.
        SaleEnd: Ending date/time for PriceBreak.SalePrice to be used as the price for the LineItem. Requires that the PriceBreak.SalePrice value is set.
        IsOnSale: True when at least one PriceBreak has a SalePrice defined, and the current time is between the SaleStart and SaleEnd date. (read-only)
        xp:
    """

    PriceBreaks: Optional[list[PriceBreak]] = None
    OwnerID: Optional[str] = None
    ID: Optional[str] = None
    Name: Optional[str] = None
    ApplyTax: Optional[bool] = None
    ApplyShipping: Optional[bool] = None
    MinQuantity: int = 1
    MaxQuantity: Optional[int] = None
    UseCumulativeQuantity: Optional[bool] = None
    RestrictedQuantity: Optional[bool] = None
    Currency: Optional[str] = None
    SaleStart: Optional[str] = None
    SaleEnd: Optional[str] = None
    IsOnSale: Optional[bool] = None
    xp: Optional[XP] = None
