# GENERATED by tools/codegen — DO NOT EDIT
# Source: ordercloud-openapi-v3.json
"""OrderCloud ProductCollectionEntry and related models."""

from __future__ import annotations
from typing import Generic, Optional
from pydantic import Field

from .shared import OrderCloudModel, XP
from .buyer import BuyerPriceSchedule
from .misc import AccessLevel
from .product import Inventory

__all__ = [
    "ProductCollectionEntry",
    "ProductCollectionProduct",
    "ProductCollectionBuyerProduct",
    "ProductCollectionInvitation",
    "ProductCollection",
]
_Inventory = Inventory
_AccessLevel = AccessLevel


class ProductCollectionEntry(OrderCloudModel):
    """An OrderCloud ProductCollectionEntry.

    Attributes:
        product_id:
        list_order:
    """

    product_id: Optional[str] = Field(None, alias="ProductID")
    list_order: Optional[int] = Field(None, alias="ListOrder")


class ProductCollectionProduct(OrderCloudModel, Generic[XP]):
    """An OrderCloud ProductCollectionProduct.

    Attributes:
        list_order:
        date_added:
        owner_id: ID of the organization that owns the product. Only the marketplace owner can override the OwnerID on create.
        default_price_schedule_id: When provided, no explicit price schedule assignment is required. When a price schedule assignment exists, it will override any default provided.
        auto_forward: If true, when this product is ordered by a buyer, it will automatically be added to a new order from the marketplace owner to the default supplier and submitted. Requires a valid DefaultSupplierID.
        id:
        parent_id: ID of the parent product. If not null, IsParent should be false
        is_parent: If true, ParentID must be null, as a parent product cannot have a parent itself.
        is_bundle: If true, IsParent must be false, as a parent product cannot be a bundle. (read-only)
        name:
        description:
        quantity_multiplier: For reference only, does not influence any OrderCloud behavior. Used to indicate an amount per Quantity.
        ship_weight:
        ship_height:
        ship_width:
        ship_length:
        active: If false, product is not visible or purchasable from a buyer's perspective.
        spec_count: Count of specs assigned to the product. (read-only)
        variant_count: Count of variants generated from the product/spec combinations. (read-only)
        ship_from_address_id: Marketplace owner or supplier AddressID where the product will be shipped from. Can be used to calculate shipping costs.
        inventory:
        default_supplier_id: Used for forwarding orders to suppliers.
        all_suppliers_can_sell: If true, all suppliers are eligible to opt into selling this product.
        returnable:
        date_created:  (read-only)
        xp:
    """

    list_order: Optional[int] = Field(None, alias="ListOrder")
    date_added: Optional[str] = Field(None, alias="DateAdded")
    owner_id: Optional[str] = Field(None, alias="OwnerID")
    default_price_schedule_id: Optional[str] = Field(None, alias="DefaultPriceScheduleID")
    auto_forward: Optional[bool] = Field(None, alias="AutoForward")
    id: Optional[str] = Field(None, alias="ID")
    parent_id: Optional[str] = Field(None, alias="ParentID")
    is_parent: Optional[bool] = Field(None, alias="IsParent")
    is_bundle: Optional[bool] = Field(None, alias="IsBundle")
    name: Optional[str] = Field(None, alias="Name")
    description: Optional[str] = Field(None, alias="Description")
    quantity_multiplier: int = Field(1, alias="QuantityMultiplier")
    ship_weight: Optional[float] = Field(None, alias="ShipWeight")
    ship_height: Optional[float] = Field(None, alias="ShipHeight")
    ship_width: Optional[float] = Field(None, alias="ShipWidth")
    ship_length: Optional[float] = Field(None, alias="ShipLength")
    active: Optional[bool] = Field(None, alias="Active")
    spec_count: int = Field(0, alias="SpecCount")
    variant_count: int = Field(0, alias="VariantCount")
    ship_from_address_id: Optional[str] = Field(None, alias="ShipFromAddressID")
    inventory: Optional[_Inventory] = Field(None, alias="Inventory")
    default_supplier_id: Optional[str] = Field(None, alias="DefaultSupplierID")
    all_suppliers_can_sell: Optional[bool] = Field(None, alias="AllSuppliersCanSell")
    returnable: Optional[bool] = Field(None, alias="Returnable")
    date_created: Optional[str] = Field(None, alias="DateCreated")
    xp: Optional[XP] = Field(None, alias="xp")


class ProductCollectionBuyerProduct(OrderCloudModel, Generic[XP]):
    """An OrderCloud ProductCollectionBuyerProduct.

    Attributes:
        list_order:
        date_added:
        price_schedule:  (read-only)
        id:
        parent_id: ID of the parent product. If not null, IsParent should be false
        is_parent: If true, ParentID must be null, as a parent product cannot have a parent itself.
        is_bundle: If true, IsParent must be false, as a parent product cannot be a bundle. (read-only)
        name:
        description:
        quantity_multiplier: For reference only, does not influence any OrderCloud behavior. Used to indicate an amount per Quantity.
        ship_weight:
        ship_height:
        ship_width:
        ship_length:
        active: If false, product is not visible or purchasable from a buyer's perspective.
        spec_count: Count of specs assigned to the product. (read-only)
        variant_count: Count of variants generated from the product/spec combinations. (read-only)
        ship_from_address_id: Marketplace owner or supplier AddressID where the product will be shipped from. Can be used to calculate shipping costs.
        inventory:
        default_supplier_id: Used for forwarding orders to suppliers.
        all_suppliers_can_sell: If true, all suppliers are eligible to opt into selling this product.
        returnable:
        date_created:  (read-only)
        xp:
    """

    list_order: Optional[int] = Field(None, alias="ListOrder")
    date_added: Optional[str] = Field(None, alias="DateAdded")
    price_schedule: Optional[BuyerPriceSchedule] = Field(None, alias="PriceSchedule")
    id: Optional[str] = Field(None, alias="ID")
    parent_id: Optional[str] = Field(None, alias="ParentID")
    is_parent: Optional[bool] = Field(None, alias="IsParent")
    is_bundle: Optional[bool] = Field(None, alias="IsBundle")
    name: Optional[str] = Field(None, alias="Name")
    description: Optional[str] = Field(None, alias="Description")
    quantity_multiplier: int = Field(1, alias="QuantityMultiplier")
    ship_weight: Optional[float] = Field(None, alias="ShipWeight")
    ship_height: Optional[float] = Field(None, alias="ShipHeight")
    ship_width: Optional[float] = Field(None, alias="ShipWidth")
    ship_length: Optional[float] = Field(None, alias="ShipLength")
    active: Optional[bool] = Field(None, alias="Active")
    spec_count: int = Field(0, alias="SpecCount")
    variant_count: int = Field(0, alias="VariantCount")
    ship_from_address_id: Optional[str] = Field(None, alias="ShipFromAddressID")
    inventory: Optional[_Inventory] = Field(None, alias="Inventory")
    default_supplier_id: Optional[str] = Field(None, alias="DefaultSupplierID")
    all_suppliers_can_sell: Optional[bool] = Field(None, alias="AllSuppliersCanSell")
    returnable: Optional[bool] = Field(None, alias="Returnable")
    date_created: Optional[str] = Field(None, alias="DateCreated")
    xp: Optional[XP] = Field(None, alias="xp")


class ProductCollectionInvitation(OrderCloudModel, Generic[XP]):
    """An OrderCloud ProductCollectionInvitation.

    Attributes:
        id:  (read-only)
        name:
        admin:
        accepted: Updated when accepted. (read-only)
        expiration_date: ExpirationDate defaults to 30 days from create, maximum 1 year.
        xp:
    """

    id: Optional[str] = Field(None, alias="ID")
    name: Optional[str] = Field(None, alias="Name")
    admin: bool = Field(False, alias="Admin")
    accepted: bool = Field(False, alias="Accepted")
    expiration_date: Optional[str] = Field(None, alias="ExpirationDate")
    xp: Optional[XP] = Field(None, alias="xp")


class ProductCollection(OrderCloudModel, Generic[XP]):
    """An OrderCloud ProductCollection.

    Attributes:
        id:
        name:
        xp:
        access_level:
    """

    id: Optional[str] = Field(None, alias="ID")
    name: Optional[str] = Field(None, alias="Name")
    xp: Optional[XP] = Field(None, alias="xp")
    access_level: Optional[_AccessLevel] = Field(None, alias="AccessLevel")
