# GENERATED by tools/codegen — DO NOT EDIT
# Source: ordercloud-openapi-v3.json
"""OrderCloud PromotionOverride and related models."""

from __future__ import annotations
from typing import Any, Optional

from .shared import OrderCloudModel

__all__ = [
    "PromotionOverride",
    "PromotionIntegration",
    "AddedPromo",
    "RemovedPromo",
    "EligiblePromotion",
    "RefreshPromosResponse",
    "Promotion",
]


class PromotionOverride(OrderCloudModel):
    """An OrderCloud PromotionOverride.

    Attributes:
        PromotionID:
        Amount: Overrides the promotion's calculated discount to this amount.
    """

    PromotionID: Optional[str] = None
    Amount: Optional[float] = None


class PromotionIntegration(OrderCloudModel):
    """An OrderCloud PromotionIntegration.

    Attributes:
        HashKey: Security feature that allows your middleware to verify the digital signature in the request header to ensure you only accept trusted data.
        Url:
        CustomAuthHeaderName: The header name that can be passed to your middleware.
        CustomAuthHeaderValue: The header value that can be passed to your middleware.
    """

    HashKey: Optional[str] = None
    Url: Optional[str] = None
    CustomAuthHeaderName: Optional[str] = None
    CustomAuthHeaderValue: Optional[str] = None


class AddedPromo(OrderCloudModel):
    """An OrderCloud AddedPromo.

    Attributes:
        LineItemID:
        Amount:
        ID:
        LineItemLevel: If true, certain eligible expression requirements must be met, and the PromotionDiscount will be applied at the line item level.
        Code: Must be unique. Entered by buyer when adding promo to order.
        Name:
        RedemptionLimit: Limit the total number of orders this promotion can be applied to across all users.
        RedemptionLimitPerUser: Limit the total number of orders this promotion can be applied to per user.
        RedemptionCount: The number of times this promotion has been applied to an order. (read-only)
        QuantityLimitPerOrder: Can only be used when LineItemLevel is true and ItemLimitPerOrder does not have a value. When defined the ValueExpression will be the discount applied to each qualifying quantity of eligible items. When no ItemSortBy is defined, items will be sorted by DateAdded ascending.
        ItemLimitPerOrder: Can only be used when LineItemLevel is true and QuantityLimitPerOrder does not have a value. Limits the number of items the promotion will apply to when eligible. When no ItemSortBy is defined, items will be sorted by DateAdded ascending.
        ItemSortBy: Comma delimited list of properties to sort by. Can only be used when ItemLimitPerOrder is true. Used to determine the order in which the promotion is applied to the specified limit of items. Use ! to reverse sort order on a property.
        Description:
        FinePrint: For reference only. Terms, conditions, and other legal jargon.
        StartDate:
        ExpirationDate:
        EligibleExpression: The expression evaluated to determine if an item or order is eligible for a promotion. See rules engine documentation for formatting details.
        ValueExpression: The expression evaluated to determine the discount amount of an eligible promotion. See rules engine documentation for formatting details.
        CanCombine: If true, the promotion can be applied to an order that already other promotions applied, as long as they can also be combined.
        AllowAllBuyers: Allow promo to be used by all buyers without creating explicit assignments.
        OwnerID: ID of the organization that owns the promotion. Only the marketplace owner can override the OwnerID on create.
        AutoApply:
        Active:
        UseIntegration:
        Priority: Used to control the order in which promotions are applied when calling the auto apply or refresh endpoint.
        xp:
    """

    LineItemID: Optional[str] = None
    Amount: Optional[float] = None
    ID: Optional[str] = None
    LineItemLevel: Optional[bool] = None
    Code: Optional[str] = None
    Name: Optional[str] = None
    RedemptionLimit: Optional[int] = None
    RedemptionLimitPerUser: Optional[int] = None
    RedemptionCount: int = 0
    QuantityLimitPerOrder: Optional[int] = None
    ItemLimitPerOrder: Optional[int] = None
    ItemSortBy: Optional[str] = None
    Description: Optional[str] = None
    FinePrint: Optional[str] = None
    StartDate: Optional[str] = None
    ExpirationDate: Optional[str] = None
    EligibleExpression: Optional[str] = None
    ValueExpression: Optional[str] = None
    CanCombine: Optional[bool] = None
    AllowAllBuyers: Optional[bool] = None
    OwnerID: Optional[str] = None
    AutoApply: bool = False
    Active: bool = True
    UseIntegration: Optional[bool] = None
    Priority: Optional[int] = None
    xp: Optional[dict[str, Any]] = None


class RemovedPromo(OrderCloudModel):
    """An OrderCloud RemovedPromo.

    Attributes:
        ErrorCode:
        Reason:
        LineItemID:
        Amount:
        ID:
        LineItemLevel: If true, certain eligible expression requirements must be met, and the PromotionDiscount will be applied at the line item level.
        Code: Must be unique. Entered by buyer when adding promo to order.
        Name:
        RedemptionLimit: Limit the total number of orders this promotion can be applied to across all users.
        RedemptionLimitPerUser: Limit the total number of orders this promotion can be applied to per user.
        RedemptionCount: The number of times this promotion has been applied to an order. (read-only)
        QuantityLimitPerOrder: Can only be used when LineItemLevel is true and ItemLimitPerOrder does not have a value. When defined the ValueExpression will be the discount applied to each qualifying quantity of eligible items. When no ItemSortBy is defined, items will be sorted by DateAdded ascending.
        ItemLimitPerOrder: Can only be used when LineItemLevel is true and QuantityLimitPerOrder does not have a value. Limits the number of items the promotion will apply to when eligible. When no ItemSortBy is defined, items will be sorted by DateAdded ascending.
        ItemSortBy: Comma delimited list of properties to sort by. Can only be used when ItemLimitPerOrder is true. Used to determine the order in which the promotion is applied to the specified limit of items. Use ! to reverse sort order on a property.
        Description:
        FinePrint: For reference only. Terms, conditions, and other legal jargon.
        StartDate:
        ExpirationDate:
        EligibleExpression: The expression evaluated to determine if an item or order is eligible for a promotion. See rules engine documentation for formatting details.
        ValueExpression: The expression evaluated to determine the discount amount of an eligible promotion. See rules engine documentation for formatting details.
        CanCombine: If true, the promotion can be applied to an order that already other promotions applied, as long as they can also be combined.
        AllowAllBuyers: Allow promo to be used by all buyers without creating explicit assignments.
        OwnerID: ID of the organization that owns the promotion. Only the marketplace owner can override the OwnerID on create.
        AutoApply:
        Active:
        UseIntegration:
        Priority: Used to control the order in which promotions are applied when calling the auto apply or refresh endpoint.
        xp:
    """

    ErrorCode: Optional[str] = None
    Reason: Optional[str] = None
    LineItemID: Optional[str] = None
    Amount: Optional[float] = None
    ID: Optional[str] = None
    LineItemLevel: Optional[bool] = None
    Code: Optional[str] = None
    Name: Optional[str] = None
    RedemptionLimit: Optional[int] = None
    RedemptionLimitPerUser: Optional[int] = None
    RedemptionCount: int = 0
    QuantityLimitPerOrder: Optional[int] = None
    ItemLimitPerOrder: Optional[int] = None
    ItemSortBy: Optional[str] = None
    Description: Optional[str] = None
    FinePrint: Optional[str] = None
    StartDate: Optional[str] = None
    ExpirationDate: Optional[str] = None
    EligibleExpression: Optional[str] = None
    ValueExpression: Optional[str] = None
    CanCombine: Optional[bool] = None
    AllowAllBuyers: Optional[bool] = None
    OwnerID: Optional[str] = None
    AutoApply: bool = False
    Active: bool = True
    UseIntegration: Optional[bool] = None
    Priority: Optional[int] = None
    xp: Optional[dict[str, Any]] = None


class EligiblePromotion(OrderCloudModel):
    """An OrderCloud EligiblePromotion.

    Attributes:
        Amount:  (read-only)
        ID:
        LineItemLevel: If true, certain eligible expression requirements must be met, and the PromotionDiscount will be applied at the line item level.
        Code: Must be unique. Entered by buyer when adding promo to order.
        Name:
        RedemptionLimit: Limit the total number of orders this promotion can be applied to across all users.
        RedemptionLimitPerUser: Limit the total number of orders this promotion can be applied to per user.
        RedemptionCount: The number of times this promotion has been applied to an order. (read-only)
        QuantityLimitPerOrder: Can only be used when LineItemLevel is true and ItemLimitPerOrder does not have a value. When defined the ValueExpression will be the discount applied to each qualifying quantity of eligible items. When no ItemSortBy is defined, items will be sorted by DateAdded ascending.
        ItemLimitPerOrder: Can only be used when LineItemLevel is true and QuantityLimitPerOrder does not have a value. Limits the number of items the promotion will apply to when eligible. When no ItemSortBy is defined, items will be sorted by DateAdded ascending.
        ItemSortBy: Comma delimited list of properties to sort by. Can only be used when ItemLimitPerOrder is true. Used to determine the order in which the promotion is applied to the specified limit of items. Use ! to reverse sort order on a property.
        Description:
        FinePrint: For reference only. Terms, conditions, and other legal jargon.
        StartDate:
        ExpirationDate:
        EligibleExpression: The expression evaluated to determine if an item or order is eligible for a promotion. See rules engine documentation for formatting details.
        ValueExpression: The expression evaluated to determine the discount amount of an eligible promotion. See rules engine documentation for formatting details.
        CanCombine: If true, the promotion can be applied to an order that already other promotions applied, as long as they can also be combined.
        AllowAllBuyers: Allow promo to be used by all buyers without creating explicit assignments.
        OwnerID: ID of the organization that owns the promotion. Only the marketplace owner can override the OwnerID on create.
        AutoApply:
        Active:
        UseIntegration:
        Priority: Used to control the order in which promotions are applied when calling the auto apply or refresh endpoint.
        xp:
    """

    Amount: float = 0.0
    ID: Optional[str] = None
    LineItemLevel: Optional[bool] = None
    Code: Optional[str] = None
    Name: Optional[str] = None
    RedemptionLimit: Optional[int] = None
    RedemptionLimitPerUser: Optional[int] = None
    RedemptionCount: int = 0
    QuantityLimitPerOrder: Optional[int] = None
    ItemLimitPerOrder: Optional[int] = None
    ItemSortBy: Optional[str] = None
    Description: Optional[str] = None
    FinePrint: Optional[str] = None
    StartDate: Optional[str] = None
    ExpirationDate: Optional[str] = None
    EligibleExpression: Optional[str] = None
    ValueExpression: Optional[str] = None
    CanCombine: Optional[bool] = None
    AllowAllBuyers: Optional[bool] = None
    OwnerID: Optional[str] = None
    AutoApply: bool = False
    Active: bool = True
    UseIntegration: Optional[bool] = None
    Priority: Optional[int] = None
    xp: Optional[dict[str, Any]] = None


class RefreshPromosResponse(OrderCloudModel):
    """An OrderCloud RefreshPromosResponse.

    Attributes:
        PromosAdded: Promotions that were auto-applied.
        PromosRemoved: Promotions that were removed due to ineligibility or other reasons.
    """

    PromosAdded: Optional[list[AddedPromo]] = None
    PromosRemoved: Optional[list[RemovedPromo]] = None


class Promotion(OrderCloudModel):
    """An OrderCloud Promotion.

    Attributes:
        ID:
        LineItemLevel: If true, certain eligible expression requirements must be met, and the PromotionDiscount will be applied at the line item level.
        Code: Must be unique. Entered by buyer when adding promo to order.
        Name:
        RedemptionLimit: Limit the total number of orders this promotion can be applied to across all users.
        RedemptionLimitPerUser: Limit the total number of orders this promotion can be applied to per user.
        RedemptionCount: The number of times this promotion has been applied to an order. (read-only)
        QuantityLimitPerOrder: Can only be used when LineItemLevel is true and ItemLimitPerOrder does not have a value. When defined the ValueExpression will be the discount applied to each qualifying quantity of eligible items. When no ItemSortBy is defined, items will be sorted by DateAdded ascending.
        ItemLimitPerOrder: Can only be used when LineItemLevel is true and QuantityLimitPerOrder does not have a value. Limits the number of items the promotion will apply to when eligible. When no ItemSortBy is defined, items will be sorted by DateAdded ascending.
        ItemSortBy: Comma delimited list of properties to sort by. Can only be used when ItemLimitPerOrder is true. Used to determine the order in which the promotion is applied to the specified limit of items. Use ! to reverse sort order on a property.
        Description:
        FinePrint: For reference only. Terms, conditions, and other legal jargon.
        StartDate:
        ExpirationDate:
        EligibleExpression: The expression evaluated to determine if an item or order is eligible for a promotion. See rules engine documentation for formatting details.
        ValueExpression: The expression evaluated to determine the discount amount of an eligible promotion. See rules engine documentation for formatting details.
        CanCombine: If true, the promotion can be applied to an order that already other promotions applied, as long as they can also be combined.
        AllowAllBuyers: Allow promo to be used by all buyers without creating explicit assignments.
        OwnerID: ID of the organization that owns the promotion. Only the marketplace owner can override the OwnerID on create.
        AutoApply:
        Active:
        UseIntegration:
        Priority: Used to control the order in which promotions are applied when calling the auto apply or refresh endpoint.
        xp:
    """

    ID: Optional[str] = None
    LineItemLevel: Optional[bool] = None
    Code: Optional[str] = None
    Name: Optional[str] = None
    RedemptionLimit: Optional[int] = None
    RedemptionLimitPerUser: Optional[int] = None
    RedemptionCount: int = 0
    QuantityLimitPerOrder: Optional[int] = None
    ItemLimitPerOrder: Optional[int] = None
    ItemSortBy: Optional[str] = None
    Description: Optional[str] = None
    FinePrint: Optional[str] = None
    StartDate: Optional[str] = None
    ExpirationDate: Optional[str] = None
    EligibleExpression: Optional[str] = None
    ValueExpression: Optional[str] = None
    CanCombine: Optional[bool] = None
    AllowAllBuyers: Optional[bool] = None
    OwnerID: Optional[str] = None
    AutoApply: bool = False
    Active: bool = True
    UseIntegration: Optional[bool] = None
    Priority: Optional[int] = None
    xp: Optional[dict[str, Any]] = None
