# GENERATED by tools/codegen — DO NOT EDIT
# Source: ordercloud-openapi-v3.json
"""OrderCloud PasswordConfig, ImpersonationConfig, SecurityProfile models."""

from __future__ import annotations
from typing import Optional

from .shared import OrderCloudModel
from .misc import ApiRole

__all__ = ["PasswordConfig", "ImpersonationConfig", "SecurityProfile"]


class PasswordConfig(OrderCloudModel):
    """An OrderCloud PasswordConfig.

    Attributes:
        LimitPasswordReuse: The number of passwords, including the current password, that are blocked from reuse. For example, if set to 1, any password except the current one can be reused.
        MaxConsecutiveDupeChars: The maximum number of consecutive repeating characters in a password.
        MaximumPasswordAge: The password expires after MaximumPasswordAge in days.
        MinimumPasswordAge: The password may not be changed again until this number of minutes has passed.
        AllowedFailedAttempts: The number of failed attempts before the account is locked for the LockoutDuration.
        LockoutDuration: The number of minutes an account is locked when the AllowedFailedAttempts is reached. Use 0 to indicate that lockout should be indefinite, requiring the manual intervention by an admin user.
        UpperCaseRequired: At least one upper case character is required.
        LowerCaseRequired: At least one lower case character is required.
        SpecialCharacterRequired: At least one special character is required.
        NumericRequired: At least one number is required.
        MinimumCharacterCount: The minimum length of a password.
    """

    LimitPasswordReuse: Optional[int] = None
    MaxConsecutiveDupeChars: Optional[int] = None
    MaximumPasswordAge: Optional[int] = None
    MinimumPasswordAge: Optional[int] = None
    AllowedFailedAttempts: Optional[int] = None
    LockoutDuration: Optional[int] = None
    UpperCaseRequired: Optional[bool] = None
    LowerCaseRequired: Optional[bool] = None
    SpecialCharacterRequired: Optional[bool] = None
    NumericRequired: Optional[bool] = None
    MinimumCharacterCount: Optional[int] = None


class ImpersonationConfig(OrderCloudModel):
    """An OrderCloud ImpersonationConfig.

    Attributes:
        ID:
        ImpersonationBuyerID: The BuyerID of the impersonator group or user (party doing the impersonating)
        ImpersonationGroupID: The UserGroupID of the impersonator (party doing the impersonating)
        ImpersonationUserID: The UserID of the impersonator (party doing the impersonating)
        BuyerID: The BuyerID of the impersonatee (party being impersonated). If null, the config can be used to impersonate users in any buyer in the marketplace that is able to access the specified API Client.
        GroupID: The UserGroupID of the impersonatee (party being impersonated)
        UserID: The UserID of the impersonatee (party being impersonated)
        SecurityProfileID:
        ClientID:
    """

    ID: Optional[str] = None
    ImpersonationBuyerID: Optional[str] = None
    ImpersonationGroupID: Optional[str] = None
    ImpersonationUserID: Optional[str] = None
    BuyerID: Optional[str] = None
    GroupID: Optional[str] = None
    UserID: Optional[str] = None
    SecurityProfileID: Optional[str] = None
    ClientID: Optional[str] = None


class SecurityProfile(OrderCloudModel):
    """An OrderCloud SecurityProfile.

    Attributes:
        ID:
        Name:
        Roles:
        CustomRoles:
        PasswordConfig:
    """

    ID: Optional[str] = None
    Name: Optional[str] = None
    Roles: Optional[list[ApiRole]] = None
    CustomRoles: Optional[list[str]] = None
    PasswordConfig: Optional[_PasswordConfig] = None


_PasswordConfig = PasswordConfig
