# GENERATED by tools/codegen — DO NOT EDIT
# Source: ordercloud-openapi-v3.json
"""OrderCloud SubscriptionInterval and related models."""

from __future__ import annotations
from enum import Enum
from typing import Generic, Optional

from .shared import OrderCloudModel, XP
from .misc import ApiRole
from .payment import PaymentType

__all__ = [
    "SubscriptionInterval",
    "SubscriptionPayment",
    "SubscriptionIntegration",
    "SubscriptionIntegrationResponse",
    "Subscription",
]


class SubscriptionInterval(str, Enum):
    """"""

    Days = "Days"
    Weeks = "Weeks"
    Months = "Months"


class SubscriptionPayment(OrderCloudModel):
    """An OrderCloud SubscriptionPayment.

    Attributes:
        Type:
        CreditCardID:
        SpendingAccountID:
    """

    Type: Optional[PaymentType] = None
    CreditCardID: Optional[str] = None
    SpendingAccountID: Optional[str] = None


class SubscriptionIntegration(OrderCloudModel, Generic[XP]):
    """An OrderCloud SubscriptionIntegration.

    Attributes:
        ApiClientID: ID of the API client that will be used to generate the token passed to your hosted application via subscription integration.
        HashKey: Security feature that allows your middleware to verify the digital signature in the request header to ensure you only accept trusted data.
        ElevatedRoles:
        Active:
        NotificationDays:
        Url:
        xp:
        CustomAuthHeaderName: The header name that can be passed to your middleware.
        CustomAuthHeaderValue: The header value that can be passed to your middleware.
    """

    ApiClientID: Optional[str] = None
    HashKey: Optional[str] = None
    ElevatedRoles: Optional[list[ApiRole]] = None
    Active: Optional[bool] = None
    NotificationDays: Optional[int] = None
    Url: Optional[str] = None
    xp: Optional[XP] = None
    CustomAuthHeaderName: Optional[str] = None
    CustomAuthHeaderValue: Optional[str] = None


class SubscriptionIntegrationResponse(OrderCloudModel, Generic[XP]):
    """An OrderCloud SubscriptionIntegrationResponse.

    Attributes:
        HttpStatusCode:
        UnhandledErrorBody:
        xp:
        Succeeded:
    """

    HttpStatusCode: Optional[int] = None
    UnhandledErrorBody: Optional[str] = None
    xp: Optional[XP] = None
    Succeeded: Optional[bool] = None


class Subscription(OrderCloudModel, Generic[XP]):
    """An OrderCloud Subscription.

    Attributes:
        ID:
        Frequency: Used to define how often to process the subscription. The subscription will process once every {Frequency} {Interval}.
        Interval: Used to define how often to process the subscription. The subscription will process once every {Frequency} {Interval}.
        NextOrderDate: Next order date of the subscription. The hourly process that creates subscription orders will query for subscriptions with a NextOrderDate between now and five hours ago.
        LastOrderDate:  (read-only)
        NotificationDate: Date that subscription order reminder message sender will be triggered if used. Value is the result of NextOrderDate less NotificationDays on the subscription integration. (read-only)
        DateCreated:  (read-only)
        EndDate:
        Active:
        FromCompanyID: Only use when creating a subscription on behalf of another user. ID of the buyer or marketplace owner placing the order.
        FromUserID: Only use when creating a subscription on behalf of a another user.
        ToCompanyID: ID of the marketplace owner or supplier receiving the order created by this subscription, only writable on create.
        Payment:
        BillingAddressID:
        ShippingAddressID:
        ProjectedSubtotal: Tentative subtotal of next subscription order. Based on current known pricing; avoid if product or pricing is provided by an external integration. (read-only)
        xp:
    """

    ID: Optional[str] = None
    Frequency: Optional[int] = None
    Interval: Optional[SubscriptionInterval] = None
    NextOrderDate: Optional[str] = None
    LastOrderDate: Optional[str] = None
    NotificationDate: Optional[str] = None
    DateCreated: Optional[str] = None
    EndDate: Optional[str] = None
    Active: bool = True
    FromCompanyID: Optional[str] = None
    FromUserID: Optional[str] = None
    ToCompanyID: Optional[str] = None
    Payment: Optional[SubscriptionPayment] = None
    BillingAddressID: Optional[str] = None
    ShippingAddressID: Optional[str] = None
    ProjectedSubtotal: float = 0.0
    xp: Optional[XP] = None
