# GENERATED by tools/codegen — DO NOT EDIT
# Source: ordercloud-openapi-v3.json
"""OrderCloud SupplierBuyer, Supplier models."""

from __future__ import annotations
from typing import Generic, Optional
from pydantic import Field

from .shared import OrderCloudModel, XP

__all__ = ["SupplierBuyer", "Supplier"]


class SupplierBuyer(OrderCloudModel):
    """An OrderCloud SupplierBuyer.

    Attributes:
        id:
        name:
    """

    id: Optional[str] = Field(None, alias="ID")
    name: Optional[str] = Field(None, alias="Name")


class Supplier(OrderCloudModel, Generic[XP]):
    """An OrderCloud Supplier.

    Attributes:
        id:
        name:
        active: If false, all user authentication is blocked.
        date_created:  (read-only)
        all_buyers_can_order: If false, buyers will only be able to set ToCompanyID on an order to the marketplace owner, or suppliers they have an explicit relationship to.
        xp:
    """

    id: Optional[str] = Field(None, alias="ID")
    name: Optional[str] = Field(None, alias="Name")
    active: Optional[bool] = Field(None, alias="Active")
    date_created: Optional[str] = Field(None, alias="DateCreated")
    all_buyers_can_order: Optional[bool] = Field(None, alias="AllBuyersCanOrder")
    xp: Optional[XP] = Field(None, alias="xp")
