# GENERATED by tools/codegen — DO NOT EDIT
# Source: ordercloud-openapi-v3.json
"""OrderCloud SupplierBuyer, Supplier models."""

from __future__ import annotations
from typing import Any, Optional

from .shared import OrderCloudModel

__all__ = ["SupplierBuyer", "Supplier"]


class SupplierBuyer(OrderCloudModel):
    """An OrderCloud SupplierBuyer.

    Attributes:
        ID:
        Name:
    """

    ID: Optional[str] = None
    Name: Optional[str] = None


class Supplier(OrderCloudModel):
    """An OrderCloud Supplier.

    Attributes:
        ID:
        Name:
        Active: If false, all user authentication is blocked.
        DateCreated:  (read-only)
        AllBuyersCanOrder: If false, buyers will only be able to set ToCompanyID on an order to the marketplace owner, or suppliers they have an explicit relationship to.
        xp:
    """

    ID: Optional[str] = None
    Name: Optional[str] = None
    Active: Optional[bool] = None
    DateCreated: Optional[str] = None
    AllBuyersCanOrder: Optional[bool] = None
    xp: Optional[dict[str, Any]] = None
