# GENERATED by tools/codegen — DO NOT EDIT
# Source: ordercloud-openapi-v3.json
"""OrderCloud EntitySyncConfig and related models."""

from __future__ import annotations
from typing import Any, Optional
from pydantic import Field

from .shared import OrderCloudModel

__all__ = [
    "EntitySyncConfig",
    "OrderSyncConfig",
    "ProductSyncConfig",
    "SyncAdminUser",
    "SyncBuyer",
    "SyncBuyerUser",
    "SyncBuyerUserGroup",
    "SyncCategory",
    "SyncInventoryRecord",
    "SyncProduct",
    "SyncSupplier",
    "SyncSupplierUser",
]


class EntitySyncConfig(OrderCloudModel):
    """An OrderCloud EntitySyncConfig.

    Attributes:
        delivery_config_id:
        sync_entity_changed:
        sync_entity_deleted:
        paused:
    """

    delivery_config_id: Optional[str] = Field(None, alias="DeliveryConfigID")
    sync_entity_changed: Optional[bool] = Field(None, alias="SyncEntityChanged")
    sync_entity_deleted: Optional[bool] = Field(None, alias="SyncEntityDeleted")
    paused: Optional[bool] = Field(None, alias="Paused")


class OrderSyncConfig(OrderCloudModel):
    """An OrderCloud OrderSyncConfig.

    Attributes:
        delivery_config_id:
        config_data:
    """

    delivery_config_id: Optional[str] = Field(None, alias="DeliveryConfigID")
    config_data: Optional[dict[str, Any]] = Field(None, alias="ConfigData")


class ProductSyncConfig(OrderCloudModel):
    """An OrderCloud ProductSyncConfig.

    Attributes:
        sync_product_changed:
        sync_product_deleted:
        delivery_config_id:
        config_data:
        paused:
        exclude_price_schedules:
    """

    sync_product_changed: Optional[bool] = Field(None, alias="SyncProductChanged")
    sync_product_deleted: Optional[bool] = Field(None, alias="SyncProductDeleted")
    delivery_config_id: Optional[str] = Field(None, alias="DeliveryConfigID")
    config_data: Optional[dict[str, Any]] = Field(None, alias="ConfigData")
    paused: Optional[bool] = Field(None, alias="Paused")
    exclude_price_schedules: Optional[bool] = Field(None, alias="ExcludePriceSchedules")


class SyncAdminUser(OrderCloudModel):
    """An OrderCloud SyncAdminUser.

    Attributes:
        user_id:
    """

    user_id: Optional[str] = Field(None, alias="UserID")


class SyncBuyer(OrderCloudModel):
    """An OrderCloud SyncBuyer.

    Attributes:
        buyer_id:
    """

    buyer_id: Optional[str] = Field(None, alias="BuyerID")


class SyncBuyerUser(OrderCloudModel):
    """An OrderCloud SyncBuyerUser.

    Attributes:
        buyer_id:
        user_id:
    """

    buyer_id: Optional[str] = Field(None, alias="BuyerID")
    user_id: Optional[str] = Field(None, alias="UserID")


class SyncBuyerUserGroup(OrderCloudModel):
    """An OrderCloud SyncBuyerUserGroup.

    Attributes:
        buyer_id:
        user_group_id:
    """

    buyer_id: Optional[str] = Field(None, alias="BuyerID")
    user_group_id: Optional[str] = Field(None, alias="UserGroupID")


class SyncCategory(OrderCloudModel):
    """An OrderCloud SyncCategory.

    Attributes:
        catalog_id:
        category_id:
    """

    catalog_id: Optional[str] = Field(None, alias="CatalogID")
    category_id: Optional[str] = Field(None, alias="CategoryID")


class SyncInventoryRecord(OrderCloudModel):
    """An OrderCloud SyncInventoryRecord.

    Attributes:
        product_id:
        inventory_record_id:
    """

    product_id: Optional[str] = Field(None, alias="ProductID")
    inventory_record_id: Optional[str] = Field(None, alias="InventoryRecordID")


class SyncProduct(OrderCloudModel):
    """An OrderCloud SyncProduct.

    Attributes:
        product_id:
    """

    product_id: Optional[str] = Field(None, alias="ProductID")


class SyncSupplier(OrderCloudModel):
    """An OrderCloud SyncSupplier.

    Attributes:
        supplier_id:
    """

    supplier_id: Optional[str] = Field(None, alias="SupplierID")


class SyncSupplierUser(OrderCloudModel):
    """An OrderCloud SyncSupplierUser.

    Attributes:
        supplier_id:
        user_id:
    """

    supplier_id: Optional[str] = Field(None, alias="SupplierID")
    user_id: Optional[str] = Field(None, alias="UserID")
