# GENERATED by tools/codegen — DO NOT EDIT
# Source: ordercloud-openapi-v3.json
"""OrderCloud UserGroup models."""

from __future__ import annotations
from typing import Generic, Optional
from pydantic import Field

from .shared import OrderCloudModel, XP

__all__ = ["UserGroup"]


class UserGroup(OrderCloudModel, Generic[XP]):
    """An OrderCloud UserGroup.

    Attributes:
        id:
        name:
        description:
        xp:
    """

    id: Optional[str] = Field(None, alias="ID")
    name: Optional[str] = Field(None, alias="Name")
    description: Optional[str] = Field(None, alias="Description")
    xp: Optional[XP] = Field(None, alias="xp")
