# GENERATED by tools/codegen — DO NOT EDIT
# Source: ordercloud-openapi-v3.json
"""OrderCloud Locale and related models."""

from __future__ import annotations
from enum import Enum
from typing import Generic, Optional

from .shared import OrderCloudModel, XP

__all__ = [
    "UserOrderMoveOption",
    "Locale",
    "MeBuyer",
    "MeSeller",
    "MeSupplier",
    "OrderUser",
    "MeUser",
    "User",
]


class UserOrderMoveOption(str, Enum):
    """"""

    _None = "None"
    Unsubmitted = "Unsubmitted"
    All = "All"


class Locale(OrderCloudModel):
    """An OrderCloud Locale.

    Attributes:
        ID:
        OwnerID: ID of the organization that owns the Locale. Only the marketplace owner can override the OwnerID on create.
        Currency: We recommend using ISO-4217 currency codes for compatibility with tax and payment processors.
        Language: We recommend using ISO-639 language code - ISO-3166 Country code (e.g. en-US).
    """

    ID: Optional[str] = None
    OwnerID: Optional[str] = None
    Currency: Optional[str] = None
    Language: Optional[str] = None


class MeBuyer(OrderCloudModel):
    """An OrderCloud MeBuyer.

    Attributes:
        ID:  (read-only)
        DefaultCatalogID:  (read-only)
    """

    ID: Optional[str] = None
    DefaultCatalogID: Optional[str] = None


class MeSeller(OrderCloudModel):
    """An OrderCloud MeSeller.

    Attributes:
        ID:  (read-only)
    """

    ID: Optional[str] = None


class MeSupplier(OrderCloudModel):
    """An OrderCloud MeSupplier.

    Attributes:
        ID:  (read-only)
    """

    ID: Optional[str] = None


class OrderUser(OrderCloudModel, Generic[XP]):
    """An OrderCloud OrderUser.

    Attributes:
        ID:
        CompanyID:  (read-only)
        Username: Must be unique across all organizations.
        Password:
        FirstName:
        LastName:
        Email:
        Phone:
        TermsAccepted:
        Active: If false, authentication is prohibited.
        xp:
        AvailableRoles: List of roles currently available to the user via all security profile assignments. (read-only)
        Locale: Most specific locale assigned to the user, if any. (read-only)
        DateCreated:  (read-only)
        LastActive: Accurate within a few minutes. Includes impersonation activity. (read-only)
        PasswordLastSetDate: Can be used in conjunction with SecurityProfile.PasswordConfig to enforce password reset schedules. (read-only)
    """

    ID: Optional[str] = None
    CompanyID: Optional[str] = None
    Username: Optional[str] = None
    Password: Optional[str] = None
    FirstName: Optional[str] = None
    LastName: Optional[str] = None
    Email: Optional[str] = None
    Phone: Optional[str] = None
    TermsAccepted: Optional[str] = None
    Active: Optional[bool] = None
    xp: Optional[XP] = None
    AvailableRoles: Optional[list[str]] = None
    Locale: Optional[_Locale] = None
    DateCreated: Optional[str] = None
    LastActive: Optional[str] = None
    PasswordLastSetDate: Optional[str] = None


class MeUser(OrderCloudModel, Generic[XP]):
    """An OrderCloud MeUser.

    Attributes:
        Buyer:  (read-only)
        Supplier:  (read-only)
        Seller:  (read-only)
        ID:
        CompanyID:  (read-only)
        Username: Must be unique across all organizations.
        Password:
        FirstName:
        LastName:
        Email:
        Phone:
        TermsAccepted:
        Active: If false, authentication is prohibited.
        xp:
        AvailableRoles: List of roles currently available to the user via all security profile assignments. (read-only)
        Locale: Most specific locale assigned to the user, if any. (read-only)
        DateCreated:  (read-only)
        LastActive: Accurate within a few minutes. Includes impersonation activity. (read-only)
        PasswordLastSetDate: Can be used in conjunction with SecurityProfile.PasswordConfig to enforce password reset schedules. (read-only)
    """

    Buyer: Optional[MeBuyer] = None
    Supplier: Optional[MeSupplier] = None
    Seller: Optional[MeSeller] = None
    ID: Optional[str] = None
    CompanyID: Optional[str] = None
    Username: Optional[str] = None
    Password: Optional[str] = None
    FirstName: Optional[str] = None
    LastName: Optional[str] = None
    Email: Optional[str] = None
    Phone: Optional[str] = None
    TermsAccepted: Optional[str] = None
    Active: Optional[bool] = None
    xp: Optional[XP] = None
    AvailableRoles: Optional[list[str]] = None
    Locale: Optional[_Locale] = None
    DateCreated: Optional[str] = None
    LastActive: Optional[str] = None
    PasswordLastSetDate: Optional[str] = None


class User(OrderCloudModel, Generic[XP]):
    """An OrderCloud User.

    Attributes:
        FailedLoginAttempts: Number of times the user failed authentication due to incorrect password since last successful attempt, or since being unlocked. (read-only)
        ID:
        CompanyID:  (read-only)
        Username: Must be unique across all organizations.
        Password:
        FirstName:
        LastName:
        Email:
        Phone:
        TermsAccepted:
        Active: If false, authentication is prohibited.
        xp:
        AvailableRoles: List of roles currently available to the user via all security profile assignments. (read-only)
        Locale: Most specific locale assigned to the user, if any. (read-only)
        DateCreated:  (read-only)
        LastActive: Accurate within a few minutes. Includes impersonation activity. (read-only)
        PasswordLastSetDate: Can be used in conjunction with SecurityProfile.PasswordConfig to enforce password reset schedules. (read-only)
    """

    FailedLoginAttempts: int = 0
    ID: Optional[str] = None
    CompanyID: Optional[str] = None
    Username: Optional[str] = None
    Password: Optional[str] = None
    FirstName: Optional[str] = None
    LastName: Optional[str] = None
    Email: Optional[str] = None
    Phone: Optional[str] = None
    TermsAccepted: Optional[str] = None
    Active: Optional[bool] = None
    xp: Optional[XP] = None
    AvailableRoles: Optional[list[str]] = None
    Locale: Optional[_Locale] = None
    DateCreated: Optional[str] = None
    LastActive: Optional[str] = None
    PasswordLastSetDate: Optional[str] = None


_Locale = Locale
