# GENERATED by tools/codegen — DO NOT EDIT
# Source: ordercloud-openapi-v3.json
"""OrderCloud Locale and related models."""

from __future__ import annotations
from typing import Generic, Optional
from pydantic import Field

from .shared import OrderCloudEnum, OrderCloudModel, XP

__all__ = [
    "UserOrderMoveOption",
    "Locale",
    "MeBuyer",
    "MeSeller",
    "MeSupplier",
    "OrderUser",
    "MeUser",
    "User",
]


class UserOrderMoveOption(OrderCloudEnum):
    """"""

    _None = "None"
    Unsubmitted = "Unsubmitted"
    All = "All"


class Locale(OrderCloudModel):
    """An OrderCloud Locale.

    Attributes:
        id:
        owner_id: ID of the organization that owns the Locale. Only the marketplace owner can override the OwnerID on create.
        currency: We recommend using ISO-4217 currency codes for compatibility with tax and payment processors.
        language: We recommend using ISO-639 language code - ISO-3166 Country code (e.g. en-US).
    """

    id: Optional[str] = Field(None, alias="ID")
    owner_id: Optional[str] = Field(None, alias="OwnerID")
    currency: Optional[str] = Field(None, alias="Currency")
    language: Optional[str] = Field(None, alias="Language")


class MeBuyer(OrderCloudModel):
    """An OrderCloud MeBuyer.

    Attributes:
        id:  (read-only)
        default_catalog_id:  (read-only)
    """

    id: Optional[str] = Field(None, alias="ID")
    default_catalog_id: Optional[str] = Field(None, alias="DefaultCatalogID")


class MeSeller(OrderCloudModel):
    """An OrderCloud MeSeller.

    Attributes:
        id:  (read-only)
    """

    id: Optional[str] = Field(None, alias="ID")


class MeSupplier(OrderCloudModel):
    """An OrderCloud MeSupplier.

    Attributes:
        id:  (read-only)
    """

    id: Optional[str] = Field(None, alias="ID")


class OrderUser(OrderCloudModel, Generic[XP]):
    """An OrderCloud OrderUser.

    Attributes:
        id:
        company_id:  (read-only)
        username: Must be unique across all organizations.
        password:
        first_name:
        last_name:
        email:
        phone:
        terms_accepted:
        active: If false, authentication is prohibited.
        xp:
        available_roles: List of roles currently available to the user via all security profile assignments. (read-only)
        locale: Most specific locale assigned to the user, if any. (read-only)
        date_created:  (read-only)
        last_active: Accurate within a few minutes. Includes impersonation activity. (read-only)
        password_last_set_date: Can be used in conjunction with SecurityProfile.PasswordConfig to enforce password reset schedules. (read-only)
    """

    id: Optional[str] = Field(None, alias="ID")
    company_id: Optional[str] = Field(None, alias="CompanyID")
    username: Optional[str] = Field(None, alias="Username")
    password: Optional[str] = Field(None, alias="Password")
    first_name: Optional[str] = Field(None, alias="FirstName")
    last_name: Optional[str] = Field(None, alias="LastName")
    email: Optional[str] = Field(None, alias="Email")
    phone: Optional[str] = Field(None, alias="Phone")
    terms_accepted: Optional[str] = Field(None, alias="TermsAccepted")
    active: Optional[bool] = Field(None, alias="Active")
    xp: Optional[XP] = Field(None, alias="xp")
    available_roles: Optional[list[str]] = Field(None, alias="AvailableRoles")
    locale: Optional[_Locale] = Field(None, alias="Locale")
    date_created: Optional[str] = Field(None, alias="DateCreated")
    last_active: Optional[str] = Field(None, alias="LastActive")
    password_last_set_date: Optional[str] = Field(None, alias="PasswordLastSetDate")


class MeUser(OrderCloudModel, Generic[XP]):
    """An OrderCloud MeUser.

    Attributes:
        buyer:  (read-only)
        supplier:  (read-only)
        seller:  (read-only)
        id:
        company_id:  (read-only)
        username: Must be unique across all organizations.
        password:
        first_name:
        last_name:
        email:
        phone:
        terms_accepted:
        active: If false, authentication is prohibited.
        xp:
        available_roles: List of roles currently available to the user via all security profile assignments. (read-only)
        locale: Most specific locale assigned to the user, if any. (read-only)
        date_created:  (read-only)
        last_active: Accurate within a few minutes. Includes impersonation activity. (read-only)
        password_last_set_date: Can be used in conjunction with SecurityProfile.PasswordConfig to enforce password reset schedules. (read-only)
    """

    buyer: Optional[MeBuyer] = Field(None, alias="Buyer")
    supplier: Optional[MeSupplier] = Field(None, alias="Supplier")
    seller: Optional[MeSeller] = Field(None, alias="Seller")
    id: Optional[str] = Field(None, alias="ID")
    company_id: Optional[str] = Field(None, alias="CompanyID")
    username: Optional[str] = Field(None, alias="Username")
    password: Optional[str] = Field(None, alias="Password")
    first_name: Optional[str] = Field(None, alias="FirstName")
    last_name: Optional[str] = Field(None, alias="LastName")
    email: Optional[str] = Field(None, alias="Email")
    phone: Optional[str] = Field(None, alias="Phone")
    terms_accepted: Optional[str] = Field(None, alias="TermsAccepted")
    active: Optional[bool] = Field(None, alias="Active")
    xp: Optional[XP] = Field(None, alias="xp")
    available_roles: Optional[list[str]] = Field(None, alias="AvailableRoles")
    locale: Optional[_Locale] = Field(None, alias="Locale")
    date_created: Optional[str] = Field(None, alias="DateCreated")
    last_active: Optional[str] = Field(None, alias="LastActive")
    password_last_set_date: Optional[str] = Field(None, alias="PasswordLastSetDate")


class User(OrderCloudModel, Generic[XP]):
    """An OrderCloud User.

    Attributes:
        failed_login_attempts: Number of times the user failed authentication due to incorrect password since last successful attempt, or since being unlocked. (read-only)
        id:
        company_id:  (read-only)
        username: Must be unique across all organizations.
        password:
        first_name:
        last_name:
        email:
        phone:
        terms_accepted:
        active: If false, authentication is prohibited.
        xp:
        available_roles: List of roles currently available to the user via all security profile assignments. (read-only)
        locale: Most specific locale assigned to the user, if any. (read-only)
        date_created:  (read-only)
        last_active: Accurate within a few minutes. Includes impersonation activity. (read-only)
        password_last_set_date: Can be used in conjunction with SecurityProfile.PasswordConfig to enforce password reset schedules. (read-only)
    """

    failed_login_attempts: int = Field(0, alias="FailedLoginAttempts")
    id: Optional[str] = Field(None, alias="ID")
    company_id: Optional[str] = Field(None, alias="CompanyID")
    username: Optional[str] = Field(None, alias="Username")
    password: Optional[str] = Field(None, alias="Password")
    first_name: Optional[str] = Field(None, alias="FirstName")
    last_name: Optional[str] = Field(None, alias="LastName")
    email: Optional[str] = Field(None, alias="Email")
    phone: Optional[str] = Field(None, alias="Phone")
    terms_accepted: Optional[str] = Field(None, alias="TermsAccepted")
    active: Optional[bool] = Field(None, alias="Active")
    xp: Optional[XP] = Field(None, alias="xp")
    available_roles: Optional[list[str]] = Field(None, alias="AvailableRoles")
    locale: Optional[_Locale] = Field(None, alias="Locale")
    date_created: Optional[str] = Field(None, alias="DateCreated")
    last_active: Optional[str] = Field(None, alias="LastActive")
    password_last_set_date: Optional[str] = Field(None, alias="PasswordLastSetDate")


_Locale = Locale
