# GENERATED by tools/codegen — DO NOT EDIT
# Source: ordercloud-openapi-v3.json
"""OrderCloud UserGroup models."""

from __future__ import annotations
from typing import Generic, Optional

from .shared import OrderCloudModel, XP

__all__ = ["UserGroup"]


class UserGroup(OrderCloudModel, Generic[XP]):
    """An OrderCloud UserGroup.

    Attributes:
        ID:
        Name:
        Description:
        xp:
    """

    ID: Optional[str] = None
    Name: Optional[str] = None
    Description: Optional[str] = None
    xp: Optional[XP] = None
